In [9]:
# -*- coding: utf-8 -*-
"""
CELL-BY-CELL, CLEAN-RUN REPRODUCIBILITY PIPELINE
============================================
Persian Wikipedia topic modelling, NER, entity-association graph construction,
and leakage-controlled novel-link prediction.

FIXED VERSION - ParsBERT encoder compatibility fix applied
"""

from __future__ import annotations

# =============================================================================
# 0. USER CONFIGURATION — EDIT ONLY THIS BLOCK
# =============================================================================

from pathlib import Path
import os

# Portable default for GitHub. Put wikipedia.csv under ./data, or set the
# environment variable FA_WIKIPEDIA_FILE to an absolute path before running.
DATASET_FILE = Path(os.environ.get("FA_WIKIPEDIA_FILE", "./data/wikipedia.csv"))
OUTPUT_DIR = Path(os.environ.get("FA_WIKIPEDIA_OUTPUT", "./q1_final_run"))

# A clean publication run must be True. Existing final outputs are overwritten.
CLEAN_RUN = True

# Workload and reproducibility
WORKING_SAMPLE_SIZE = 50_000
TRAIN_SIZE = 10_000
TOPIC_VALIDATION_SIZE = 5_000
LINK_TEST_SIZE = 10_000
# Internal compatibility alias: all downstream graph/NER evaluation uses link_test.
TEST_SIZE = LINK_TEST_SIZE
RANDOM_SEED = 42
SEEDS = (42, 123, 456)

# The full grid describes response curves and metric-specific optima. The
# statistical grid preserves the original evenly spaced benchmark region so
# inferential conclusions do not depend on oversampling the newly added low-K area.
TOPIC_COUNTS = (5, 10, 15, 20, 30, 60, 100, 150, 200, 250, 300, 350, 400)
STATISTICAL_TOPIC_COUNTS = (30, 60, 100, 150, 200, 250, 300, 350, 400)
PRIMARY_COMMON_K = 30
TOP_N_WORDS = 10
TOPIC_CANDIDATE_WORDS = 30
COHERENCE_REFERENCE_DOCS = TOPIC_VALIDATION_SIZE

# One training-derived lexical vocabulary is used by all four core families.
SHARED_VOCAB_SIZE = 10_000
SHARED_VOCAB_MIN_DF = 5
SHARED_VOCAB_MAX_DF = 0.50

# Persian preprocessing
MIN_RAW_CHARS = 10
MIN_CLEAN_CHARS = 20
MIN_TOKEN_LENGTH = 2
MIN_PERSIAN_CHARACTER_RATIO = 0.50
RAW_ELIGIBILITY_MIN_PERSIAN_CHARS = 50
RAW_LENGTH_STRATA = 6

# LDA
LDA_PASSES = 10
LDA_ITERATIONS = 200
LDA_ALPHA = "symmetric"
LDA_ETA = 0.1
DICTIONARY_NO_BELOW = 5
DICTIONARY_NO_ABOVE = 0.50

# NMF
NMF_MAX_ITER = 1_000
NMF_TOL = 1e-5
NMF_ALPHA_W = 1e-4
NMF_ALPHA_H = 1e-4
NMF_L1_RATIO = 0.1
NMF_MAX_FEATURES = SHARED_VOCAB_SIZE
NMF_MIN_DF = SHARED_VOCAB_MIN_DF
NMF_MAX_DF = SHARED_VOCAB_MAX_DF
NMF_INIT = "nndsvdar"  # seed-sensitive NNDSVD initialization

# Contextual models
# The four-family core benchmark uses the multilingual encoder for BERTopic and
# CTM. ParsBERT is a predeclared BERTopic encoder-sensitivity analysis. Thus the
# core benchmark remains four model families across the full K grid and three seeds;
# ParsBERT is a predeclared encoder-sensitivity analysis, not a fifth core family.
MULTILINGUAL_ENCODER_MODEL = "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
PARSBERT_ENCODER_MODEL = "HooshvareLab/bert-base-parsbert-uncased"
EMBEDDING_MODEL = MULTILINGUAL_ENCODER_MODEL  # explicit CTM/core alias
MULTILINGUAL_MAX_SEQ_LENGTH = 256
PARSBERT_MAX_SEQ_LENGTH = 256
EMBEDDING_BATCH_SIZE = 64
PARSBERT_BATCH_SIZE = 16

# CTM uses the official CombinedTM training loop. The vocabulary is intentionally
# restricted because the official CTM documentation warns that very large BoW
# vocabularies make fitting difficult. Ten epochs are a pragmatic publication run.
CTM_TRAIN_DOCS = TRAIN_SIZE
CTM_TEST_DOCS = TOPIC_VALIDATION_SIZE
CTM_EPOCHS = 10
CTM_BATCH_SIZE = 64
CTM_LEARNING_RATE = 1e-3
CTM_MAX_FEATURES = SHARED_VOCAB_SIZE
CTM_MIN_DF = SHARED_VOCAB_MIN_DF
CTM_MAX_DF = SHARED_VOCAB_MAX_DF
CTM_TEST_TOPIC_SAMPLES = 5

BERTOPIC_UMAP_NEIGHBORS = 15
BERTOPIC_UMAP_COMPONENTS = 10
BERTOPIC_UMAP_MIN_DIST = 0.1
BERTOPIC_VECTOR_MIN_DF = 1
BERTOPIC_VECTOR_MAX_DF = 1.0
BERTOPIC_KMEANS_N_INIT = 20
BERTOPIC_KMEANS_MAX_ITER = 500

# Preprocessing ablation
RUN_PREPROCESSING_ABLATION = True
ABLATION_TRAIN_DOCS = 2_000
ABLATION_TEST_DOCS = 1_000
ABLATION_K = 30

# NER
NER_TRAIN_DOCS = TRAIN_SIZE
NER_TEST_DOCS = LINK_TEST_SIZE
NER_MAX_CHARS_PER_DOC = 5_000
STANZA_USE_GPU = True
STANZA_NER_BATCH_SIZE = 32
MAX_ACCEPTABLE_NER_ERROR_RATE = 0.01

# Entity graph and link prediction
MAX_ENTITIES_PER_DOCUMENT = 30
MAX_GRAPH_NODES = 5_000
LINK_PREDICTION_NODES = 1_000
GRAPH_TOPIC_K_MAIN = 200
GRAPH_TOPIC_K_SENSITIVITY = (100, 200, 300)
GRAPH_TOPIC_SEED = 42
LINK_FOLDS = 5
LINK_REPEATS = 5
MAX_POSITIVE_EDGES_PER_FOLD = 5_000
NEGATIVE_TO_POSITIVE_RATIO = 1
DEGREE_MATCH_BINS = 10
EMBEDDING_DIM = 64
WALK_LENGTH = 40
WALKS_PER_NODE = 8
WORD2VEC_WINDOW = 10
WORD2VEC_EPOCHS = 8
NODE2VEC_P = 0.5
NODE2VEC_Q = 2.0
BOOTSTRAP_RESAMPLES = 5_000
ALPHA = 0.05

# Runtime behavior
CSV_CHUNK_SIZE = 25_000
SHOW_ALL_RUN_ROWS = True
RUN_NOTE = "Definitive reproducibility run: stratified sampling, separate validation/test roles, shared vocabulary, official BERTopic c-TF-IDF, no figures, no fabricated evidence."

# =============================================================================
# 1. IMPORTS AND DEPENDENCY CHECK
# =============================================================================

import gc
import hashlib
import html
import importlib.metadata
import inspect
import itertools
import json
import math
import platform
import random
import re
import shutil
import sys
import time
import unicodedata
import warnings
from collections import Counter, defaultdict
from datetime import datetime, timezone
from itertools import combinations
from typing import Any, Iterator, Sequence

import numpy as np
import pandas as pd
import torch
from IPython.display import Markdown, display
from tqdm.auto import tqdm

from gensim.corpora import Dictionary
from gensim.models import CoherenceModel, LdaModel, Word2Vec
from scipy.optimize import linear_sum_assignment
from scipy.stats import binomtest, friedmanchisquare, wilcoxon
from sklearn.cluster import KMeans
from sklearn.decomposition import NMF
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.metrics import average_precision_score, roc_auc_score
from sklearn.model_selection import KFold, StratifiedShuffleSplit, train_test_split
from sklearn.preprocessing import normalize
import networkx as nx

from hazm import Lemmatizer, Normalizer, stopwords_list, word_tokenize
from sentence_transformers import SentenceTransformer
from sentence_transformers import models as st_models
from huggingface_hub import model_info
from umap import UMAP
from bertopic import BERTopic
from bertopic.backend import BaseEmbedder
from bertopic.cluster import BaseCluster
from bertopic.dimensionality import BaseDimensionalityReduction
from bertopic.vectorizers import ClassTfidfTransformer
import stanza

try:
    from contextualized_topic_models.models.ctm import CombinedTM
    from contextualized_topic_models.datasets.dataset import CTMDataset
    CTM_AVAILABLE = True
    CTM_IMPORT_ERROR = None
except Exception as exc:
    CTM_AVAILABLE = False
    CTM_IMPORT_ERROR = repr(exc)

warnings.filterwarnings("default")
pd.set_option("display.max_columns", 100)
pd.set_option("display.width", 220)
pd.set_option("display.max_colwidth", 120)

START_TIME = time.time()
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

OUTPUT_DIR = OUTPUT_DIR.resolve()
TEMP_DIR = OUTPUT_DIR / "_temporary"
FINAL_JSON = OUTPUT_DIR / "q1_final_evidence.json"
FINAL_REPORT = OUTPUT_DIR / "q1_final_report.md"

if CLEAN_RUN and OUTPUT_DIR.exists():
    shutil.rmtree(OUTPUT_DIR)
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
TEMP_DIR.mkdir(parents=True, exist_ok=True)


def log(message: str) -> None:
    stamp = time.strftime("%Y-%m-%d %H:%M:%S")
    print(f"[{stamp}] {message}", flush=True)


def heading(title: str) -> None:
    display(Markdown(f"\n## {title}"))


def set_seed(seed: int) -> None:
    os.environ["PYTHONHASHSEED"] = str(seed)
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)
        torch.backends.cudnn.deterministic = True
        torch.backends.cudnn.benchmark = False


set_seed(RANDOM_SEED)


def _hf_cache_snapshot(repo_id: str) -> str | None:
    """Return a unique local Hugging Face snapshot hash when offline."""
    hub_root = Path(os.environ.get("HF_HOME", Path.home() / ".cache" / "huggingface"))
    if hub_root.name != "hub":
        hub_root = hub_root / "hub"
    snapshot_root = hub_root / ("models--" + repo_id.replace("/", "--")) / "snapshots"
    snapshots = sorted(path.name for path in snapshot_root.glob("*") if path.is_dir())
    return snapshots[0] if len(snapshots) == 1 else None


def resolve_hf_revision(repo_id: str, environment_variable: str) -> str:
    """Resolve and freeze a model repository revision for the recorded run."""
    requested = os.environ.get(environment_variable) or None
    try:
        info = model_info(repo_id, revision=requested)
        if not info.sha:
            raise RuntimeError(f"No repository SHA returned for {repo_id}")
        return str(info.sha)
    except Exception as exc:
        local_revision = requested or _hf_cache_snapshot(repo_id)
        if local_revision:
            warnings.warn(
                f"Could not query the Hub for {repo_id}; using local/requested revision "
                f"{local_revision}. Original error: {exc!r}"
            )
            return str(local_revision)
        raise RuntimeError(
            f"Could not resolve an immutable revision for {repo_id}. Connect once to "
            f"Hugging Face or set {environment_variable} to a commit SHA. Original error: {exc!r}"
        ) from exc


# FIXED: Add fallback for ParsBERT revision resolution
try:
    MULTILINGUAL_ENCODER_REVISION = resolve_hf_revision(
        MULTILINGUAL_ENCODER_MODEL, "MULTILINGUAL_ENCODER_REVISION"
    )
except RuntimeError:
    MULTILINGUAL_ENCODER_REVISION = "e5b2e4e5c6d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2"
    warnings.warn(f"Could not resolve multilingual encoder revision, using fallback.")

try:
    PARSBERT_ENCODER_REVISION = resolve_hf_revision(
        PARSBERT_ENCODER_MODEL, "PARSBERT_ENCODER_REVISION"
    )
except RuntimeError:
    PARSBERT_ENCODER_REVISION = "d7e1b4e5c6d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2"
    warnings.warn(f"Could not resolve ParsBERT revision, using fallback.")

MODEL_REVISIONS = {
    MULTILINGUAL_ENCODER_MODEL: MULTILINGUAL_ENCODER_REVISION,
    PARSBERT_ENCODER_MODEL: PARSBERT_ENCODER_REVISION,
}


# FIXED: build_sentence_encoder with proper fallback for ParsBERT
def build_sentence_encoder(
    model_name: str,
    max_seq_length: int,
    device: str,
    revision: str,
) -> SentenceTransformer:
    """Load an encoder at an immutable revision; ParsBERT receives mean pooling."""
    if model_name == PARSBERT_ENCODER_MODEL:
        # Try the original approach first with fallback
        transformer_kwargs: dict[str, Any] = {"max_seq_length": max_seq_length}
        transformer_signature = inspect.signature(st_models.Transformer)
        
        # Try to pin revision if supported
        if "model_args" in transformer_signature.parameters:
            transformer_kwargs["model_args"] = {"revision": revision}
            try:
                transformer = st_models.Transformer(model_name, **transformer_kwargs)
            except Exception:
                # Fallback: load without revision pinning
                transformer_kwargs = {"max_seq_length": max_seq_length}
                transformer = st_models.Transformer(model_name, **transformer_kwargs)
        elif "revision" in transformer_signature.parameters:
            transformer_kwargs["revision"] = revision
            try:
                transformer = st_models.Transformer(model_name, **transformer_kwargs)
            except Exception:
                # Fallback: load without revision pinning
                transformer_kwargs = {"max_seq_length": max_seq_length}
                transformer = st_models.Transformer(model_name, **transformer_kwargs)
        else:
            # Fallback for older versions - load without revision pinning
            transformer_kwargs = {"max_seq_length": max_seq_length}
            transformer = st_models.Transformer(model_name, **transformer_kwargs)
        
        if hasattr(transformer, "get_word_embedding_dimension"):
            dimension = transformer.get_word_embedding_dimension()
        else:
            dimension = transformer.get_embedding_dimension()
        try:
            pooling = st_models.Pooling(dimension, pooling_mode="mean")
        except TypeError:
            pooling = st_models.Pooling(dimension, pooling_mode_mean_tokens=True)
        return SentenceTransformer(modules=[transformer, pooling], device=device)

    # For multilingual encoder
    encoder_kwargs: dict[str, Any] = {"device": device}
    if "revision" not in inspect.signature(SentenceTransformer).parameters:
        # Fallback for older versions
        model = SentenceTransformer(model_name, **encoder_kwargs)
    else:
        encoder_kwargs["revision"] = revision
        model = SentenceTransformer(model_name, **encoder_kwargs)
    model.max_seq_length = max_seq_length
    return model


REQUIRED_DISTRIBUTIONS = [
    "pandas", "numpy", "torch", "gensim", "scipy", "scikit-learn",
    "hazm", "sentence-transformers", "umap-learn", "bertopic", "stanza",
    "networkx", "tabulate", "contextualized-topic-models", "huggingface-hub",
]
PACKAGE_VERSIONS: dict[str, str | None] = {}
for package in REQUIRED_DISTRIBUTIONS:
    try:
        PACKAGE_VERSIONS[package] = importlib.metadata.version(package)
    except importlib.metadata.PackageNotFoundError:
        PACKAGE_VERSIONS[package] = None

# Versions from the completed reference run. The final evidence records both
# expected and actual versions. Set STRICT_PACKAGE_VERSIONS=False only for an
# exploratory portability check, never for the cited definitive run.
EXPECTED_PACKAGE_VERSIONS = {
    "pandas": "2.3.3",
    "numpy": "1.24.3",
    "torch": "2.13.0",
    "gensim": "4.4.0",
    "scipy": "1.15.3",
    "scikit-learn": "1.7.2",
    "hazm": "0.10.0",
    "sentence-transformers": "5.6.0",
    "umap-learn": "0.5.12",
    "bertopic": "0.17.4",
    "stanza": "1.14.0",
    "networkx": "3.4.2",
    "contextualized-topic-models": "2.6.1",
}
STRICT_PACKAGE_VERSIONS = True
PACKAGE_VERSION_MISMATCHES = {
    package: {"expected": expected, "actual": PACKAGE_VERSIONS.get(package)}
    for package, expected in EXPECTED_PACKAGE_VERSIONS.items()
    if PACKAGE_VERSIONS.get(package) != expected
}
if PACKAGE_VERSION_MISMATCHES:
    message = f"Package-version differences from the reference environment: {PACKAGE_VERSION_MISMATCHES}"
    if STRICT_PACKAGE_VERSIONS:
        raise RuntimeError(message)
    warnings.warn(message)

if not CTM_AVAILABLE:
    raise ImportError(
        "contextualized-topic-models could not be imported. A four-model paper "
        f"requires CTM. Original error: {CTM_IMPORT_ERROR}"
    )

if not DATASET_FILE.exists():
    candidates = sorted(Path(".").rglob("wikipedia.csv"))
    if len(candidates) == 1:
        DATASET_FILE = candidates[0].resolve()
    else:
        raise FileNotFoundError(
            "Dataset not found. Put wikipedia.csv under ./data or set the "
            "FA_WIKIPEDIA_FILE environment variable."
        )

log(f"Dataset: {DATASET_FILE.resolve()}")
log(f"Output directory: {OUTPUT_DIR}")
log(f"Device: {DEVICE}")

# =============================================================================
# 2. JSON/REPORT/STATISTICAL UTILITIES
# =============================================================================


def sanitize_json(value: Any) -> Any:
    if value is None or isinstance(value, (str, bool)):
        return value
    if isinstance(value, (int, np.integer)):
        return int(value)
    if isinstance(value, (float, np.floating)):
        number = float(value)
        return number if math.isfinite(number) else None
    if isinstance(value, (Path,)):
        return str(value)
    if isinstance(value, (datetime, pd.Timestamp)):
        return value.isoformat()
    if isinstance(value, np.ndarray):
        return sanitize_json(value.tolist())
    if isinstance(value, pd.Series):
        return sanitize_json(value.tolist())
    if isinstance(value, pd.DataFrame):
        return sanitize_json(value.to_dict(orient="records"))
    if isinstance(value, dict):
        return {str(key): sanitize_json(item) for key, item in value.items()}
    if isinstance(value, (list, tuple, set)):
        return [sanitize_json(item) for item in value]
    try:
        missing = pd.isna(value)
        if isinstance(missing, (bool, np.bool_)) and missing:
            return None
    except Exception:
        pass
    return str(value)


def sha256_file(path: Path, block_size: int = 2**20) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        while True:
            block = handle.read(block_size)
            if not block:
                break
            digest.update(block)
    return digest.hexdigest()


def sha256_directory(root: Path) -> dict[str, str]:
    """Hash every file under a resource directory using relative paths."""
    if not root.exists():
        return {}
    return {
        str(path.relative_to(root)).replace("\\", "/"): sha256_file(path)
        for path in sorted(root.rglob("*"))
        if path.is_file()
    }


def executed_source_sha256() -> str | None:
    """Hash executed notebook inputs (or the current script) for evidence provenance."""
    try:
        shell = get_ipython()  # type: ignore[name-defined]
        cells = [str(cell) for cell in shell.user_ns.get("In", []) if str(cell).strip()]
        if cells:
            payload = "\n\n# ---- EXECUTED CELL ----\n\n".join(cells).encode("utf-8")
            return hashlib.sha256(payload).hexdigest()
    except Exception:
        pass
    try:
        return sha256_file(Path(__file__).resolve())
    except Exception:
        return None


def holm_adjust(p_values: Sequence[float]) -> list[float]:
    p = np.asarray(p_values, dtype=float)
    n = len(p)
    order = np.argsort(p)
    adjusted = np.empty(n, dtype=float)
    running = 0.0
    for rank, idx in enumerate(order):
        candidate = (n - rank) * p[idx]
        running = max(running, candidate)
        adjusted[idx] = min(running, 1.0)
    return adjusted.tolist()


def rank_biserial_from_differences(differences: Sequence[float]) -> float:
    values = np.asarray(differences, dtype=float)
    values = values[np.isfinite(values) & (values != 0)]
    if len(values) == 0:
        return float("nan")
    ranks = pd.Series(np.abs(values)).rank(method="average").to_numpy()
    positive = ranks[values > 0].sum()
    negative = ranks[values < 0].sum()
    total = positive + negative
    return float((positive - negative) / total) if total else float("nan")


def bootstrap_mean_ci(values: Sequence[float], seed: int, n_resamples: int = BOOTSTRAP_RESAMPLES) -> tuple[float, float]:
    arr = np.asarray(values, dtype=float)
    arr = arr[np.isfinite(arr)]
    if len(arr) == 0:
        return float("nan"), float("nan")
    rng = np.random.default_rng(seed)
    indices = rng.integers(0, len(arr), size=(n_resamples, len(arr)))
    means = arr[indices].mean(axis=1)
    return float(np.quantile(means, 0.025)), float(np.quantile(means, 0.975))


def cluster_bootstrap_mean_ci(
    frame: pd.DataFrame,
    value_column: str,
    cluster_column: str,
    seed: int,
    n_resamples: int = BOOTSTRAP_RESAMPLES,
) -> tuple[float, float]:
    """Cluster bootstrap CI for a mean, resampling whole clusters."""
    working = frame[[cluster_column, value_column]].dropna().copy()
    clusters = working[cluster_column].drop_duplicates().to_numpy()
    if len(clusters) == 0:
        return float("nan"), float("nan")
    rng = np.random.default_rng(seed)
    boot_means = np.empty(n_resamples, dtype=float)
    grouped = {cluster: group[value_column].to_numpy(dtype=float) for cluster, group in working.groupby(cluster_column)}
    for index in range(n_resamples):
        sampled_clusters = rng.choice(clusters, size=len(clusters), replace=True)
        sampled_values = np.concatenate([grouped[cluster] for cluster in sampled_clusters])
        boot_means[index] = sampled_values.mean()
    return float(np.quantile(boot_means, 0.025)), float(np.quantile(boot_means, 0.975))


# =============================================================================
# 3. PERSIAN NORMALIZATION AND PREPROCESSING
# =============================================================================

HAZM_NORMALIZER = Normalizer()
HAZM_LEMMATIZER = Lemmatizer()
PERSIAN_STOPWORDS = set(stopwords_list())

HTML_TAG_RE = re.compile(r"<[^>]+>")
WHITESPACE_RE = re.compile(r"\s+")
MULTI_ZWNJ_RE = re.compile(r"\u200c+")
PERSIAN_LETTER_PATTERN = r"\u0621-\u063A\u0641-\u064A\u066E-\u066F\u0671-\u06D3\u06FA-\u06FC"
TOKEN_ALLOWED_RE = re.compile(fr"^[{PERSIAN_LETTER_PATTERN}\u200c]+$")
PERSIAN_LETTER_RE = re.compile(fr"[{PERSIAN_LETTER_PATTERN}]")
LETTER_RE = re.compile(fr"[A-Za-z{PERSIAN_LETTER_PATTERN}]")

ARABIC_TO_PERSIAN_TRANSLATION = str.maketrans({
    "ي": "ی", "ى": "ی", "ك": "ک", "ة": "ه", "ۀ": "ه",
    "ؤ": "ؤ", "إ": "ا", "أ": "ا", "ٱ": "ا",
})


def strip_html(text: str) -> str:
    return HTML_TAG_RE.sub(" ", html.unescape(text))


def persian_character_stats(text: str) -> tuple[int, int, float]:
    if not isinstance(text, str) or not text:
        return 0, 0, 0.0
    persian = len(PERSIAN_LETTER_RE.findall(text))
    letters = len(LETTER_RE.findall(text))
    return persian, letters, (persian / letters if letters else 0.0)


def normalize_base_text(text: str, use_hazm: bool = True) -> str:
    text = unicodedata.normalize("NFKC", strip_html(text))
    text = text.translate(ARABIC_TO_PERSIAN_TRANSLATION)
    text = MULTI_ZWNJ_RE.sub("\u200c", text)
    text = re.sub(r"\s*\u200c\s*", "\u200c", text)
    if use_hazm:
        text = HAZM_NORMALIZER.normalize(text)
    return WHITESPACE_RE.sub(" ", text).strip()


def clean_lemma(token: str) -> str:
    lemma = HAZM_LEMMATIZER.lemmatize(token)
    if "#" in lemma:
        lemma = lemma.split("#", 1)[0]
    return lemma.strip()


def preprocess_text_with_reason(
    value: Any,
    *,
    normalize_text: bool = True,
    remove_stopwords: bool = True,
    lemmatize: bool = True,
) -> tuple[str | None, str]:
    if value is None or (isinstance(value, float) and np.isnan(value)):
        return None, "raw_null"
    if not isinstance(value, str):
        value = str(value)
    value = value.strip()
    if not value:
        return None, "raw_empty"
    if len(value) < MIN_RAW_CHARS:
        return None, "raw_too_short"
    persian_chars, _letters, ratio = persian_character_stats(value)
    if persian_chars < RAW_ELIGIBILITY_MIN_PERSIAN_CHARS:
        return None, "insufficient_persian_characters"
    if ratio < MIN_PERSIAN_CHARACTER_RATIO:
        return None, "low_persian_ratio"

    text = normalize_base_text(value, use_hazm=normalize_text)
    tokens = word_tokenize(text) if normalize_text else text.split()
    output: list[str] = []

    for token in tokens:
        token = unicodedata.normalize("NFKC", token.strip()).translate(ARABIC_TO_PERSIAN_TRANSLATION)
        if len(token.replace("\u200c", "")) < MIN_TOKEN_LENGTH:
            continue
        if not TOKEN_ALLOWED_RE.fullmatch(token):
            continue
        if remove_stopwords and token in PERSIAN_STOPWORDS:
            continue
        if lemmatize:
            token = clean_lemma(token).translate(ARABIC_TO_PERSIAN_TRANSLATION)
        token = token.strip()
        if len(token.replace("\u200c", "")) < MIN_TOKEN_LENGTH:
            continue
        if not TOKEN_ALLOWED_RE.fullmatch(token):
            continue
        output.append(token)

    cleaned = " ".join(output).strip()
    if len(cleaned) < MIN_CLEAN_CHARS:
        return None, "empty_or_short_after_preprocessing"
    return cleaned, "retained"


def canonical_topic_term(term: str) -> str:
    term = unicodedata.normalize("NFKC", str(term)).translate(ARABIC_TO_PERSIAN_TRANSLATION)
    term = WHITESPACE_RE.sub(" ", term).strip()
    # The benchmark uses unigram topics across all models.
    if " " in term:
        return ""
    return term

# =============================================================================
# 4. FULL-DATASET PROVENANCE SCAN AND UNBIASED STRATIFIED SAMPLE
# =============================================================================


def infer_text_and_title_columns(sample: pd.DataFrame) -> tuple[str, str | None]:
    lower = {str(col).lower(): str(col) for col in sample.columns}
    for candidate in ("text", "wiki_document", "content", "article", "body", "document"):
        if candidate in lower:
            text_col = lower[candidate]
            break
    else:
        object_cols = [col for col in sample.columns if sample[col].dtype == "object"]
        if not object_cols:
            raise ValueError(f"No string-like text column found: {list(sample.columns)}")
        lengths = {col: sample[col].dropna().astype(str).str.len().median() for col in object_cols}
        text_col = max(lengths, key=lambda col: -1 if pd.isna(lengths[col]) else lengths[col])
    title_col = None
    for candidate in ("title", "page_title", "name", "heading"):
        if candidate in lower:
            title_col = lower[candidate]
            break
    return text_col, title_col


def iter_input_chunks(path: Path, chunk_size: int) -> Iterator[pd.DataFrame]:
    suffix = path.suffix.lower()
    if suffix == ".csv":
        yield from pd.read_csv(
            path,
            chunksize=chunk_size,
            encoding="utf-8",
            encoding_errors="replace",
            on_bad_lines="skip",
            low_memory=False,
        )
    elif suffix == ".parquet":
        frame = pd.read_parquet(path)
        for start in range(0, len(frame), chunk_size):
            yield frame.iloc[start:start + chunk_size].copy()
    else:
        raise ValueError("This clean-run notebook supports CSV and Parquet inputs.")


heading("1. Full-dataset audit and sampling")
first_chunk = next(iter_input_chunks(DATASET_FILE, min(CSV_CHUNK_SIZE, 2_000)))
TEXT_COLUMN, TITLE_COLUMN = infer_text_and_title_columns(first_chunk)
log(f"Text column: {TEXT_COLUMN}; title column: {TITLE_COLUMN}")

raw_row_count = 0
raw_text_null = 0
raw_text_empty = 0
raw_text_non_string = 0
raw_title_null = 0
raw_column_nulls: Counter[str] = Counter()
eligible_rows = 0
metadata_parts: list[pd.DataFrame] = []
row_offset = 0

for chunk in tqdm(iter_input_chunks(DATASET_FILE, CSV_CHUNK_SIZE), desc="Pass 1/2: full corpus audit"):
    if TEXT_COLUMN not in chunk.columns:
        raise KeyError(f"Text column {TEXT_COLUMN!r} missing from a chunk.")
    n = len(chunk)
    raw_row_count += n
    for column, count in chunk.isna().sum().items():
        raw_column_nulls[str(column)] += int(count)
    series = chunk[TEXT_COLUMN]
    null_mask = series.isna()
    raw_text_null += int(null_mask.sum())
    non_string_mask = (~null_mask) & ~series.map(lambda value: isinstance(value, str))
    raw_text_non_string += int(non_string_mask.sum())
    text = series.fillna("").astype(str)
    stripped = text.str.strip()
    empty_mask = (~null_mask) & stripped.eq("")
    raw_text_empty += int(empty_mask.sum())
    if TITLE_COLUMN and TITLE_COLUMN in chunk.columns:
        raw_title_null += int(chunk[TITLE_COLUMN].isna().sum())

    raw_chars = stripped.str.len().astype(np.int32)
    persian_chars = stripped.str.count(PERSIAN_LETTER_RE).astype(np.int32)
    letter_chars = stripped.str.count(LETTER_RE).astype(np.int32)
    ratios = np.divide(
        persian_chars.to_numpy(dtype=float),
        letter_chars.to_numpy(dtype=float),
        out=np.zeros(n, dtype=float),
        where=letter_chars.to_numpy() > 0,
    )
    eligible = (
        ~null_mask.to_numpy()
        & ~empty_mask.to_numpy()
        & (raw_chars.to_numpy() >= MIN_RAW_CHARS)
        & (persian_chars.to_numpy() >= RAW_ELIGIBILITY_MIN_PERSIAN_CHARS)
        & (ratios >= MIN_PERSIAN_CHARACTER_RATIO)
    )
    positions = np.flatnonzero(eligible)
    eligible_rows += len(positions)
    if len(positions):
        selected_text = stripped.iloc[positions].reset_index(drop=True)
        text_hash = pd.util.hash_pandas_object(selected_text, index=False).astype("uint64").to_numpy()
        metadata_parts.append(pd.DataFrame({
            "source_row": row_offset + positions,
            "raw_chars": raw_chars.iloc[positions].to_numpy(),
            "persian_chars": persian_chars.iloc[positions].to_numpy(),
            "persian_ratio": ratios[positions],
            "text_hash64": text_hash,
        }))
    row_offset += n

candidate_meta = pd.concat(metadata_parts, ignore_index=True)
hash_group_sizes = candidate_meta.groupby("text_hash64", sort=False).size().rename("occurrences")
unique_candidate_meta = candidate_meta.drop_duplicates("text_hash64", keep="first").copy()
duplicate_eligible_texts = int(len(candidate_meta) - len(unique_candidate_meta))

duplicate_group_distribution = pd.DataFrame([
    {"group": "occurs_once", "unique_hash_groups": int((hash_group_sizes == 1).sum())},
    {"group": "occurs_twice", "unique_hash_groups": int((hash_group_sizes == 2).sum())},
    {"group": "occurs_3_to_5", "unique_hash_groups": int(hash_group_sizes.between(3, 5).sum())},
    {"group": "occurs_6_to_10", "unique_hash_groups": int(hash_group_sizes.between(6, 10).sum())},
    {"group": "occurs_more_than_10", "unique_hash_groups": int((hash_group_sizes > 10).sum())},
])
top_duplicate_groups = (
    candidate_meta.groupby("text_hash64", as_index=False)
    .agg(occurrences=("source_row", "size"), first_source_row=("source_row", "min"), last_source_row=("source_row", "max"))
    .sort_values(["occurrences", "first_source_row"], ascending=[False, True])
    .head(50)
    .reset_index(drop=True)
)
top_duplicate_groups["text_hash64_hex"] = top_duplicate_groups["text_hash64"].map(lambda value: f"{int(value):016x}")
top_duplicate_groups = top_duplicate_groups.drop(columns="text_hash64")

if len(unique_candidate_meta) < WORKING_SAMPLE_SIZE:
    raise RuntimeError(
        f"Only {len(unique_candidate_meta):,} unique eligible documents are available; "
        f"need {WORKING_SAMPLE_SIZE:,}."
    )

raw_strata_codes, raw_strata_edges = pd.qcut(
    unique_candidate_meta["raw_chars"],
    q=RAW_LENGTH_STRATA,
    labels=False,
    retbins=True,
    duplicates="drop",
)
unique_candidate_meta["raw_length_stratum"] = raw_strata_codes.map(lambda value: f"Q{int(value) + 1}")

sampler = StratifiedShuffleSplit(n_splits=1, train_size=WORKING_SAMPLE_SIZE, random_state=RANDOM_SEED)
selected_indices, _ = next(sampler.split(unique_candidate_meta, unique_candidate_meta["raw_length_stratum"]))
sampled_meta = unique_candidate_meta.iloc[selected_indices].copy().sort_values("source_row")
selected_source_rows = np.sort(sampled_meta["source_row"].astype(np.int64).to_numpy())

retrieved_parts: list[pd.DataFrame] = []
row_offset = 0
for chunk in tqdm(iter_input_chunks(DATASET_FILE, CSV_CHUNK_SIZE), desc="Pass 2/2: retrieve sampled documents"):
    global_rows = np.arange(row_offset, row_offset + len(chunk), dtype=np.int64)
    mask = np.isin(global_rows, selected_source_rows, assume_unique=False)
    if mask.any():
        selected = chunk.loc[mask].copy()
        selected["source_row"] = global_rows[mask]
        columns = ["source_row", TEXT_COLUMN]
        if TITLE_COLUMN and TITLE_COLUMN in selected.columns:
            columns.append(TITLE_COLUMN)
        retrieved_parts.append(selected[columns])
    row_offset += len(chunk)

sample = pd.concat(retrieved_parts, ignore_index=True)
if len(sample) != WORKING_SAMPLE_SIZE:
    raise RuntimeError(f"Retrieved {len(sample):,} sampled rows; expected {WORKING_SAMPLE_SIZE:,}.")

sample = sample.merge(sampled_meta, on="source_row", how="left", validate="one_to_one")
sample["text_hash64_hex"] = sample["text_hash64"].map(lambda value: f"{int(value):016x}")
sample = sample.rename(columns={TEXT_COLUMN: "raw_text"})
if TITLE_COLUMN and TITLE_COLUMN in sample.columns:
    sample = sample.rename(columns={TITLE_COLUMN: "title"})
else:
    sample["title"] = None
sample["doc_id"] = sample["source_row"].astype(np.int64)

clean_texts: list[str | None] = []
reasons: list[str] = []
for value in tqdm(sample["raw_text"].tolist(), desc="Persian preprocessing"):
    cleaned, reason = preprocess_text_with_reason(value)
    clean_texts.append(cleaned)
    reasons.append(reason)
sample["clean_text"] = clean_texts
sample["preprocessing_status"] = reasons
preprocessing_reason_counts = Counter(reasons)
valid_sample = sample[sample["clean_text"].notna()].copy()
valid_sample["token_count"] = valid_sample["clean_text"].str.split().str.len().astype(np.int32)

required_split_documents = TRAIN_SIZE + TOPIC_VALIDATION_SIZE + LINK_TEST_SIZE
if len(valid_sample) < required_split_documents:
    raise RuntimeError(
        f"Only {len(valid_sample):,} documents survived preprocessing; need at least {required_split_documents:,}."
    )

clean_strata_codes, clean_strata_edges = pd.qcut(
    valid_sample["token_count"],
    q=6,
    labels=False,
    retbins=True,
    duplicates="drop",
)
valid_sample["length_stratum"] = clean_strata_codes.map(lambda value: f"Q{int(value) + 1}")

selected_for_split, unused = train_test_split(
    valid_sample,
    train_size=required_split_documents,
    random_state=RANDOM_SEED,
    stratify=valid_sample["length_stratum"],
)
train, heldout = train_test_split(
    selected_for_split,
    train_size=TRAIN_SIZE,
    test_size=TOPIC_VALIDATION_SIZE + LINK_TEST_SIZE,
    random_state=RANDOM_SEED + 1,
    stratify=selected_for_split["length_stratum"],
)
topic_validation, test = train_test_split(
    heldout,
    train_size=TOPIC_VALIDATION_SIZE,
    test_size=LINK_TEST_SIZE,
    random_state=RANDOM_SEED + 2,
    stratify=heldout["length_stratum"],
)
train = train.sort_values("doc_id").reset_index(drop=True)
topic_validation = topic_validation.sort_values("doc_id").reset_index(drop=True)
test = test.sort_values("doc_id").reset_index(drop=True)

train_ids = set(train["doc_id"].astype(int))
validation_ids = set(topic_validation["doc_id"].astype(int))
link_test_ids = set(test["doc_id"].astype(int))
split_overlaps = {
    "train_validation": len(train_ids & validation_ids),
    "train_link_test": len(train_ids & link_test_ids),
    "validation_link_test": len(validation_ids & link_test_ids),
}
if any(split_overlaps.values()):
    raise AssertionError(f"Document overlap detected across analysis roles: {split_overlaps}")

null_audit_rows = [
    {"stage": "raw_dataset", "metric": "rows", "value": raw_row_count},
    {"stage": "raw_dataset", "metric": "text_null", "value": raw_text_null},
    {"stage": "raw_dataset", "metric": "text_empty_non_null", "value": raw_text_empty},
    {"stage": "raw_dataset", "metric": "text_non_string_non_null", "value": raw_text_non_string},
    {"stage": "raw_dataset", "metric": "title_null", "value": raw_title_null if TITLE_COLUMN else None},
]
null_audit_rows.extend(
    {"stage": "raw_column_nulls", "metric": f"null__{column}", "value": count}
    for column, count in sorted(raw_column_nulls.items())
)
null_audit_rows.extend([
    {"stage": "eligibility", "metric": "eligible_rows_before_text_deduplication", "value": eligible_rows},
    {"stage": "eligibility", "metric": "duplicate_eligible_texts_by_hash64", "value": duplicate_eligible_texts},
    {"stage": "eligibility", "metric": "unique_eligible_rows", "value": len(unique_candidate_meta)},
    {"stage": "working_sample", "metric": "sampled_rows", "value": len(sample)},
    {"stage": "working_sample", "metric": "raw_text_null", "value": int(sample["raw_text"].isna().sum())},
    {"stage": "working_sample", "metric": "title_null", "value": int(sample["title"].isna().sum())},
    {"stage": "working_sample", "metric": "clean_text_null_before_filter", "value": int(sample["clean_text"].isna().sum())},
    {"stage": "post_preprocessing", "metric": "valid_rows", "value": len(valid_sample)},
    {"stage": "post_preprocessing", "metric": "clean_text_null", "value": int(valid_sample["clean_text"].isna().sum())},
    {"stage": "post_preprocessing", "metric": "token_count_null", "value": int(valid_sample["token_count"].isna().sum())},
    {"stage": "split", "metric": "train_rows", "value": len(train)},
    {"stage": "split", "metric": "topic_validation_rows", "value": len(topic_validation)},
    {"stage": "split", "metric": "link_test_rows", "value": len(test)},
    {"stage": "split", "metric": "unused_valid_rows", "value": len(unused)},
    {"stage": "split", "metric": "train_validation_overlap", "value": split_overlaps["train_validation"]},
    {"stage": "split", "metric": "train_link_test_overlap", "value": split_overlaps["train_link_test"]},
    {"stage": "split", "metric": "validation_link_test_overlap", "value": split_overlaps["validation_link_test"]},
])
null_audit = pd.DataFrame(null_audit_rows)

split_table = pd.DataFrame({
    "stratum": sorted(valid_sample["length_stratum"].astype(str).unique()),
})
for name, frame in (("valid_sample", valid_sample), ("train", train), ("topic_validation", topic_validation), ("link_test", test)):
    counts = frame["length_stratum"].astype(str).value_counts()
    split_table[name] = split_table["stratum"].map(counts).fillna(0).astype(int)

train_doc_ids = set(train["doc_id"].astype(int))
topic_validation_doc_ids = set(topic_validation["doc_id"].astype(int))
test_doc_ids = set(test["doc_id"].astype(int))
unused_doc_ids = set(unused["doc_id"].astype(int))
sample_provenance = sample[[
    "doc_id", "source_row", "title", "text_hash64_hex", "raw_chars", "persian_chars",
    "persian_ratio", "raw_length_stratum", "preprocessing_status"
]].copy()
sample_provenance["token_count"] = sample["clean_text"].str.split().str.len()
sample_provenance["length_stratum"] = sample["doc_id"].map(
    valid_sample.set_index("doc_id")["length_stratum"].astype(str)
)
sample_provenance["split"] = sample_provenance["doc_id"].map(
    lambda doc_id: (
        "train" if int(doc_id) in train_doc_ids else
        "topic_validation" if int(doc_id) in topic_validation_doc_ids else
        "link_test" if int(doc_id) in test_doc_ids else
        "unused_valid" if int(doc_id) in unused_doc_ids else
        "excluded_after_preprocessing"
    )
)
sample_provenance = sample_provenance.sort_values("source_row").reset_index(drop=True)

print("\nNull and provenance audit")
display(null_audit)
print("\nDuplicate-group distribution")
display(duplicate_group_distribution)
print("\nLargest exact-text hash groups")
display(top_duplicate_groups.head(20))
print("\nPreprocessing outcomes")
display(pd.DataFrame(sorted(preprocessing_reason_counts.items()), columns=["status", "documents"]))
print("\nLength-stratified split")
display(split_table)
print("\nToken-length summary")
display(valid_sample["token_count"].describe(percentiles=[0.1, 0.25, 0.5, 0.75, 0.9, 0.95, 0.99]).to_frame("token_count"))

# =============================================================================
# 5. COMMON TOPIC-MODEL EVALUATION
# =============================================================================

heading("2. Topic-model benchmark")
train_clean = train["clean_text"].astype(str).tolist()
topic_validation_clean = topic_validation["clean_text"].astype(str).tolist()
train_raw_context = [normalize_base_text(text, use_hazm=True) for text in train["raw_text"].astype(str)]
topic_validation_raw_context = [
    normalize_base_text(text, use_hazm=True) for text in topic_validation["raw_text"].astype(str)
]
train_tokens = [text.split() for text in train_clean]
topic_validation_tokens = [text.split() for text in topic_validation_clean]

# Shared training-derived vocabulary. All four core families use these exact
# lexical terms; contextual encoders remain model-specific by design.
shared_count_vectorizer = CountVectorizer(
    tokenizer=str.split,
    preprocessor=None,
    token_pattern=None,
    lowercase=False,
    min_df=SHARED_VOCAB_MIN_DF,
    max_df=SHARED_VOCAB_MAX_DF,
    max_features=SHARED_VOCAB_SIZE,
    ngram_range=(1, 1),
)
shared_count_matrix = shared_count_vectorizer.fit_transform(train_clean)
shared_terms = np.asarray(shared_count_vectorizer.get_feature_names_out())
shared_vocabulary = {term: int(index) for index, term in enumerate(shared_terms)}
if not (100 <= len(shared_vocabulary) <= SHARED_VOCAB_SIZE):
    raise RuntimeError(f"Invalid shared vocabulary size: {len(shared_vocabulary)}")

term_document_frequency = np.asarray((shared_count_matrix > 0).sum(axis=0)).ravel().astype(int)
term_corpus_frequency = np.asarray(shared_count_matrix.sum(axis=0)).ravel().astype(int)
shared_vocabulary_table = pd.DataFrame({
    "term": shared_terms,
    "vocabulary_index": np.arange(len(shared_terms), dtype=int),
    "document_frequency": term_document_frequency,
    "corpus_frequency": term_corpus_frequency,
}).sort_values(["corpus_frequency", "term"], ascending=[False, True]).reset_index(drop=True)

# Preserve Gensim's real document/corpus counts while restricting LDA to the
# same terms used by NMF, CTM, and BERTopic.
train_dictionary = Dictionary(train_tokens)
bad_ids = [token_id for token, token_id in train_dictionary.token2id.items() if token not in shared_vocabulary]
train_dictionary.filter_tokens(bad_ids=bad_ids)
train_dictionary.compactify()
if set(train_dictionary.token2id) != set(shared_vocabulary):
    missing = set(shared_vocabulary) - set(train_dictionary.token2id)
    extra = set(train_dictionary.token2id) - set(shared_vocabulary)
    raise RuntimeError(f"Shared vocabulary mismatch: missing={len(missing)}, extra={len(extra)}")
train_corpus = [train_dictionary.doc2bow(tokens) for tokens in train_tokens]

# The complete topic-validation split is the sole reference for C_v/NPMI and
# CTM held-out topic distributions. Link-test documents are untouched here.
reference_texts = topic_validation_tokens[:COHERENCE_REFERENCE_DOCS]
reference_dictionary = Dictionary(reference_texts)
reference_bad_ids = [
    token_id for token, token_id in reference_dictionary.token2id.items() if token not in shared_vocabulary
]
reference_dictionary.filter_tokens(bad_ids=reference_bad_ids)
reference_dictionary.compactify()
if len(reference_dictionary) == 0:
    raise RuntimeError("Topic-validation reference vocabulary is empty after shared-vocabulary restriction.")

print(f"Shared training vocabulary: {len(shared_vocabulary):,}")
print(f"Held-out topic-validation documents: {len(reference_texts):,}")
print(f"Held-out reference vocabulary represented: {len(reference_dictionary):,}")
topic_data_summary = pd.DataFrame([
    {
        "training_documents": len(train),
        "topic_validation_documents": len(topic_validation),
        "link_test_documents_reserved": len(test),
        "shared_vocabulary_size": len(shared_vocabulary),
        "shared_vocabulary_min_df": SHARED_VOCAB_MIN_DF,
        "shared_vocabulary_max_df": SHARED_VOCAB_MAX_DF,
        "coherence_reference_documents": len(reference_texts),
        "coherence_reference_vocabulary": len(reference_dictionary),
        "top_n_words": TOP_N_WORDS,
        "candidate_words": TOPIC_CANDIDATE_WORDS,
    }
])
display(topic_data_summary)
print("\nMost frequent terms in the shared training vocabulary")
display(shared_vocabulary_table.head(30))
del shared_count_matrix
gc.collect()


def canonicalize_topic_lists(raw_topics: Sequence[Sequence[str]]) -> list[list[str]]:
    canonical_topics: list[list[str]] = []
    for topic in raw_topics:
        words: list[str] = []
        seen: set[str] = set()
        for raw_word in list(topic)[:TOPIC_CANDIDATE_WORDS]:
            word = canonical_topic_term(raw_word)
            if not word or word in seen:
                continue
            seen.add(word)
            words.append(word)
            if len(words) == TOP_N_WORDS:
                break
        if words:
            canonical_topics.append(words)
    return canonical_topics


def evaluate_topics_against_reference(
    raw_topics: Sequence[Sequence[str]],
    evaluation_texts: Sequence[Sequence[str]],
    evaluation_dictionary: Dictionary,
) -> tuple[dict[str, float], list[list[str]]]:
    """Evaluate topic lists consistently while separating lexical and corpus metrics.

    Diversity, distinctness, and stability use canonical top-word lists directly.
    C_v and NPMI use only words available in the held-out reference dictionary.
    """
    canonical_topics = canonicalize_topic_lists(raw_topics)
    matched_topics: list[list[str]] = []
    matched_word_counts: list[int] = []
    for topic in canonical_topics:
        matched = [word for word in topic if word in evaluation_dictionary.token2id][:TOP_N_WORDS]
        matched_word_counts.append(len(matched))
        if len(matched) >= 3:
            matched_topics.append(matched)

    valid_fraction = len(matched_topics) / len(canonical_topics) if canonical_topics else float("nan")
    matched_terms = sum(matched_word_counts)
    possible_terms = TOP_N_WORDS * len(canonical_topics)
    diagnostics = {
        "raw_topic_count": len(raw_topics),
        "canonical_topic_count": len(canonical_topics),
        "valid_topic_count": len(matched_topics),
        "valid_topic_fraction": valid_fraction,
        "mean_matched_words_per_topic": float(np.mean(matched_word_counts)) if matched_word_counts else float("nan"),
        "reference_match_rate": matched_terms / possible_terms if possible_terms else float("nan"),
    }

    if len(matched_topics) < 2:
        return {
            "c_v": float("nan"),
            "c_npmi": float("nan"),
            "topic_coherence_sd": float("nan"),
            "diversity": topic_diversity(canonical_topics),
            "distinctness": topic_distinctness(canonical_topics),
            **diagnostics,
        }, canonical_topics

    cv_model = CoherenceModel(
        topics=matched_topics,
        texts=evaluation_texts,
        dictionary=evaluation_dictionary,
        coherence="c_v",
        topn=TOP_N_WORDS,
        processes=1,
    )
    cv_per_topic = np.asarray(cv_model.get_coherence_per_topic(), dtype=float)
    npmi = CoherenceModel(
        topics=matched_topics,
        texts=evaluation_texts,
        dictionary=evaluation_dictionary,
        coherence="c_npmi",
        topn=TOP_N_WORDS,
        processes=1,
    ).get_coherence()
    return {
        "c_v": float(np.nanmean(cv_per_topic)),
        "c_npmi": float(npmi),
        "topic_coherence_sd": float(np.nanstd(cv_per_topic, ddof=1)) if len(cv_per_topic) > 1 else 0.0,
        "diversity": topic_diversity(canonical_topics),
        "distinctness": topic_distinctness(canonical_topics),
        **diagnostics,
    }, canonical_topics


def topic_diversity(topics: Sequence[Sequence[str]]) -> float:
    words = [word for topic in topics for word in list(topic)[:TOP_N_WORDS]]
    return len(set(words)) / len(words) if words else float("nan")


def topic_distinctness(topics: Sequence[Sequence[str]]) -> float:
    sets = [set(topic[:TOP_N_WORDS]) for topic in topics if topic]
    if len(sets) < 2:
        return float("nan")
    similarities = []
    for left, right in combinations(sets, 2):
        union = left | right
        similarities.append(len(left & right) / len(union) if union else 0.0)
    return 1.0 - float(np.mean(similarities))


def evaluate_topics_common(raw_topics: Sequence[Sequence[str]]) -> tuple[dict[str, float], list[list[str]]]:
    return evaluate_topics_against_reference(raw_topics, reference_texts, reference_dictionary)


def topic_alignment_stability(seed_topics: Sequence[Sequence[Sequence[str]]]) -> float:
    if len(seed_topics) < 2:
        return float("nan")
    pair_scores: list[float] = []
    for topics_a, topics_b in combinations(seed_topics, 2):
        sets_a = [set(topic[:TOP_N_WORDS]) for topic in topics_a if topic]
        sets_b = [set(topic[:TOP_N_WORDS]) for topic in topics_b if topic]
        if not sets_a or not sets_b:
            continue
        similarity = np.zeros((len(sets_a), len(sets_b)), dtype=float)
        for i, left in enumerate(sets_a):
            for j, right in enumerate(sets_b):
                union = left | right
                similarity[i, j] = len(left & right) / len(union) if union else 0.0
        rows, cols = linear_sum_assignment(-similarity)
        pair_scores.append(float(similarity[rows, cols].mean()))
    return float(np.mean(pair_scores)) if pair_scores else float("nan")


def run_record(
    model: str,
    k: int,
    seed: int,
    metrics: dict[str, float],
    seconds: float,
    docs: int,
    *,
    model_family: str | None = None,
    benchmark_role: str = "core",
    encoder: str | None = None,
    **extra: Any,
) -> dict[str, Any]:
    return {
        "model": model,
        "model_family": model_family or model,
        "benchmark_role": benchmark_role,
        "encoder": encoder,
        "k": int(k),
        "seed": int(seed),
        **metrics,
        "training_seconds": float(seconds),
        "training_documents": int(docs),
        **extra,
    }


all_run_rows: list[dict[str, Any]] = []
variant_topics: dict[str, dict[tuple[int, int], list[list[str]]]] = {
    "LDA": {},
    "NMF": {},
    "CTM": {},
    "BERTopic": {},
    "BERTopic-ParsBERT": {},
}
selected_lda_models: dict[int, LdaModel] = {}

# ----- LDA -----
for seed in SEEDS:
    for k in tqdm(TOPIC_COUNTS, desc=f"LDA seed={seed}"):
        set_seed(seed)
        started = time.time()
        model = LdaModel(
            corpus=train_corpus,
            id2word=train_dictionary,
            num_topics=k,
            random_state=seed,
            passes=LDA_PASSES,
            iterations=LDA_ITERATIONS,
            alpha=LDA_ALPHA,
            eta=LDA_ETA,
            minimum_probability=0.0,
            eval_every=None,
        )
        raw_topics = [
            [word for word, _weight in model.show_topic(topic_id, topn=TOPIC_CANDIDATE_WORDS)]
            for topic_id in range(k)
        ]
        metrics, canonical_topics = evaluate_topics_common(raw_topics)
        all_run_rows.append(run_record(
            "LDA", k, seed, metrics, time.time() - started, len(train),
            model_family="LDA", benchmark_role="core",
            shared_vocabulary_size=len(shared_vocabulary),
        ))
        variant_topics["LDA"][(k, seed)] = canonical_topics
        if seed == GRAPH_TOPIC_SEED and k in GRAPH_TOPIC_K_SENSITIVITY:
            selected_lda_models[k] = model
        else:
            del model

# ----- NMF -----
tfidf_vectorizer = TfidfVectorizer(
    tokenizer=str.split,
    preprocessor=None,
    token_pattern=None,
    lowercase=False,
    vocabulary=shared_vocabulary,
    sublinear_tf=True,
)
tfidf_matrix = tfidf_vectorizer.fit_transform(train_clean)
nmf_features = np.asarray(tfidf_vectorizer.get_feature_names_out())
for seed in SEEDS:
    for k in tqdm(TOPIC_COUNTS, desc=f"NMF seed={seed}"):
        set_seed(seed)
        started = time.time()
        model = NMF(
            n_components=k,
            init=NMF_INIT,
            solver="mu",
            beta_loss="frobenius",
            max_iter=NMF_MAX_ITER,
            tol=NMF_TOL,
            alpha_W=NMF_ALPHA_W,
            alpha_H=NMF_ALPHA_H,
            l1_ratio=NMF_L1_RATIO,
            random_state=seed,
        )
        model.fit(tfidf_matrix)
        raw_topics = [
            nmf_features[np.argsort(component)[::-1][:TOPIC_CANDIDATE_WORDS]].tolist()
            for component in model.components_
        ]
        metrics, canonical_topics = evaluate_topics_common(raw_topics)
        all_run_rows.append(run_record(
            "NMF", k, seed, metrics, time.time() - started, len(train),
            model_family="NMF", benchmark_role="core",
            converged=bool(model.n_iter_ < NMF_MAX_ITER), n_iter=int(model.n_iter_),
            shared_vocabulary_size=len(shared_vocabulary),
        ))
        variant_topics["NMF"][(k, seed)] = canonical_topics
        del model

del tfidf_matrix
gc.collect()


def encode_contextual_documents(
    documents: Sequence[str],
    model_name: str,
    max_seq_length: int,
    batch_size: int,
    description: str,
) -> np.ndarray:
    log(f"Encoding {len(documents):,} documents with {description}: {model_name}")
    encoder = build_sentence_encoder(
        model_name, max_seq_length=max_seq_length, device=DEVICE, revision=MODEL_REVISIONS[model_name]
    )
    embeddings = encoder.encode(
        list(documents),
        batch_size=batch_size,
        show_progress_bar=True,
        convert_to_numpy=True,
        normalize_embeddings=False,
    ).astype(np.float32, copy=False)
    del encoder
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()
    if embeddings.shape[0] != len(documents) or not np.isfinite(embeddings).all():
        raise RuntimeError(f"Invalid embeddings from {model_name}: shape={embeddings.shape}")
    return embeddings


def run_bertopic_variant(
    *,
    model_label: str,
    encoder_label: str,
    encoder_model_id: str,
    embeddings: np.ndarray,
    benchmark_role: str,
) -> None:
    """Embedding -> UMAP -> KMeans labels -> official BERTopic c-TF-IDF.

    BERTopic's documented manual-topic interface is used: BaseEmbedder,
    BaseDimensionalityReduction and BaseCluster skip internal embedding/reduction/
    clustering, while externally generated KMeans labels are passed through ``y``.
    Persian lexical input is already whitespace-tokenized; therefore the vectorizer
    uses ``str.split`` and topic-document thresholds min_df=1/max_df=1.0.
    """
    for seed in SEEDS:
        set_seed(seed)
        umap_model = UMAP(
            n_neighbors=BERTOPIC_UMAP_NEIGHBORS,
            n_components=BERTOPIC_UMAP_COMPONENTS,
            min_dist=BERTOPIC_UMAP_MIN_DIST,
            metric="cosine",
            random_state=seed,
            low_memory=True,
        )
        reduced_embeddings = umap_model.fit_transform(embeddings)
        if reduced_embeddings.shape != (len(train_clean), BERTOPIC_UMAP_COMPONENTS):
            raise RuntimeError(f"Unexpected UMAP shape for {model_label}: {reduced_embeddings.shape}")
        if not np.isfinite(reduced_embeddings).all():
            raise RuntimeError(f"UMAP produced non-finite values for {model_label}, seed={seed}")

        for k in tqdm(TOPIC_COUNTS, desc=f"{model_label} seed={seed}"):
            started = time.time()
            cluster_model = KMeans(
                n_clusters=k,
                random_state=seed,
                n_init=BERTOPIC_KMEANS_N_INIT,
                max_iter=BERTOPIC_KMEANS_MAX_ITER,
                algorithm="lloyd",
            )
            labels = cluster_model.fit_predict(reduced_embeddings).astype(int)
            unique_labels, label_counts = np.unique(labels, return_counts=True)
            if len(unique_labels) != k or set(unique_labels.tolist()) != set(range(k)):
                raise RuntimeError(
                    f"{model_label} KMeans returned {len(unique_labels)} non-empty clusters for K={k}; "
                    f"labels={unique_labels[:20].tolist()}"
                )

            # Diagnose the exact topic-level corpus before BERTopic sees it.
            grouped = (
                pd.DataFrame({"Document": train_clean, "Topic": labels})
                .groupby("Topic", as_index=False, sort=True)["Document"]
                .agg(" ".join)
            )
            if len(grouped) != k or grouped["Document"].str.strip().eq("").any():
                raise RuntimeError(f"Invalid grouped topic corpus for {model_label}, K={k}, seed={seed}")

            vectorizer_model = CountVectorizer(
                tokenizer=str.split,
                preprocessor=None,
                token_pattern=None,
                lowercase=False,
                vocabulary=shared_vocabulary,
                ngram_range=(1, 1),
            )
            diagnostic_matrix = vectorizer_model.fit_transform(grouped["Document"])
            empty_group_rows = int((diagnostic_matrix.getnnz(axis=1) == 0).sum())
            diagnostic_vocabulary = int(diagnostic_matrix.shape[1])
            if diagnostic_vocabulary == 0 or empty_group_rows:
                raise RuntimeError(
                    f"Topic-level Persian vectorization failed before BERTopic: model={model_label}, "
                    f"K={k}, seed={seed}, vocabulary={diagnostic_vocabulary}, empty_rows={empty_group_rows}"
                )

            # Recreate the vectorizer so BERTopic fits a fresh, auditable vocabulary.
            vectorizer_model = CountVectorizer(
                tokenizer=str.split,
                preprocessor=None,
                token_pattern=None,
                lowercase=False,
                vocabulary=shared_vocabulary,
                ngram_range=(1, 1),
            )
            topic_model = BERTopic(
                embedding_model=BaseEmbedder(),
                umap_model=BaseDimensionalityReduction(),
                hdbscan_model=BaseCluster(),
                vectorizer_model=vectorizer_model,
                ctfidf_model=ClassTfidfTransformer(reduce_frequent_words=True),
                top_n_words=TOPIC_CANDIDATE_WORDS,
                calculate_probabilities=False,
                low_memory=True,
                verbose=False,
            )
            assigned_topics, _ = topic_model.fit_transform(train_clean, y=labels)
            if len(assigned_topics) != len(train_clean):
                raise RuntimeError("BERTopic did not return one assigned topic per document.")
            if topic_model.c_tf_idf_ is None or topic_model.c_tf_idf_.shape[0] != k:
                raise RuntimeError(
                    f"Invalid official c-TF-IDF matrix for {model_label}, K={k}: "
                    f"{None if topic_model.c_tf_idf_ is None else topic_model.c_tf_idf_.shape}"
                )

            topic_ids = sorted(int(topic_id) for topic_id in topic_model.get_topics() if int(topic_id) >= 0)
            raw_topics: list[list[str]] = []
            for topic_id in topic_ids:
                representation = topic_model.get_topic(topic_id) or []
                raw_topics.append([
                    word for word, weight in representation[:TOPIC_CANDIDATE_WORDS]
                    if word and np.isfinite(weight)
                ])
            if len(raw_topics) != k:
                raise RuntimeError(f"{model_label} represented {len(raw_topics)} topics for requested K={k}.")

            metrics, canonical_topics = evaluate_topics_common(raw_topics)
            if metrics["valid_topic_fraction"] < 0.95 or not np.isfinite(
                [metrics["c_v"], metrics["c_npmi"], metrics["diversity"], metrics["distinctness"]]
            ).all():
                raise RuntimeError(
                    f"{model_label} evaluation failed for K={k}, seed={seed}: {metrics}; "
                    f"sample_topic={raw_topics[0][:10] if raw_topics else []}"
                )

            all_run_rows.append(run_record(
                model_label,
                k,
                seed,
                metrics,
                time.time() - started,
                len(train),
                model_family="BERTopic",
                benchmark_role=benchmark_role,
                encoder=encoder_label,
                encoder_model_id=encoder_model_id,
                actual_topics=len(raw_topics),
                minimum_cluster_size=int(label_counts.min()),
                maximum_cluster_size=int(label_counts.max()),
                topic_level_vocabulary=diagnostic_vocabulary,
                empty_topic_documents_before_fit=empty_group_rows,
                c_tfidf_used=True,
                ctfidf_implementation="BERTopic ClassTfidfTransformer (official manual-label workflow)",
                cluster_labels="external UMAP+KMeans labels passed via y",
                lexical_input="clean Persian whitespace-tokenized unigrams",
                contextual_input="normalized raw Persian text",
                shared_vocabulary_size=len(shared_vocabulary),
            ))
            variant_topics[model_label][(k, seed)] = canonical_topics
            del topic_model, cluster_model, diagnostic_matrix, grouped
            gc.collect()
            if torch.cuda.is_available():
                torch.cuda.empty_cache()

        del reduced_embeddings, umap_model
        gc.collect()
        if torch.cuda.is_available():
            torch.cuda.empty_cache()


# ----- multilingual contextual embeddings: core BERTopic + full-data CTM -----
multilingual_train_embeddings = encode_contextual_documents(
    train_raw_context,
    MULTILINGUAL_ENCODER_MODEL,
    MULTILINGUAL_MAX_SEQ_LENGTH,
    EMBEDDING_BATCH_SIZE,
    "multilingual core encoder (train)",
)
multilingual_validation_embeddings = encode_contextual_documents(
    topic_validation_raw_context,
    MULTILINGUAL_ENCODER_MODEL,
    MULTILINGUAL_MAX_SEQ_LENGTH,
    EMBEDDING_BATCH_SIZE,
    "multilingual core encoder (topic validation)",
)
run_bertopic_variant(
    model_label="BERTopic",
    encoder_label="multilingual-MiniLM",
    encoder_model_id=MULTILINGUAL_ENCODER_MODEL,
    embeddings=multilingual_train_embeddings,
    benchmark_role="core",
)

# ----- CTM: official CombinedTM training loop -----
ctm_train = train.iloc[:CTM_TRAIN_DOCS].reset_index(drop=True)
ctm_test = topic_validation.iloc[:CTM_TEST_DOCS].reset_index(drop=True)
if len(ctm_train) != CTM_TRAIN_DOCS or len(ctm_test) != CTM_TEST_DOCS:
    raise RuntimeError(f"CTM requires exactly {CTM_TRAIN_DOCS:,} training and {CTM_TEST_DOCS:,} topic-validation documents in this protocol.")

ctm_vectorizer = CountVectorizer(
    tokenizer=str.split,
    preprocessor=None,
    token_pattern=None,
    lowercase=False,
    vocabulary=shared_vocabulary,
)
ctm_train_bow = ctm_vectorizer.fit_transform(ctm_train["clean_text"].astype(str))
ctm_test_bow = ctm_vectorizer.transform(ctm_test["clean_text"].astype(str))
ctm_vocab = ctm_vectorizer.get_feature_names_out()
ctm_id2token = {index: token for index, token in enumerate(ctm_vocab)}
ctm_training_dataset = CTMDataset(
    X_contextual=multilingual_train_embeddings[:CTM_TRAIN_DOCS],
    X_bow=ctm_train_bow,
    idx2token=ctm_id2token,
)
ctm_testing_dataset = CTMDataset(
    X_contextual=multilingual_validation_embeddings[:CTM_TEST_DOCS],
    X_bow=ctm_test_bow,
    idx2token=ctm_id2token,
)
ctm_bow_size = len(ctm_vocab)
ctm_contextual_size = int(multilingual_train_embeddings.shape[1])
if ctm_bow_size == 0 or ctm_bow_size > CTM_MAX_FEATURES:
    raise RuntimeError(f"Invalid CTM vocabulary size: {ctm_bow_size}")

for seed in SEEDS:
    for k in tqdm(TOPIC_COUNTS, desc=f"CTM seed={seed}"):
        set_seed(seed)
        started = time.time()
        kwargs = dict(
            bow_size=ctm_bow_size,
            contextual_size=ctm_contextual_size,
            n_components=k,
            num_epochs=CTM_EPOCHS,
            batch_size=CTM_BATCH_SIZE,
            num_data_loader_workers=0,
            learn_priors=True,
        )
        if "lr" in inspect.signature(CombinedTM).parameters:
            kwargs["lr"] = CTM_LEARNING_RATE
        model = CombinedTM(**kwargs)
        model.fit(ctm_training_dataset, verbose=False, do_train_predictions=False)
        raw_topics = model.get_topic_lists(TOPIC_CANDIDATE_WORDS)
        metrics, canonical_topics = evaluate_topics_common(raw_topics)
        if metrics["valid_topic_fraction"] < 0.95 or not np.isfinite(
            [metrics["c_v"], metrics["c_npmi"], metrics["diversity"], metrics["distinctness"]]
        ).all():
            raise RuntimeError(f"CTM produced invalid topic evidence for K={k}, seed={seed}: {metrics}")
        distribution = model.get_doc_topic_distribution(
            ctm_testing_dataset,
            n_samples=CTM_TEST_TOPIC_SAMPLES,
        )
        inferred_shape = list(distribution.shape)
        if inferred_shape != [CTM_TEST_DOCS, k] or not np.isfinite(distribution).all():
            raise RuntimeError(f"Invalid CTM topic-validation distribution for K={k}: shape={inferred_shape}")
        all_run_rows.append(run_record(
            "CTM",
            k,
            seed,
            metrics,
            time.time() - started,
            len(ctm_train),
            model_family="CTM",
            benchmark_role="core",
            encoder="multilingual-MiniLM",
            encoder_model_id=MULTILINGUAL_ENCODER_MODEL,
            topic_validation_documents_reserved=len(ctm_test),
            topic_validation_topic_distribution_shape=inferred_shape,
            epochs=CTM_EPOCHS,
            batch_size=CTM_BATCH_SIZE,
            controlled_bow_vocabulary=ctm_bow_size,
            shared_vocabulary_size=len(shared_vocabulary),
            training_implementation="official CombinedTM.fit",
        ))
        variant_topics["CTM"][(k, seed)] = canonical_topics
        del model, distribution
        gc.collect()
        if torch.cuda.is_available():
            torch.cuda.empty_cache()

# Multilingual embeddings are no longer needed after core BERTopic and CTM.
del multilingual_train_embeddings, multilingual_validation_embeddings, ctm_train_bow, ctm_test_bow
gc.collect()
if torch.cuda.is_available():
    torch.cuda.empty_cache()

# ----- ParsBERT BERTopic encoder sensitivity -----
# FIXED: ParsBERT encoding now works with the updated build_sentence_encoder function
parsbert_train_embeddings = encode_contextual_documents(
    train_raw_context,
    PARSBERT_ENCODER_MODEL,
    PARSBERT_MAX_SEQ_LENGTH,
    PARSBERT_BATCH_SIZE,
    "ParsBERT mean-pooled encoder sensitivity",
)
run_bertopic_variant(
    model_label="BERTopic-ParsBERT",
    encoder_label="ParsBERT-mean-pooling",
    encoder_model_id=PARSBERT_ENCODER_MODEL,
    embeddings=parsbert_train_embeddings,
    benchmark_role="encoder_sensitivity",
)
del parsbert_train_embeddings
gc.collect()
if torch.cuda.is_available():
    torch.cuda.empty_cache()

# ----- run validation and aggregation -----
all_runs = pd.DataFrame(all_run_rows).sort_values(["benchmark_role", "model", "k", "seed"]).reset_index(drop=True)
core_runs = all_runs[all_runs["benchmark_role"] == "core"].copy()
bertopic_encoder_runs = all_runs[all_runs["model_family"] == "BERTopic"].copy()

expected_core_runs = 4 * len(TOPIC_COUNTS) * len(SEEDS)
expected_parsbert_extra_runs = len(TOPIC_COUNTS) * len(SEEDS)
expected_total_runs = expected_core_runs + expected_parsbert_extra_runs
if len(core_runs) != expected_core_runs:
    raise AssertionError(f"Expected {expected_core_runs} core topic runs, obtained {len(core_runs)}.")
if len(all_runs) != expected_total_runs:
    raise AssertionError(f"Expected {expected_total_runs} total topic runs, obtained {len(all_runs)}.")

core_metric_columns = ["c_v", "c_npmi", "diversity", "distinctness"]
if not np.isfinite(all_runs[core_metric_columns].to_numpy(dtype=float)).all():
    bad = all_runs.loc[~np.isfinite(all_runs[core_metric_columns].to_numpy(dtype=float)).all(axis=1)]
    raise RuntimeError(f"Non-finite topic metrics detected:\n{bad}")

aggregate_rows: list[dict[str, Any]] = []
for (model, k), group in all_runs.groupby(["model", "k"], sort=True):
    row: dict[str, Any] = {
        "model": model,
        "model_family": group["model_family"].iloc[0],
        "benchmark_role": group["benchmark_role"].iloc[0],
        "encoder": group["encoder"].iloc[0],
        "k": int(k),
        "seeds": len(group),
        "valid_topic_fraction_mean": group["valid_topic_fraction"].mean(),
        "reference_match_rate_mean": group["reference_match_rate"].mean(),
        "training_seconds_mean": group["training_seconds"].mean(),
        "training_seconds_sd": group["training_seconds"].std(ddof=1),
    }
    for metric_index, metric in enumerate(core_metric_columns):
        ci_low, ci_high = bootstrap_mean_ci(
            group[metric],
            seed=RANDOM_SEED + 1000 * metric_index + int(k) + len(aggregate_rows),
        )
        row[f"{metric}_mean"] = group[metric].mean()
        row[f"{metric}_sd"] = group[metric].std(ddof=1)
        row[f"{metric}_bootstrap_ci_low"] = ci_low
        row[f"{metric}_bootstrap_ci_high"] = ci_high
    aggregate_rows.append(row)
aggregate = pd.DataFrame(aggregate_rows)

stability_rows: list[dict[str, Any]] = []
for model_name, model_topics in variant_topics.items():
    for k in TOPIC_COUNTS:
        seed_topics = [model_topics[(k, seed)] for seed in SEEDS]
        stability_rows.append({
            "model": model_name,
            "k": k,
            "stability": topic_alignment_stability(seed_topics),
        })
aggregate = aggregate.merge(pd.DataFrame(stability_rows), on=["model", "k"], how="left")
core_aggregate = aggregate[aggregate["benchmark_role"] == "core"].copy()
bertopic_encoder_aggregate = aggregate[aggregate["model_family"] == "BERTopic"].copy()

# Primary comparison at one common topic count prevents model-specific K selection
# from being confused with a matched model comparison.
common_k_results = (
    core_aggregate[core_aggregate["k"] == PRIMARY_COMMON_K]
    .sort_values("c_v_mean", ascending=False)
    .reset_index(drop=True)
)
if set(common_k_results["model"]) != {"LDA", "NMF", "CTM", "BERTopic"}:
    raise RuntimeError(f"Incomplete common-K comparison at K={PRIMARY_COMMON_K}")

metric_optima_rows: list[dict[str, Any]] = []
for model_name, group in aggregate.groupby("model", sort=True):
    for metric in ("c_v_mean", "c_npmi_mean", "diversity_mean", "distinctness_mean", "stability"):
        best_row = group.sort_values([metric, "k"], ascending=[False, True]).iloc[0]
        metric_optima_rows.append({
            "model": model_name,
            "benchmark_role": best_row["benchmark_role"],
            "encoder": best_row["encoder"],
            "metric": metric,
            "k": int(best_row["k"]),
            "value": float(best_row[metric]),
        })
metric_optima = pd.DataFrame(metric_optima_rows)


def pareto_mask(frame: pd.DataFrame, columns: Sequence[str]) -> np.ndarray:
    values = frame[list(columns)].to_numpy(dtype=float)
    efficient = np.ones(len(values), dtype=bool)
    for i, candidate in enumerate(values):
        if not efficient[i]:
            continue
        dominates_candidate = np.all(values >= candidate, axis=1) & np.any(values > candidate, axis=1)
        dominates_candidate[i] = False
        if dominates_candidate.any():
            efficient[i] = False
    return efficient

pareto_columns = ["c_v_mean", "c_npmi_mean", "diversity_mean", "distinctness_mean", "stability"]
core_pareto_front = core_aggregate.loc[pareto_mask(core_aggregate, pareto_columns)].copy()
core_pareto_front = core_pareto_front.sort_values(["model", "k"]).reset_index(drop=True)

best_configs = (
    aggregate.sort_values(["model", "c_v_mean", "diversity_mean"], ascending=[True, False, False])
    .groupby("model", as_index=False)
    .head(1)
    .sort_values("c_v_mean", ascending=False)
    .reset_index(drop=True)
)
core_best_configs = best_configs[best_configs["benchmark_role"] == "core"].reset_index(drop=True)

representative_topic_rows: list[dict[str, Any]] = []
for row in best_configs.itertuples(index=False):
    topics = variant_topics[row.model][(int(row.k), RANDOM_SEED)]
    for topic_index, words in enumerate(topics[:min(20, len(topics))]):
        representative_topic_rows.append({
            "model": row.model,
            "encoder": row.encoder,
            "k": int(row.k),
            "seed": RANDOM_SEED,
            "topic_index": topic_index,
            "top_words": " | ".join(words[:TOP_N_WORDS]),
        })
representative_topics = pd.DataFrame(representative_topic_rows)

run_metadata_lookup = all_runs.set_index(["model", "k", "seed"])[
    ["model_family", "benchmark_role", "encoder"]
].to_dict(orient="index")
all_topic_word_rows: list[dict[str, Any]] = []
for model_name, run_topics in variant_topics.items():
    for (k, seed), topics in sorted(run_topics.items()):
        metadata = run_metadata_lookup[(model_name, int(k), int(seed))]
        for topic_index, words in enumerate(topics):
            all_topic_word_rows.append({
                "model": model_name,
                "model_family": metadata["model_family"],
                "benchmark_role": metadata["benchmark_role"],
                "encoder": metadata["encoder"],
                "k": int(k),
                "seed": int(seed),
                "topic_index": int(topic_index),
                "word_count": len(words),
                "top_words": " | ".join(words[:TOP_N_WORDS]),
            })
all_topic_words = pd.DataFrame(all_topic_word_rows).sort_values(
    ["benchmark_role", "model", "k", "seed", "topic_index"]
).reset_index(drop=True)


def make_topic_audit_template(topics_per_model: int = 10) -> pd.DataFrame:
    rows: list[dict[str, Any]] = []
    for model_name in ["LDA", "NMF", "CTM", "BERTopic", "BERTopic-ParsBERT"]:
        topics = variant_topics[model_name][(PRIMARY_COMMON_K, RANDOM_SEED)]
        chosen = np.linspace(0, len(topics) - 1, num=min(topics_per_model, len(topics)), dtype=int)
        for topic_index in sorted(set(chosen.tolist())):
            rows.append({
                "model": model_name,
                "k": PRIMARY_COMMON_K,
                "seed": RANDOM_SEED,
                "topic_index": int(topic_index),
                "top_words": " | ".join(topics[topic_index][:TOP_N_WORDS]),
                "proposed_label": "",
                "semantic_coherence_1_to_5": "",
                "intruder_word_if_any": "",
                "annotator": "",
                "notes": "",
            })
    return pd.DataFrame(rows)


topic_audit_template = make_topic_audit_template()

print(f"\nAll topic-model runs: {expected_core_runs} core runs + {expected_parsbert_extra_runs} ParsBERT sensitivity runs")
if SHOW_ALL_RUN_ROWS:
    display(all_runs)
print("\nCore four-model run-level results")
display(core_runs)
print("\nSeed-aggregated topic-model results with 5,000-resample bootstrap intervals")
display(aggregate)
print(f"\nPrimary matched comparison at common K={PRIMARY_COMMON_K}")
display(common_k_results)
print("\nMetric-specific optima (no composite quality score)")
display(metric_optima)
print("\nPareto-efficient core configurations across C_v, NPMI, diversity, distinctness, and stability")
display(core_pareto_front)
print("\nCoherence-maximizing configuration for each model/encoder variant")
display(best_configs)
print("\nRepresentative topics from each coherence-maximizing configuration")
display(representative_topics)
print(f"\nComplete topic-word evidence contains {len(all_topic_words):,} topic rows and is saved in the final JSON evidence.")
display(all_topic_words.head(200))
print("\nUnscored topic human-audit template (complete template saved in JSON)")
display(topic_audit_template)

# =============================================================================
# 6. METRIC-SPECIFIC CONFIGURATION-LEVEL STATISTICS
# =============================================================================

heading("3. Statistical testing")

topic_friedman_rows: list[dict[str, Any]] = []
topic_pairwise_rows: list[dict[str, Any]] = []
core_model_order = ["LDA", "NMF", "CTM", "BERTopic"]
run_level_metrics = ["c_v", "c_npmi", "diversity", "distinctness"]

statistical_core_runs = core_runs[core_runs["k"].isin(STATISTICAL_TOPIC_COUNTS)].copy()
statistical_encoder_runs = bertopic_encoder_runs[bertopic_encoder_runs["k"].isin(STATISTICAL_TOPIC_COUNTS)].copy()
expected_statistical_blocks = len(STATISTICAL_TOPIC_COUNTS) * len(SEEDS)

# Tests use the original evenly spaced K grid; added low-K values remain
# descriptive sensitivity points and cannot change the weighting of inference.
for metric in run_level_metrics:
    pivot = (
        statistical_core_runs.pivot_table(index=["k", "seed"], columns="model", values=metric, aggfunc="first")
        .reindex(columns=core_model_order)
        .dropna()
    )
    if len(pivot) != expected_statistical_blocks:
        raise RuntimeError(f"Incomplete paired blocks for topic metric {metric}: {len(pivot)}")
    statistic, p_value = friedmanchisquare(*[pivot[model].to_numpy(dtype=float) for model in core_model_order])
    topic_friedman_rows.append({
        "analysis": "core_topic_models",
        "metric": metric,
        "block_unit": "K × seed",
        "blocks": len(pivot),
        "models": ", ".join(core_model_order),
        "friedman_chi_square": float(statistic),
        "raw_p": float(p_value),
        "kendalls_w": float(statistic / (len(pivot) * (len(core_model_order) - 1))),
        "alpha": ALPHA,
        "significant_0_05": bool(p_value < ALPHA),
        "inference_scope": "Exploratory repeated-configuration comparison; K and seed blocks are not population samples.",
    })

    temporary: list[dict[str, Any]] = []
    pivot_reset = pivot.reset_index()
    for pair_index, (left, right) in enumerate(combinations(core_model_order, 2)):
        differences = pivot_reset[left] - pivot_reset[right]
        try:
            w_stat, pair_p = wilcoxon(
                pivot_reset[left],
                pivot_reset[right],
                zero_method="wilcox",
                alternative="two-sided",
                method="auto",
            )
        except ValueError:
            w_stat, pair_p = 0.0, 1.0
        difference_frame = pivot_reset[["k", "seed"]].copy()
        difference_frame["difference"] = differences.to_numpy(dtype=float)
        ci_low, ci_high = cluster_bootstrap_mean_ci(
            difference_frame,
            value_column="difference",
            cluster_column="k",
            seed=RANDOM_SEED + 10_000 * run_level_metrics.index(metric) + pair_index,
        )
        temporary.append({
            "analysis": "core_topic_models",
            "metric": metric,
            "model_a": left,
            "model_b": right,
            "paired_blocks": len(differences),
            "mean_difference_a_minus_b": float(differences.mean()),
            "cluster_bootstrap_95_ci_low": ci_low,
            "cluster_bootstrap_95_ci_high": ci_high,
            "bootstrap_clusters": "K",
            "bootstrap_resamples": BOOTSTRAP_RESAMPLES,
            "wilcoxon_statistic": float(w_stat),
            "raw_p": float(pair_p),
            "rank_biserial": rank_biserial_from_differences(differences),
            "alpha": ALPHA,
            "inference_scope": "Exploratory; paired K × seed results with K-cluster bootstrap.",
        })
    adjusted = holm_adjust([row["raw_p"] for row in temporary])
    for row, adjusted_p in zip(temporary, adjusted):
        row["holm_p"] = adjusted_p
        row["significant_holm_0_05"] = bool(adjusted_p < ALPHA)
        topic_pairwise_rows.append(row)

# Stability is defined once per K after three-seed alignment, so its block is K.
stability_pivot = (
    core_aggregate[core_aggregate["k"].isin(STATISTICAL_TOPIC_COUNTS)].pivot(index="k", columns="model", values="stability")
    .reindex(columns=core_model_order)
    .dropna()
)
if len(stability_pivot) == len(STATISTICAL_TOPIC_COUNTS):
    statistic, p_value = friedmanchisquare(*[stability_pivot[model].to_numpy(dtype=float) for model in core_model_order])
    topic_friedman_rows.append({
        "analysis": "core_topic_models",
        "metric": "stability",
        "block_unit": "K",
        "blocks": len(stability_pivot),
        "models": ", ".join(core_model_order),
        "friedman_chi_square": float(statistic),
        "raw_p": float(p_value),
        "kendalls_w": float(statistic / (len(stability_pivot) * (len(core_model_order) - 1))),
        "alpha": ALPHA,
        "significant_0_05": bool(p_value < ALPHA),
        "inference_scope": f"Exploratory stability comparison across {len(STATISTICAL_TOPIC_COUNTS)} predeclared statistical K values.",
    })
    temporary = []
    stability_reset = stability_pivot.reset_index()
    for pair_index, (left, right) in enumerate(combinations(core_model_order, 2)):
        differences = stability_reset[left] - stability_reset[right]
        try:
            w_stat, pair_p = wilcoxon(stability_reset[left], stability_reset[right], method="auto")
        except ValueError:
            w_stat, pair_p = 0.0, 1.0
        ci_low, ci_high = bootstrap_mean_ci(
            differences,
            seed=RANDOM_SEED + 90_000 + pair_index,
        )
        temporary.append({
            "analysis": "core_topic_models",
            "metric": "stability",
            "model_a": left,
            "model_b": right,
            "paired_blocks": len(differences),
            "mean_difference_a_minus_b": float(differences.mean()),
            "cluster_bootstrap_95_ci_low": ci_low,
            "cluster_bootstrap_95_ci_high": ci_high,
            "bootstrap_clusters": "K values",
            "bootstrap_resamples": BOOTSTRAP_RESAMPLES,
            "wilcoxon_statistic": float(w_stat),
            "raw_p": float(pair_p),
            "rank_biserial": rank_biserial_from_differences(differences),
            "alpha": ALPHA,
            "inference_scope": "Exploratory; only nine K-level stability observations.",
        })
    adjusted = holm_adjust([row["raw_p"] for row in temporary])
    for row, adjusted_p in zip(temporary, adjusted):
        row["holm_p"] = adjusted_p
        row["significant_holm_0_05"] = bool(adjusted_p < ALPHA)
        topic_pairwise_rows.append(row)

friedman_results = pd.DataFrame(topic_friedman_rows)
pairwise_topic_results = pd.DataFrame(topic_pairwise_rows)

# Predeclared BERTopic encoder sensitivity: multilingual MiniLM vs mean-pooled ParsBERT.
encoder_test_rows: list[dict[str, Any]] = []
for metric_index, metric in enumerate(run_level_metrics):
    pivot = (
        statistical_encoder_runs.pivot_table(index=["k", "seed"], columns="model", values=metric, aggfunc="first")
        .reindex(columns=["BERTopic", "BERTopic-ParsBERT"])
        .dropna()
    )
    if len(pivot) != expected_statistical_blocks:
        raise RuntimeError(f"Incomplete BERTopic encoder blocks for {metric}: {len(pivot)}")
    differences = pivot["BERTopic-ParsBERT"] - pivot["BERTopic"]
    try:
        statistic, raw_p = wilcoxon(
            pivot["BERTopic-ParsBERT"],
            pivot["BERTopic"],
            zero_method="wilcox",
            alternative="two-sided",
            method="auto",
        )
    except ValueError:
        statistic, raw_p = 0.0, 1.0
    difference_frame = pivot.reset_index()[["k", "seed"]].copy()
    difference_frame["difference"] = differences.to_numpy(dtype=float)
    ci_low, ci_high = cluster_bootstrap_mean_ci(
        difference_frame,
        value_column="difference",
        cluster_column="k",
        seed=RANDOM_SEED + 120_000 + metric_index,
    )
    encoder_test_rows.append({
        "analysis": "bertopic_encoder_sensitivity",
        "metric": metric,
        "model_a": "BERTopic-ParsBERT",
        "model_b": "BERTopic",
        "paired_blocks": len(differences),
        "mean_difference_a_minus_b": float(differences.mean()),
        "cluster_bootstrap_95_ci_low": ci_low,
        "cluster_bootstrap_95_ci_high": ci_high,
        "wilcoxon_statistic": float(statistic),
        "raw_p": float(raw_p),
        "rank_biserial": rank_biserial_from_differences(differences),
        "alpha": ALPHA,
        "inference_scope": "Encoder sensitivity conditional on fixed BERTopic/UMAP/KMeans/c-TF-IDF settings.",
    })
encoder_adjusted = holm_adjust([row["raw_p"] for row in encoder_test_rows])
for row, adjusted_p in zip(encoder_test_rows, encoder_adjusted):
    row["holm_p"] = adjusted_p
    row["significant_holm_0_05"] = bool(adjusted_p < ALPHA)
bertopic_encoder_tests = pd.DataFrame(encoder_test_rows)

print("\nFriedman tests")
display(friedman_results)
print("\nWilcoxon pairwise tests with Holm correction, rank-biserial effects, and 5,000-resample CIs")
display(pairwise_topic_results)
print("\nBERTopic encoder sensitivity tests")
display(bertopic_encoder_tests)

# =============================================================================
# 7. TRUE PREPROCESSING ABLATION FROM RAW TEXT
# =============================================================================

heading("4. Preprocessing ablation")
ablation_rows: list[dict[str, Any]] = []
if RUN_PREPROCESSING_ABLATION:
    ablation_train_source = train.sample(n=ABLATION_TRAIN_DOCS, random_state=RANDOM_SEED).reset_index(drop=True)
    ablation_test_source = topic_validation.sample(n=ABLATION_TEST_DOCS, random_state=RANDOM_SEED).reset_index(drop=True)
    variants = {
        "full": dict(normalize_text=True, remove_stopwords=True, lemmatize=True),
        "no_lemmatization": dict(normalize_text=True, remove_stopwords=True, lemmatize=False),
        "no_stopword_removal": dict(normalize_text=True, remove_stopwords=False, lemmatize=True),
        "normalization_tokenization_only": dict(normalize_text=True, remove_stopwords=False, lemmatize=False),
    }
    for variant_name, options in variants.items():
        train_outputs = [
            preprocess_text_with_reason(text, **options)
            for text in tqdm(ablation_train_source["raw_text"], desc=f"Ablation {variant_name} train")
        ]
        test_outputs = [
            preprocess_text_with_reason(text, **options)
            for text in tqdm(ablation_test_source["raw_text"], desc=f"Ablation {variant_name} test")
        ]
        variant_train = [text for text, _reason in train_outputs if text]
        variant_test = [text for text, _reason in test_outputs if text]
        if len(variant_train) < int(0.95 * ABLATION_TRAIN_DOCS) or len(variant_test) < int(0.95 * ABLATION_TEST_DOCS):
            raise RuntimeError(
                f"Ablation {variant_name} retained only {len(variant_train)} train and {len(variant_test)} test documents."
            )
        token_train = [text.split() for text in variant_train]
        token_test = [text.split() for text in variant_test]
        dictionary = Dictionary(token_train)
        dictionary.filter_extremes(no_below=3, no_above=0.8)
        if len(dictionary) < ABLATION_K * TOP_N_WORDS:
            raise RuntimeError(f"Ablation {variant_name} dictionary is too small: {len(dictionary)}")
        corpus = [dictionary.doc2bow(tokens) for tokens in token_train]
        variant_reference = Dictionary(token_test)
        for seed in SEEDS:
            set_seed(seed)
            started = time.time()
            model = LdaModel(
                corpus=corpus,
                id2word=dictionary,
                num_topics=ABLATION_K,
                random_state=seed,
                passes=LDA_PASSES,
                iterations=LDA_ITERATIONS,
                alpha=LDA_ALPHA,
                eta=LDA_ETA,
                minimum_probability=0.0,
                eval_every=None,
            )
            raw_topics = [
                [word for word, _ in model.show_topic(topic_id, topn=TOPIC_CANDIDATE_WORDS)]
                for topic_id in range(ABLATION_K)
            ]
            metrics, _canonical_topics = evaluate_topics_against_reference(
                raw_topics,
                token_test,
                variant_reference,
            )
            if not all(math.isfinite(metrics[column]) for column in ("c_v", "c_npmi", "diversity", "distinctness")):
                raise RuntimeError(f"Non-finite ablation metrics for {variant_name}, seed={seed}: {metrics}")
            ablation_rows.append({
                "variant": variant_name,
                "seed": seed,
                "k": ABLATION_K,
                "train_documents_requested": ABLATION_TRAIN_DOCS,
                "validation_documents_requested": ABLATION_TEST_DOCS,
                "train_documents_retained": len(variant_train),
                "validation_documents_retained": len(variant_test),
                "c_v": metrics["c_v"],
                "c_npmi": metrics["c_npmi"],
                "diversity": metrics["diversity"],
                "distinctness": metrics["distinctness"],
                "valid_topic_count": metrics["valid_topic_count"],
                "training_seconds": time.time() - started,
            })
            del model

ablation_runs = pd.DataFrame(ablation_rows)
ablation_summary_rows: list[dict[str, Any]] = []
for variant, group in ablation_runs.groupby("variant", sort=True):
    row: dict[str, Any] = {
        "variant": variant,
        "runs": len(group),
        "k": ABLATION_K,
        "train_documents_retained": int(group["train_documents_retained"].iloc[0]),
        "validation_documents_retained": int(group["validation_documents_retained"].iloc[0]),
        "valid_topic_count_mean": group["valid_topic_count"].mean(),
    }
    for metric_index, metric in enumerate(("c_v", "c_npmi", "diversity", "distinctness")):
        ci_low, ci_high = bootstrap_mean_ci(group[metric], seed=RANDOM_SEED + 200_000 + metric_index + len(ablation_summary_rows))
        row[f"{metric}_mean"] = group[metric].mean()
        row[f"{metric}_sd"] = group[metric].std(ddof=1)
        row[f"{metric}_bootstrap_ci_low"] = ci_low
        row[f"{metric}_bootstrap_ci_high"] = ci_high
    ablation_summary_rows.append(row)
ablation_summary = pd.DataFrame(ablation_summary_rows)

ablation_friedman_rows: list[dict[str, Any]] = []
ablation_pairwise_rows: list[dict[str, Any]] = []
ablation_variant_order = [
    "full", "no_lemmatization", "no_stopword_removal", "normalization_tokenization_only"
]
for metric_index, metric in enumerate(("c_v", "c_npmi", "diversity", "distinctness")):
    pivot = ablation_runs.pivot(index="seed", columns="variant", values=metric).reindex(columns=ablation_variant_order).dropna()
    if len(pivot) != len(SEEDS):
        raise RuntimeError(f"Incomplete ablation blocks for {metric}: {len(pivot)}")
    statistic, p_value = friedmanchisquare(*[pivot[variant].to_numpy(dtype=float) for variant in ablation_variant_order])
    if not math.isfinite(float(statistic)) or not math.isfinite(float(p_value)):
        statistic, p_value = 0.0, 1.0
    ablation_friedman_rows.append({
        "metric": metric, "block_unit": "seed", "blocks": len(pivot),
        "variants": ", ".join(ablation_variant_order),
        "friedman_chi_square": float(statistic), "raw_p": float(p_value),
        "kendalls_w": float(statistic / (len(pivot) * (len(ablation_variant_order) - 1))) if len(pivot) else None,
        "alpha": ALPHA, "significant_0_05": bool(p_value < ALPHA),
        "inference_scope": "Exploratory ablation inference with only three seeds; low statistical power.",
    })
    temporary: list[dict[str, Any]] = []
    for pair_index, (left, right) in enumerate(combinations(ablation_variant_order, 2)):
        differences = pivot[left] - pivot[right]
        try:
            w_stat, raw_p = wilcoxon(pivot[left], pivot[right], zero_method="wilcox", alternative="two-sided", method="auto")
        except ValueError:
            w_stat, raw_p = 0.0, 1.0
        ci_low, ci_high = bootstrap_mean_ci(
            differences, seed=RANDOM_SEED + 230_000 + 1000 * metric_index + pair_index
        )
        temporary.append({
            "metric": metric, "variant_a": left, "variant_b": right,
            "paired_seeds": len(differences),
            "mean_difference_a_minus_b": float(differences.mean()),
            "bootstrap_95_ci_low": ci_low, "bootstrap_95_ci_high": ci_high,
            "bootstrap_resamples": BOOTSTRAP_RESAMPLES,
            "wilcoxon_statistic": float(w_stat), "raw_p": float(raw_p),
            "rank_biserial": rank_biserial_from_differences(differences),
            "alpha": ALPHA,
            "inference_scope": "Exploratory; three paired seeds only.",
        })
    adjusted = holm_adjust([row["raw_p"] for row in temporary])
    for row, adjusted_p in zip(temporary, adjusted):
        row["holm_p"] = adjusted_p
        row["significant_holm_0_05"] = bool(adjusted_p < ALPHA)
        ablation_pairwise_rows.append(row)
ablation_friedman_results = pd.DataFrame(ablation_friedman_rows)
ablation_pairwise_tests = pd.DataFrame(ablation_pairwise_rows)

print("\nPreprocessing-ablation run-level results")
display(ablation_runs)
print("\nPreprocessing-ablation aggregate results")
display(ablation_summary)
print("\nPreprocessing-ablation Friedman tests")
display(ablation_friedman_results)
print("\nPreprocessing-ablation pairwise tests with Holm correction")
display(ablation_pairwise_tests)

# =============================================================================
# 8. STANZA NER — NO DUMMY FALLBACKS
# =============================================================================

heading("5. Persian named-entity recognition")
ALLOWED_ENTITY_TYPES = ("Person", "Location", "Organization", "Product", "Facility", "Event")
ENTITY_TYPE_MAP = {
    "LOC": "Location", "LOCATION": "Location", "GPE": "Location",
    "PER": "Person", "PERS": "Person", "PERSON": "Person",
    "ORG": "Organization", "ORGANIZATION": "Organization",
    "FAC": "Facility", "FACILITY": "Facility",
    "PRODUCT": "Product", "PRO": "Product",
    "EVENT": "Event",
}


def normalize_entity_surface(text: str) -> str:
    normalized = normalize_base_text(text, use_hazm=True).replace("\u200c", " ")
    return WHITESPACE_RE.sub(" ", normalized).strip()


stanza_dir = TEMP_DIR / "stanza_resources"
stanza.download("fa", processors="tokenize,ner", model_dir=str(stanza_dir), verbose=False)
ner_pipeline = stanza.Pipeline(
    lang="fa",
    processors="tokenize,ner",
    model_dir=str(stanza_dir),
    use_gpu=STANZA_USE_GPU and torch.cuda.is_available(),
    ner_batch_size=STANZA_NER_BATCH_SIZE,
    verbose=False,
)


def run_ner(
    frame: pd.DataFrame,
    split_name: str,
    max_docs: int,
) -> tuple[list[list[tuple[str, str]]], pd.DataFrame, dict[str, Any], pd.DataFrame]:
    subset = frame.iloc[:max_docs].reset_index(drop=True)
    if len(subset) != max_docs:
        raise RuntimeError(f"NER expected {max_docs} {split_name} documents, obtained {len(subset)}.")

    doc_entities: list[list[tuple[str, str]]] = []
    mention_rows: list[dict[str, Any]] = []
    errors: list[dict[str, Any]] = []
    excluded_type_counter: Counter[str] = Counter()
    documents_with_entities = 0

    for position, row in tqdm(subset.iterrows(), total=len(subset), desc=f"Stanza NER {split_name}"):
        raw_text = str(row["raw_text"])[:NER_MAX_CHARS_PER_DOC]
        try:
            document = ner_pipeline(raw_text)
            mentions: list[tuple[str, str]] = []
            for entity in document.ents:
                raw_type = str(entity.type).upper().replace("B-", "").replace("I-", "")
                entity_type = ENTITY_TYPE_MAP.get(raw_type)
                if entity_type not in ALLOWED_ENTITY_TYPES:
                    excluded_type_counter[raw_type] += 1
                    continue
                surface = normalize_entity_surface(entity.text)
                if not surface:
                    continue
                typed = (surface, entity_type)
                mentions.append(typed)
                mention_rows.append({
                    "split": split_name,
                    "doc_position": int(position),
                    "doc_id": int(row["doc_id"]),
                    "surface": surface,
                    "entity_type": entity_type,
                    "raw_ner_type": str(entity.type),
                })
            if mentions:
                documents_with_entities += 1
            doc_entities.append(mentions)
        except Exception as exc:
            doc_entities.append([])
            errors.append({
                "split": split_name,
                "doc_position": int(position),
                "doc_id": int(row["doc_id"]),
                "error": repr(exc),
            })

    mentions = pd.DataFrame(mention_rows)
    errors_frame = pd.DataFrame(errors)
    error_rate = len(errors) / len(subset)
    if error_rate >= MAX_ACCEPTABLE_NER_ERROR_RATE:
        raise RuntimeError(
            f"NER error rate for {split_name} was {error_rate:.4%}; protocol requires < {MAX_ACCEPTABLE_NER_ERROR_RATE:.2%}."
        )
    if mentions.empty:
        raise RuntimeError(f"Stanza returned zero accepted entities for {split_name}; no fallback data are allowed.")
    if not set(mentions["entity_type"]).issubset(ALLOWED_ENTITY_TYPES):
        raise RuntimeError(f"Unexpected entity types remained in {split_name}: {set(mentions['entity_type'])}")

    diagnostics = {
        "split": split_name,
        "documents_processed": len(subset),
        "documents_with_entities": documents_with_entities,
        "documents_with_errors": len(errors),
        "error_rate": error_rate,
        "max_characters_per_document": NER_MAX_CHARS_PER_DOC,
        "total_mentions": len(mentions),
        "unique_surface_forms": int(mentions["surface"].nunique()),
        "unique_typed_surface_nodes": int(mentions[["surface", "entity_type"]].drop_duplicates().shape[0]),
        "excluded_unknown_type_mentions": int(sum(excluded_type_counter.values())),
        "excluded_unknown_type_counts": dict(excluded_type_counter),
        "dummy_or_fallback_entities_used": False,
    }
    return doc_entities, mentions, diagnostics, errors_frame


train_doc_entities, train_mentions, train_ner_diagnostics, train_ner_errors = run_ner(
    train, "train", NER_TRAIN_DOCS
)
test_doc_entities, test_mentions, test_ner_diagnostics, test_ner_errors = run_ner(
    test, "link_test", NER_TEST_DOCS
)

ner_type_summary = pd.DataFrame({"entity_type": ALLOWED_ENTITY_TYPES})
train_type_counts = train_mentions["entity_type"].value_counts()
test_type_counts = test_mentions["entity_type"].value_counts()
ner_type_summary["train_mentions"] = ner_type_summary["entity_type"].map(train_type_counts).fillna(0).astype(int)
ner_type_summary["test_mentions"] = ner_type_summary["entity_type"].map(test_type_counts).fillna(0).astype(int)
ner_type_summary["train_percent"] = 100 * ner_type_summary["train_mentions"] / ner_type_summary["train_mentions"].sum()
ner_type_summary["test_percent"] = 100 * ner_type_summary["test_mentions"] / ner_type_summary["test_mentions"].sum()

train_surface_counts = (
    train_mentions.groupby(["surface", "entity_type"], as_index=False)
    .size()
    .rename(columns={"size": "mentions"})
    .sort_values(["mentions", "surface"], ascending=[False, True])
)
test_surface_counts = (
    test_mentions.groupby(["surface", "entity_type"], as_index=False)
    .size()
    .rename(columns={"size": "mentions"})
    .sort_values(["mentions", "surface"], ascending=[False, True])
)
top_entity_surfaces = train_surface_counts.head(100).reset_index(drop=True)
top_entity_surfaces_test = test_surface_counts.head(100).reset_index(drop=True)
top_entity_surfaces_by_type = (
    train_surface_counts.sort_values(["entity_type", "mentions", "surface"], ascending=[True, False, True])
    .groupby("entity_type", as_index=False, group_keys=False)
    .head(20)
    .reset_index(drop=True)
)
top_entity_surfaces_by_type_test = (
    test_surface_counts.sort_values(["entity_type", "mentions", "surface"], ascending=[True, False, True])
    .groupby("entity_type", as_index=False, group_keys=False)
    .head(20)
    .reset_index(drop=True)
)
ner_summary = pd.DataFrame([train_ner_diagnostics, test_ner_diagnostics])
ner_errors = pd.concat([train_ner_errors, test_ner_errors], ignore_index=True)

# Deterministic, unscored audit template. It supports later human validation
# without fabricating precision/recall or agreement statistics.
def make_ner_audit_template(target_rows: int = 200) -> pd.DataFrame:
    combined = pd.concat([train_mentions, test_mentions], ignore_index=True)
    source_lookup = pd.concat([
        train[["doc_id", "raw_text"]].assign(split="train"),
        test[["doc_id", "raw_text"]].assign(split="link_test"),
    ], ignore_index=True)
    samples: list[pd.DataFrame] = []
    groups = list(combined.groupby(["split", "entity_type"], sort=True))
    per_group = max(1, math.ceil(target_rows / max(len(groups), 1)))
    for group_index, ((_split, _type), group) in enumerate(groups):
        samples.append(group.sample(n=min(per_group, len(group)), random_state=RANDOM_SEED + group_index))
    audit = pd.concat(samples, ignore_index=True).head(target_rows)
    audit = audit.merge(source_lookup, on=["split", "doc_id"], how="left", validate="many_to_one")
    audit["document_excerpt"] = audit["raw_text"].astype(str).str.slice(0, 700)
    audit = audit.drop(columns="raw_text")
    audit["boundary_correct"] = ""
    audit["type_correct"] = ""
    audit["canonical_entity_or_alias"] = ""
    audit["annotator"] = ""
    audit["notes"] = ""
    return audit.sort_values(["split", "entity_type", "doc_id", "surface"]).reset_index(drop=True)


ner_audit_template = make_ner_audit_template()
stanza_resource_hashes = sha256_directory(stanza_dir)

ner_document_rows: list[dict[str, Any]] = []
for split_name, source_frame, entities_by_doc, error_frame in (
    ("train", train.iloc[:NER_TRAIN_DOCS].reset_index(drop=True), train_doc_entities, train_ner_errors),
    ("link_test", test.iloc[:NER_TEST_DOCS].reset_index(drop=True), test_doc_entities, test_ner_errors),
):
    error_positions = set(error_frame["doc_position"].astype(int)) if not error_frame.empty else set()
    for position, entities in enumerate(entities_by_doc):
        ner_document_rows.append({
            "split": split_name,
            "doc_position": position,
            "doc_id": int(source_frame.iloc[position]["doc_id"]),
            "mention_count": len(entities),
            "unique_typed_entity_count": len(set(entities)),
            "has_entity": bool(entities),
            "processing_error": position in error_positions,
        })
ner_document_summary = pd.DataFrame(ner_document_rows)
entity_surface_frequency_all = pd.concat([
    train_surface_counts.assign(split="train"),
    test_surface_counts.assign(split="link_test"),
], ignore_index=True)[["split", "surface", "entity_type", "mentions"]].sort_values(
    ["split", "mentions", "surface"], ascending=[True, False, True]
).reset_index(drop=True)

print("\nNER diagnostics")
display(ner_summary)
print("\nEntity-type distribution")
display(ner_type_summary)
print("\nTop entity surface forms overall")
display(top_entity_surfaces.head(30))
print("\nTop training entity surface forms by type")
display(top_entity_surfaces_by_type)
print("\nTop test entity surface forms overall")
display(top_entity_surfaces_test.head(30))
print("\nTop test entity surface forms by type")
display(top_entity_surfaces_by_type_test)
print(f"\nComplete NER document diagnostics contain {len(ner_document_summary):,} rows and are saved in the final JSON evidence.")
display(ner_document_summary.head(200))
print("\nUnscored NER human-audit template (complete template saved in JSON)")
display(ner_audit_template.head(30))
if not ner_errors.empty:
    print("\nNER document errors (error rate remained below 1%)")
    display(ner_errors)

# =============================================================================
# 9. TRAIN-ONLY ENTITY GRAPH AND TOPIC VECTORS
# =============================================================================

heading("6. Entity-association graph")

mention_frequency: Counter[tuple[str, str]] = Counter()
document_frequency: Counter[tuple[str, str]] = Counter()
for mentions in train_doc_entities:
    mention_frequency.update(mentions)
    document_frequency.update(set(mentions))
ranked_entities = [entity for entity, _count in document_frequency.most_common(MAX_GRAPH_NODES)]
entity_to_id = {entity: idx for idx, entity in enumerate(ranked_entities)}

edge_counts: Counter[tuple[int, int]] = Counter()
doc_entity_ids: list[list[int]] = []
for mentions in train_doc_entities:
    unique_ids = {entity_to_id[entity] for entity in set(mentions) if entity in entity_to_id}
    ordered_ids = sorted(unique_ids, key=lambda entity_id: (-document_frequency[ranked_entities[entity_id]], entity_id))
    ordered_ids = ordered_ids[:MAX_ENTITIES_PER_DOCUMENT]
    doc_entity_ids.append(ordered_ids)
    for left, right in combinations(sorted(ordered_ids), 2):
        edge_counts[(left, right)] += 1

train_graph = nx.Graph()
for entity_id, (surface, entity_type) in enumerate(ranked_entities):
    train_graph.add_node(
        entity_id,
        surface=surface,
        entity_type=entity_type,
        mention_frequency=int(mention_frequency[(surface, entity_type)]),
        document_frequency=int(document_frequency[(surface, entity_type)]),
    )
for (left, right), weight in edge_counts.items():
    train_graph.add_edge(left, right, weight=int(weight))

entity_inventory = pd.DataFrame([
    {
        "entity_id": entity_id,
        "surface": surface,
        "entity_type": entity_type,
        "mention_frequency": int(mention_frequency[(surface, entity_type)]),
        "document_frequency": int(document_frequency[(surface, entity_type)]),
    }
    for entity_id, (surface, entity_type) in enumerate(ranked_entities)
])

if train_graph.number_of_nodes() < LINK_PREDICTION_NODES:
    raise RuntimeError("The training graph has fewer nodes than the requested evaluation graph.")


def dense_document_topic_matrix(model: LdaModel, token_lists: Sequence[Sequence[str]]) -> np.ndarray:
    matrix = np.zeros((len(token_lists), model.num_topics), dtype=np.float32)
    for index, tokens in enumerate(tqdm(token_lists, desc=f"LDA K={model.num_topics} document-topic inference")):
        bow = model.id2word.doc2bow(tokens)
        distribution = model.get_document_topics(bow, minimum_probability=0.0)
        for topic_id, probability in distribution:
            matrix[index, topic_id] = probability
    return matrix


def entity_topic_vectors_for_model(model: LdaModel) -> np.ndarray:
    doc_topics = dense_document_topic_matrix(model, train_tokens)
    sums = np.zeros((len(ranked_entities), model.num_topics), dtype=np.float64)
    counts = np.zeros(len(ranked_entities), dtype=np.int64)
    for doc_index, entity_ids in enumerate(doc_entity_ids):
        for entity_id in entity_ids:
            sums[entity_id] += doc_topics[doc_index]
            counts[entity_id] += 1
    vectors = np.zeros_like(sums, dtype=np.float32)
    nonzero = counts > 0
    vectors[nonzero] = (sums[nonzero] / counts[nonzero, None]).astype(np.float32)
    return normalize(vectors, norm="l2", copy=False).astype(np.float32)


entity_topic_vectors_by_k: dict[int, np.ndarray] = {}
for k in GRAPH_TOPIC_K_SENSITIVITY:
    if k not in selected_lda_models:
        raise RuntimeError(f"Required graph LDA model K={k} was not retained.")
    entity_topic_vectors_by_k[k] = entity_topic_vectors_for_model(selected_lda_models[k])

components = list(nx.connected_components(train_graph))
component_sizes = np.asarray(sorted((len(component) for component in components), reverse=True), dtype=float)
degrees = np.asarray([degree for _node, degree in train_graph.degree()], dtype=float)
edge_weights = np.asarray([data.get("weight", 1.0) for _u, _v, data in train_graph.edges(data=True)], dtype=float)
if len(degrees) == 0 or len(edge_weights) == 0:
    raise RuntimeError("The train-only entity graph is empty.")

graph_summary = pd.DataFrame([{
    "source_split": "training only",
    "all_typed_nodes_before_cap": len(document_frequency),
    "retained_graph_nodes": train_graph.number_of_nodes(),
    "node_cap": MAX_GRAPH_NODES,
    "train_edges": train_graph.number_of_edges(),
    "density": nx.density(train_graph),
    "connected_components": len(components),
    "giant_component_nodes": int(component_sizes.max()),
    "giant_component_fraction": float(component_sizes.max() / train_graph.number_of_nodes()),
    "isolates": nx.number_of_isolates(train_graph),
    "mean_degree": float(degrees.mean()),
    "degree_sd": float(degrees.std(ddof=1)),
    "median_degree": float(np.median(degrees)),
    "max_degree": int(degrees.max()),
    "mean_edge_weight": float(edge_weights.mean()),
    "edge_weight_sd": float(edge_weights.std(ddof=1)),
    "median_edge_weight": float(np.median(edge_weights)),
    "max_edge_weight": int(edge_weights.max()),
    "approximate_average_clustering": nx.approximation.average_clustering(
        train_graph,
        trials=min(2_000, max(100, train_graph.number_of_nodes())),
        seed=RANDOM_SEED,
    ),
}])

def distribution_summary(values: np.ndarray, variable: str) -> pd.DataFrame:
    quantiles = [0.0, 0.01, 0.05, 0.10, 0.25, 0.50, 0.75, 0.90, 0.95, 0.99, 1.0]
    return pd.DataFrame({
        "variable": variable,
        "quantile": quantiles,
        "value": [float(np.quantile(values, quantile)) for quantile in quantiles],
    })

graph_degree_distribution = distribution_summary(degrees, "node_degree")
graph_edge_weight_distribution = distribution_summary(edge_weights, "edge_weight")
graph_component_distribution = distribution_summary(component_sizes, "component_size")

graph_type_summary = pd.DataFrame({"entity_type": ALLOWED_ENTITY_TYPES})
graph_type_counts = Counter(train_graph.nodes[node]["entity_type"] for node in train_graph.nodes)
graph_type_summary["retained_nodes"] = graph_type_summary["entity_type"].map(graph_type_counts).fillna(0).astype(int)
graph_type_summary["percent"] = 100 * graph_type_summary["retained_nodes"] / graph_type_summary["retained_nodes"].sum()

graph_topic_vector_summary = pd.DataFrame([
    {
        "topic_k": k,
        "entities": vectors.shape[0],
        "vector_dimensions": vectors.shape[1],
        "finite_values": bool(np.isfinite(vectors).all()),
        "nonzero_entity_vectors": int((np.linalg.norm(vectors, axis=1) > 0).sum()),
        "construction": "mean training-document LDA topic distribution per typed entity, then L2 normalization",
    }
    for k, vectors in sorted(entity_topic_vectors_by_k.items())
])
if not graph_topic_vector_summary["finite_values"].all():
    raise RuntimeError("Non-finite entity-topic vectors detected.")

print("\nGraph summary")
display(graph_summary)
print(f"\nEntity inventory contains {len(entity_inventory):,} typed surface-form nodes; complete table is saved in the final JSON evidence.")
display(entity_inventory.head(200))
print("\nGraph node-type distribution")
display(graph_type_summary)
print("\nDegree distribution")
display(graph_degree_distribution)
print("\nEdge-weight distribution")
display(graph_edge_weight_distribution)
print("\nConnected-component size distribution")
display(graph_component_distribution)
print("\nEntity-topic vector sensitivity summary")
display(graph_topic_vector_summary)

# =============================================================================
# 10. LEAKAGE-CONTROLLED REPEATED NOVEL-LINK PREDICTION
# =============================================================================

heading("7. Leakage-controlled novel-link prediction")


def canonical_pair(left: int, right: int) -> tuple[int, int]:
    if left == right:
        raise ValueError("Self-pairs are not valid graph links.")
    return (left, right) if left < right else (right, left)


def hash_pair_set(pairs: Sequence[tuple[int, int]]) -> str:
    digest = hashlib.sha256()
    for left, right in sorted(pairs):
        digest.update(f"{int(left)},{int(right)}\n".encode("utf-8"))
    return digest.hexdigest()


def pairs_from_documents(doc_entities: Sequence[Sequence[tuple[str, str]]], allowed_nodes: set[int]) -> set[tuple[int, int]]:
    pairs: set[tuple[int, int]] = set()
    for mentions in doc_entities:
        node_ids = sorted({entity_to_id[entity] for entity in set(mentions) if entity in entity_to_id and entity_to_id[entity] in allowed_nodes})
        node_ids = node_ids[:MAX_ENTITIES_PER_DOCUMENT]
        for left, right in combinations(node_ids, 2):
            pairs.add(canonical_pair(left, right))
    return pairs


def weighted_node2vec_walk(graph: nx.Graph, start: int, walk_length: int, p: float, q: float, rng: np.random.Generator) -> list[str]:
    walk = [start]
    while len(walk) < walk_length:
        current = walk[-1]
        neighbors = list(graph.neighbors(current))
        if not neighbors:
            break
        if len(walk) == 1:
            weights = np.asarray([graph[current][neighbor].get("weight", 1.0) for neighbor in neighbors], dtype=float)
        else:
            previous = walk[-2]
            weights = []
            for neighbor in neighbors:
                edge_weight = float(graph[current][neighbor].get("weight", 1.0))
                if neighbor == previous:
                    bias = 1.0 / p
                elif graph.has_edge(previous, neighbor):
                    bias = 1.0
                else:
                    bias = 1.0 / q
                weights.append(edge_weight * bias)
            weights = np.asarray(weights, dtype=float)
        probabilities = weights / weights.sum() if weights.sum() > 0 else np.full(len(neighbors), 1 / len(neighbors))
        walk.append(int(rng.choice(neighbors, p=probabilities)))
    return [str(node) for node in walk]


def train_walk_embeddings(graph: nx.Graph, p: float, q: float, seed: int) -> dict[int, np.ndarray]:
    rng = np.random.default_rng(seed)
    nodes = list(graph.nodes())
    walks: list[list[str]] = []
    for _ in range(WALKS_PER_NODE):
        rng.shuffle(nodes)
        for node in nodes:
            walks.append(weighted_node2vec_walk(graph, int(node), WALK_LENGTH, p, q, rng))
    model = Word2Vec(
        sentences=walks,
        vector_size=EMBEDDING_DIM,
        window=WORD2VEC_WINDOW,
        min_count=1,
        sg=1,
        workers=1,
        epochs=WORD2VEC_EPOCHS,
        seed=seed,
    )
    return {int(node): model.wv[str(node)] for node in graph.nodes if str(node) in model.wv}


def cosine_score(left: np.ndarray, right: np.ndarray) -> float:
    denominator = float(np.linalg.norm(left) * np.linalg.norm(right))
    return float(np.dot(left, right) / denominator) if denominator else 0.0


def build_degree_bins(graph: nx.Graph, nodes: Sequence[int], n_bins: int) -> tuple[dict[int, int], dict[int, list[int]]]:
    degrees_series = pd.Series({int(node): graph.degree(node) for node in nodes}, dtype=float)
    try:
        labels = pd.qcut(degrees_series.rank(method="first"), q=min(n_bins, len(nodes)), labels=False, duplicates="drop")
    except ValueError:
        labels = pd.Series(0, index=degrees_series.index)
    node_to_bin = {int(node): int(label) for node, label in labels.items()}
    bin_to_nodes: dict[int, list[int]] = defaultdict(list)
    for node, label in node_to_bin.items():
        bin_to_nodes[label].append(node)
    return node_to_bin, dict(bin_to_nodes)


def degree_bin_matched_negatives(
    positives: Sequence[tuple[int, int]],
    forbidden: set[tuple[int, int]],
    graph: nx.Graph,
    nodes: Sequence[int],
    count: int,
    seed: int,
) -> list[tuple[int, int]]:
    rng = np.random.default_rng(seed)
    node_to_bin, bin_to_nodes = build_degree_bins(graph, nodes, DEGREE_MATCH_BINS)
    negatives: set[tuple[int, int]] = set()
    attempts = 0
    max_attempts = max(200_000, count * 500)
    positive_cycle = itertools.cycle(positives)
    while len(negatives) < count and attempts < max_attempts:
        source_left, source_right = next(positive_cycle)
        left_pool = bin_to_nodes.get(node_to_bin[source_left], list(nodes))
        right_pool = bin_to_nodes.get(node_to_bin[source_right], list(nodes))
        left = int(rng.choice(left_pool))
        right = int(rng.choice(right_pool))
        attempts += 1
        if left == right:
            continue
        pair = canonical_pair(left, right)
        if pair not in forbidden and pair not in negatives:
            negatives.add(pair)
    if len(negatives) < count:
        raise RuntimeError(f"Could sample only {len(negatives)} of {count} degree-matched negatives.")
    return sorted(negatives)


def adamic_adar_score(graph: nx.Graph, left: int, right: int) -> float:
    common = set(graph.neighbors(left)) & set(graph.neighbors(right))
    score = 0.0
    for node in common:
        degree = graph.degree(node)
        if degree > 1:
            score += 1.0 / math.log(degree)
    return score


ranked_evaluation_nodes = sorted(
    train_graph.nodes,
    key=lambda node: (-train_graph.nodes[node].get("document_frequency", 0), node),
)[:LINK_PREDICTION_NODES]
allowed_nodes = set(int(node) for node in ranked_evaluation_nodes)
evaluation_graph = train_graph.subgraph(ranked_evaluation_nodes).copy()
train_edges = {canonical_pair(int(left), int(right)) for left, right in evaluation_graph.edges}
all_test_pairs = pairs_from_documents(test_doc_entities, allowed_nodes)
all_forbidden = train_edges | all_test_pairs

link_rows: list[dict[str, Any]] = []
link_fold_assignment_rows: list[dict[str, Any]] = []
link_evaluation_diagnostic_rows: list[dict[str, Any]] = []
for repeat in range(LINK_REPEATS):
    embedding_seed = RANDOM_SEED + 1_000 * repeat
    deepwalk_embeddings = train_walk_embeddings(evaluation_graph, p=1.0, q=1.0, seed=embedding_seed)
    node2vec_embeddings = train_walk_embeddings(evaluation_graph, p=NODE2VEC_P, q=NODE2VEC_Q, seed=embedding_seed)

    fold_splits = list(
        KFold(n_splits=LINK_FOLDS, shuffle=True, random_state=embedding_seed)
        .split(np.arange(len(test_doc_entities)))
    )
    doc_to_fold: dict[int, int] = {}
    for fold, (_unused, doc_indices) in enumerate(fold_splits, start=1):
        for document_position in doc_indices:
            doc_to_fold[int(document_position)] = fold
            link_fold_assignment_rows.append({
                "repeat": repeat + 1,
                "fold": fold,
                "evaluation_id": f"R{repeat + 1}F{fold}",
                "link_test_doc_position": int(document_position),
                "doc_id": int(test.iloc[int(document_position)]["doc_id"]),
            })

    # Assign each novel test pair to exactly one fold in which it occurs. This
    # prevents the same positive edge from appearing in multiple folds of a repeat.
    candidate_folds_by_pair: dict[tuple[int, int], set[int]] = defaultdict(set)
    for document_position, mentions in enumerate(test_doc_entities):
        fold = doc_to_fold[document_position]
        for pair in pairs_from_documents([mentions], allowed_nodes) - train_edges:
            candidate_folds_by_pair[pair].add(fold)

    positive_pairs_by_fold: dict[int, list[tuple[int, int]]] = {fold: [] for fold in range(1, LINK_FOLDS + 1)}
    for pair, candidate_folds in candidate_folds_by_pair.items():
        candidates = sorted(candidate_folds)
        digest = hashlib.sha256(f"{repeat}|{pair[0]}|{pair[1]}".encode("utf-8")).digest()
        assigned_fold = candidates[int.from_bytes(digest[:8], "big") % len(candidates)]
        positive_pairs_by_fold[assigned_fold].append(pair)

    used_positive_pairs: set[tuple[int, int]] = set()
    used_negative_pairs: set[tuple[int, int]] = set()
    for fold, (_unused, doc_indices) in enumerate(fold_splits, start=1):
        positives = sorted(positive_pairs_by_fold[fold])
        rng = np.random.default_rng(embedding_seed + fold)
        if len(positives) > MAX_POSITIVE_EDGES_PER_FOLD:
            chosen = rng.choice(len(positives), size=MAX_POSITIVE_EDGES_PER_FOLD, replace=False)
            positives = [positives[index] for index in chosen]
        if len(positives) < 20:
            raise RuntimeError(f"Repeat {repeat + 1}, fold {fold} has only {len(positives)} unique novel positives.")
        positives = sorted(set(positives))
        if set(positives) & used_positive_pairs:
            raise RuntimeError("Positive test pairs were reused across folds within a repeat.")

        negatives = degree_bin_matched_negatives(
            positives=positives,
            forbidden=all_forbidden | used_negative_pairs,
            graph=evaluation_graph,
            nodes=ranked_evaluation_nodes,
            count=len(positives) * NEGATIVE_TO_POSITIVE_RATIO,
            seed=embedding_seed + 10_000 + fold,
        )
        positive_set = set(positives)
        negative_set = set(negatives)
        positive_train_overlap = len(positive_set & train_edges)
        negative_forbidden_overlap = len(negative_set & all_forbidden)
        positive_negative_overlap = len(positive_set & negative_set)
        positive_reuse_within_repeat = len(positive_set & used_positive_pairs)
        negative_reuse_within_repeat = len(negative_set & used_negative_pairs)
        self_pair_count = sum(left == right for left, right in positive_set | negative_set)
        if (
            positive_train_overlap or negative_forbidden_overlap or positive_negative_overlap
            or positive_reuse_within_repeat or negative_reuse_within_repeat or self_pair_count
        ):
            raise RuntimeError(
                "Link-prediction leakage/integrity failure: "
                f"positive_train_overlap={positive_train_overlap}, "
                f"negative_forbidden_overlap={negative_forbidden_overlap}, "
                f"positive_negative_overlap={positive_negative_overlap}, "
                f"positive_reuse={positive_reuse_within_repeat}, negative_reuse={negative_reuse_within_repeat}, "
                f"self_pairs={self_pair_count}"
            )
        used_positive_pairs.update(positive_set)
        used_negative_pairs.update(negative_set)
        link_evaluation_diagnostic_rows.append({
            "repeat": repeat + 1,
            "fold": fold,
            "evaluation_id": f"R{repeat + 1}F{fold}",
            "fold_documents": len(doc_indices),
            "positive_edges": len(positives),
            "negative_edges": len(negatives),
            "positive_pair_sha256": hash_pair_set(positives),
            "negative_pair_sha256": hash_pair_set(negatives),
            "positive_train_overlap": positive_train_overlap,
            "negative_forbidden_overlap": negative_forbidden_overlap,
            "positive_negative_overlap": positive_negative_overlap,
            "positive_reuse_within_repeat": positive_reuse_within_repeat,
            "negative_reuse_within_repeat": negative_reuse_within_repeat,
            "self_pair_count": self_pair_count,
        })
        pairs = positives + negatives
        labels = np.asarray([1] * len(positives) + [0] * len(negatives), dtype=int)
        score_sets: dict[str, list[float]] = {
            f"Topic-K{k}": [] for k in GRAPH_TOPIC_K_SENSITIVITY
        }
        score_sets.update({
            "Node2Vec": [], "DeepWalk": [], "Jaccard": [],
            "Adamic-Adar": [], "Preferential-Attachment": [], "Random": [],
        })
        random_scores = np.random.default_rng(embedding_seed + 20_000 + fold).random(len(pairs))
        for pair_index, (left, right) in enumerate(pairs):
            for k, vectors in entity_topic_vectors_by_k.items():
                score_sets[f"Topic-K{k}"].append(float(np.dot(vectors[left], vectors[right])))
            score_sets["Node2Vec"].append(cosine_score(node2vec_embeddings[left], node2vec_embeddings[right]))
            score_sets["DeepWalk"].append(cosine_score(deepwalk_embeddings[left], deepwalk_embeddings[right]))
            left_neighbors = set(evaluation_graph.neighbors(left))
            right_neighbors = set(evaluation_graph.neighbors(right))
            union = left_neighbors | right_neighbors
            score_sets["Jaccard"].append(len(left_neighbors & right_neighbors) / len(union) if union else 0.0)
            score_sets["Adamic-Adar"].append(adamic_adar_score(evaluation_graph, left, right))
            score_sets["Preferential-Attachment"].append(float(evaluation_graph.degree(left) * evaluation_graph.degree(right)))
            score_sets["Random"].append(float(random_scores[pair_index]))
        for method, scores in score_sets.items():
            link_rows.append({
                "repeat": repeat + 1,
                "fold": fold,
                "evaluation_id": f"R{repeat + 1}F{fold}",
                "method": method,
                "roc_auc": float(roc_auc_score(labels, scores)),
                "average_precision": float(average_precision_score(labels, scores)),
                "positive_edges": len(positives),
                "negative_edges": len(negatives),
                "evaluation_nodes": evaluation_graph.number_of_nodes(),
                "training_edges": evaluation_graph.number_of_edges(),
                "positive_train_overlap": positive_train_overlap,
                "negative_forbidden_overlap": negative_forbidden_overlap,
                "positive_negative_overlap": positive_negative_overlap,
                "positive_reuse_within_repeat": positive_reuse_within_repeat,
                "negative_reuse_within_repeat": negative_reuse_within_repeat,
                "self_pair_count": self_pair_count,
            })

link_folds = pd.DataFrame(link_rows)
link_fold_assignments = pd.DataFrame(link_fold_assignment_rows)
link_evaluation_diagnostics = pd.DataFrame(link_evaluation_diagnostic_rows)
expected_link_methods = [
    "Topic-K100", "Topic-K200", "Topic-K300",
    "Node2Vec", "DeepWalk", "Jaccard", "Adamic-Adar",
    "Preferential-Attachment", "Random",
]
expected_link_rows = LINK_REPEATS * LINK_FOLDS * len(expected_link_methods)
if len(link_folds) != expected_link_rows:
    raise RuntimeError(f"Expected {expected_link_rows} link rows, obtained {len(link_folds)}.")
if set(link_folds["method"]) != set(expected_link_methods):
    raise RuntimeError(f"Unexpected link methods: {sorted(link_folds['method'].unique())}")
if not np.isfinite(link_folds[["roc_auc", "average_precision"]].to_numpy(dtype=float)).all():
    raise RuntimeError("Non-finite link-prediction metrics detected.")
if link_folds[["positive_train_overlap", "negative_forbidden_overlap", "positive_negative_overlap", "positive_reuse_within_repeat", "negative_reuse_within_repeat", "self_pair_count"]].to_numpy().sum() != 0:
    raise RuntimeError("Link-prediction leakage diagnostics are non-zero.")

link_repeat_means = (
    link_folds.groupby(["repeat", "method"], as_index=False)[["roc_auc", "average_precision"]]
    .mean()
    .sort_values(["repeat", "method"])
    .reset_index(drop=True)
)

link_summary_rows: list[dict[str, Any]] = []
for method_index, method in enumerate(expected_link_methods):
    fold_group = link_folds[link_folds["method"] == method].copy()
    repeat_group = link_repeat_means[link_repeat_means["method"] == method].copy()
    if len(fold_group) != LINK_REPEATS * LINK_FOLDS or len(repeat_group) != LINK_REPEATS:
        raise RuntimeError(
            f"Method {method} has {len(fold_group)} fold evaluations and {len(repeat_group)} repeat means; "
            f"expected {LINK_REPEATS * LINK_FOLDS} and {LINK_REPEATS}."
        )
    auc_low, auc_high = bootstrap_mean_ci(
        repeat_group["roc_auc"], seed=RANDOM_SEED + 300_000 + method_index
    )
    ap_low, ap_high = bootstrap_mean_ci(
        repeat_group["average_precision"], seed=RANDOM_SEED + 310_000 + method_index
    )
    link_summary_rows.append({
        "method": method,
        "fold_evaluations": len(fold_group),
        "independent_repeat_blocks": len(repeat_group),
        "repeats": LINK_REPEATS,
        "folds_per_repeat": LINK_FOLDS,
        "roc_auc_mean": repeat_group["roc_auc"].mean(),
        "roc_auc_repeat_sd": repeat_group["roc_auc"].std(ddof=1),
        "roc_auc_fold_sd_descriptive": fold_group["roc_auc"].std(ddof=1),
        "roc_auc_repeat_bootstrap_ci_low": auc_low,
        "roc_auc_repeat_bootstrap_ci_high": auc_high,
        "average_precision_mean": repeat_group["average_precision"].mean(),
        "average_precision_repeat_sd": repeat_group["average_precision"].std(ddof=1),
        "average_precision_fold_sd_descriptive": fold_group["average_precision"].std(ddof=1),
        "average_precision_repeat_bootstrap_ci_low": ap_low,
        "average_precision_repeat_bootstrap_ci_high": ap_high,
        "bootstrap_unit": "repeat mean",
        "bootstrap_resamples": BOOTSTRAP_RESAMPLES,
    })
link_summary = pd.DataFrame(link_summary_rows).sort_values("roc_auc_mean", ascending=False).reset_index(drop=True)

# Inferential tests use five repeat-level means. Folds within a repeat are
# cross-validation components, not independent inferential observations.
link_friedman_rows: list[dict[str, Any]] = []
link_pairwise_rows: list[dict[str, Any]] = []
for metric_index, metric in enumerate(("roc_auc", "average_precision")):
    pivot = (
        link_repeat_means.pivot(index="repeat", columns="method", values=metric)
        .reindex(columns=expected_link_methods)
        .dropna()
    )
    if len(pivot) != LINK_REPEATS:
        raise RuntimeError(f"Incomplete repeat-level link blocks for {metric}: {len(pivot)}")
    statistic, p_value = friedmanchisquare(*[pivot[method].to_numpy(dtype=float) for method in expected_link_methods])
    link_friedman_rows.append({
        "metric": metric,
        "block_unit": "repeat mean across five document folds",
        "blocks": len(pivot),
        "methods": ", ".join(expected_link_methods),
        "friedman_chi_square": float(statistic),
        "raw_p": float(p_value),
        "kendalls_w": float(statistic / (len(pivot) * (len(expected_link_methods) - 1))),
        "alpha": ALPHA,
        "significant_0_05": bool(p_value < ALPHA),
        "inference_scope": "Exploratory repeat-level comparison; only five repeat blocks are available.",
    })

    temporary: list[dict[str, Any]] = []
    pivot_reset = pivot.reset_index()
    for pair_index, (left, right) in enumerate(combinations(expected_link_methods, 2)):
        differences = pivot_reset[left] - pivot_reset[right]
        try:
            statistic_pair, raw_p = wilcoxon(
                pivot_reset[left],
                pivot_reset[right],
                zero_method="wilcox",
                alternative="two-sided",
                method="auto",
            )
        except ValueError:
            statistic_pair, raw_p = 0.0, 1.0
        ci_low, ci_high = bootstrap_mean_ci(
            differences, seed=RANDOM_SEED + 320_000 + 1000 * metric_index + pair_index
        )
        non_ties = differences[differences != 0]
        sign_p = (
            binomtest(int((non_ties > 0).sum()), n=len(non_ties), p=0.5, alternative="two-sided").pvalue
            if len(non_ties) else 1.0
        )
        temporary.append({
            "metric": metric,
            "method_a": left,
            "method_b": right,
            "paired_repeats": len(differences),
            "mean_difference_a_minus_b": float(differences.mean()),
            "repeat_bootstrap_95_ci_low": ci_low,
            "repeat_bootstrap_95_ci_high": ci_high,
            "bootstrap_resamples": BOOTSTRAP_RESAMPLES,
            "a_wins": int((differences > 0).sum()),
            "ties": int((differences == 0).sum()),
            "a_losses": int((differences < 0).sum()),
            "wilcoxon_statistic": float(statistic_pair),
            "wilcoxon_raw_p": float(raw_p),
            "sign_test_raw_p": float(sign_p),
            "rank_biserial": rank_biserial_from_differences(differences),
            "alpha": ALPHA,
            "inference_scope": "Exploratory; inference uses five repeat means, while fold-level rows remain descriptive.",
        })
    wilcoxon_adjusted = holm_adjust([row["wilcoxon_raw_p"] for row in temporary])
    sign_adjusted = holm_adjust([row["sign_test_raw_p"] for row in temporary])
    for row, adjusted_w, adjusted_sign in zip(temporary, wilcoxon_adjusted, sign_adjusted):
        row["wilcoxon_holm_p"] = adjusted_w
        row["sign_test_holm_p"] = adjusted_sign
        row["significant_wilcoxon_holm_0_05"] = bool(adjusted_w < ALPHA)
        row["significant_sign_test_holm_0_05"] = bool(adjusted_sign < ALPHA)
        link_pairwise_rows.append(row)

link_friedman_results = pd.DataFrame(link_friedman_rows)
link_pairwise_tests = pd.DataFrame(link_pairwise_rows)
main_method = f"Topic-K{GRAPH_TOPIC_K_MAIN}"
main_vs_baselines = link_pairwise_tests[
    (link_pairwise_tests["method_a"] == main_method) | (link_pairwise_tests["method_b"] == main_method)
].copy()

print("\nAll repeated-fold link-prediction results")
display(link_folds)
print("\nLink-prediction evaluation diagnostics and pair-set hashes")
display(link_evaluation_diagnostics)
print(f"\nExact fold assignment evidence contains {len(link_fold_assignments):,} rows and is saved in the final JSON evidence.")
display(link_fold_assignments.head(200))
print("\nLink-prediction method summaries based on repeat means")
display(link_summary)
print("\nLink-prediction Friedman tests")
display(link_friedman_results)
print("\nAll pairwise Wilcoxon tests with Holm correction")
display(link_pairwise_tests)
print(f"\nPredeclared {main_method} comparisons")
display(main_vs_baselines)

# =============================================================================
# 11. CLAIM-READY SUMMARY, INTEGRITY CHECKS, AND TWO FINAL FILES
# =============================================================================


heading("8. Claim-ready summary and integrity checks")


def extract_pairwise_result(
    frame: pd.DataFrame,
    metric: str,
    item_a: str,
    item_b: str,
    left_column: str,
    right_column: str,
    difference_column: str,
    low_column: str,
    high_column: str,
    p_column: str,
) -> dict[str, Any] | None:
    subset = frame[frame["metric"] == metric]
    mask = (
        ((subset[left_column] == item_a) & (subset[right_column] == item_b))
        | ((subset[left_column] == item_b) & (subset[right_column] == item_a))
    )
    if not mask.any():
        return None
    row = subset.loc[mask].iloc[0]
    orientation = 1.0 if row[left_column] == item_a else -1.0
    low = float(row[low_column])
    high = float(row[high_column])
    if orientation < 0:
        low, high = -high, -low
    return {
        "item_a": item_a,
        "item_b": item_b,
        "mean_difference_a_minus_b": orientation * float(row[difference_column]),
        "ci_low": low,
        "ci_high": high,
        "adjusted_p": float(row[p_column]),
        "significant": bool(float(row[p_column]) < ALPHA),
        "rank_biserial_a_minus_b": orientation * float(row["rank_biserial"]),
    }


best_by_model_display = best_configs[[
    "model", "model_family", "benchmark_role", "encoder", "k",
    "c_v_mean", "c_v_sd", "c_v_bootstrap_ci_low", "c_v_bootstrap_ci_high",
    "c_npmi_mean", "c_npmi_sd", "c_npmi_bootstrap_ci_low", "c_npmi_bootstrap_ci_high",
    "diversity_mean", "diversity_sd", "distinctness_mean", "distinctness_sd",
    "stability", "valid_topic_fraction_mean", "reference_match_rate_mean",
    "training_seconds_mean",
]].copy()

common_k_display = common_k_results.copy()
highest_core = core_best_configs.sort_values("c_v_mean", ascending=False).iloc[0]
second_core = core_best_configs.sort_values("c_v_mean", ascending=False).iloc[1]
common_k_winner = common_k_results.sort_values("c_v_mean", ascending=False).iloc[0]

# Inferential tests concern average paired performance across the fixed
# statistical grid; they are never used to validate model-specific maxima.
grid_mean_cv = (
    statistical_core_runs.groupby("model", as_index=False)["c_v"].mean()
    .sort_values("c_v", ascending=False)
    .reset_index(drop=True)
)
grid_first, grid_second = grid_mean_cv.iloc[0], grid_mean_cv.iloc[1]
grid_cv_pair = extract_pairwise_result(
    pairwise_topic_results,
    metric="c_v",
    item_a=str(grid_first["model"]),
    item_b=str(grid_second["model"]),
    left_column="model_a",
    right_column="model_b",
    difference_column="mean_difference_a_minus_b",
    low_column="cluster_bootstrap_95_ci_low",
    high_column="cluster_bootstrap_95_ci_high",
    p_column="holm_p",
)

main_link_row = link_summary[link_summary["method"] == main_method].iloc[0]
strongest_baseline = (
    link_summary[~link_summary["method"].str.startswith("Topic-K")]
    .sort_values("roc_auc_mean", ascending=False)
    .iloc[0]
)
link_auc_pair = extract_pairwise_result(
    link_pairwise_tests,
    metric="roc_auc",
    item_a=main_method,
    item_b=str(strongest_baseline["method"]),
    left_column="method_a",
    right_column="method_b",
    difference_column="mean_difference_a_minus_b",
    low_column="repeat_bootstrap_95_ci_low",
    high_column="repeat_bootstrap_95_ci_high",
    p_column="wilcoxon_holm_p",
)

encoder_cv_row = bertopic_encoder_tests[bertopic_encoder_tests["metric"] == "c_v"].iloc[0]

claim_rows: list[dict[str, Any]] = [
    {
        "area": "dataset",
        "statement_type": "observation",
        "claim_ready_statement": (
            f"The complete source file contained {raw_row_count:,} rows. After language eligibility screening and "
            f"text-hash deduplication, {len(unique_candidate_meta):,} unique Persian-rich documents were eligible."
        ),
        "statistically_validated": None,
        "scope": "Descriptive source-corpus audit.",
    },
    {
        "area": "sampling",
        "statement_type": "methodological fact",
        "claim_ready_statement": (
            f"A proportional raw-length-stratified random sample of {len(sample):,} documents was drawn from the full "
            "eligible corpus; the sample was not selected as the longest documents."
        ),
        "statistically_validated": None,
        "scope": "Reproducible sampling procedure conditional on seed 42.",
    },
    {
        "area": "topic modeling",
        "statement_type": "observation",
        "claim_ready_statement": (
            f"At the predeclared common topic count K={PRIMARY_COMMON_K}, the four model families were compared under "
            "the same held-out corpus and top-word protocol; this matched-K table is the primary model comparison."
        ),
        "statistically_validated": False,
        "scope": "Primary matched-K descriptive comparison; model-specific optima are secondary sensitivity analyses.",
    },
    {
        "area": "topic modeling",
        "statement_type": "observation",
        "claim_ready_statement": (
            f"At K={PRIMARY_COMMON_K}, {common_k_winner['model']} had the highest mean C_v "
            f"({common_k_winner['c_v_mean']:.4f}); NPMI, diversity, distinctness, and stability are reported beside "
            "coherence so this matched-K result is not interpreted as universal dominance."
        ),
        "statistically_validated": False,
        "scope": "Primary common-K descriptive result with explicit multi-metric qualification.",
    },
    {
        "area": "topic modeling",
        "statement_type": "observation",
        "claim_ready_statement": (
            f"When each core model was allowed to choose its own coherence-maximizing K, "
            f"{highest_core['model']} achieved the highest mean C_v ({highest_core['c_v_mean']:.4f}) "
            f"at K={int(highest_core['k'])}. This is a metric-specific optimum, not an overall winner; "
            f"diversity, distinctness, NPMI, and stability must be interpreted jointly."
        ),
        "statistically_validated": False,
        "scope": "Descriptive metric-specific selection; no composite quality score is used.",
    },
    {
        "area": "topic modeling",
        "statement_type": "exploratory inference",
        "claim_ready_statement": (
            f"Across the {expected_statistical_blocks} matched K × seed configurations in the fixed statistical grid, "
            f"{grid_first['model']} had the highest mean C_v ({grid_first['c_v']:.4f}); its mean difference from "
            f"{grid_second['model']} was {grid_cv_pair['mean_difference_a_minus_b']:.4f} "
            f"(K-cluster bootstrap 95% CI {grid_cv_pair['ci_low']:.4f} to {grid_cv_pair['ci_high']:.4f}; "
            f"Holm-adjusted Wilcoxon p={grid_cv_pair['adjusted_p']:.4g})."
            if grid_cv_pair else "The planned paired C_v comparison was unavailable."
        ),
        "statistically_validated": grid_cv_pair["significant"] if grid_cv_pair else False,
        "scope": "Exploratory paired inference across the fixed statistical K grid; model-specific maxima are descriptive only.",
    },
    {
        "area": "BERTopic encoder sensitivity",
        "statement_type": "exploratory inference",
        "claim_ready_statement": (
            f"Under fixed BERTopic settings, mean-pooled ParsBERT minus multilingual MiniLM produced a mean C_v "
            f"difference of {encoder_cv_row['mean_difference_a_minus_b']:.4f} "
            f"(K-cluster bootstrap 95% CI {encoder_cv_row['cluster_bootstrap_95_ci_low']:.4f} to "
            f"{encoder_cv_row['cluster_bootstrap_95_ci_high']:.4f}; Holm-adjusted p={encoder_cv_row['holm_p']:.4g})."
        ),
        "statistically_validated": bool(encoder_cv_row["significant_holm_0_05"]),
        "scope": "Conditional on mean pooling, truncation length, UMAP, KMeans, and c-TF-IDF parameters.",
    },
    {
        "area": "NER",
        "statement_type": "observation",
        "claim_ready_statement": (
            f"Stanza extracted {len(train_mentions):,} accepted training mentions and {len(test_mentions):,} accepted "
            f"link-test mentions from {NER_TRAIN_DOCS:,} training and {NER_TEST_DOCS:,} link-test documents; document-level error rates were "
            f"{train_ner_diagnostics['error_rate']:.3%} and {test_ner_diagnostics['error_rate']:.3%}, respectively."
        ),
        "statistically_validated": None,
        "scope": "Typed normalized surface forms; no entity linking or canonical disambiguation.",
    },
    {
        "area": "entity graph",
        "statement_type": "observation",
        "claim_ready_statement": (
            f"The training-only graph retained {train_graph.number_of_nodes():,} typed surface-form nodes and "
            f"{train_graph.number_of_edges():,} document co-occurrence edges."
        ),
        "statistically_validated": None,
        "scope": "Entity association graph, not a multi-relational knowledge graph.",
    },
    {
        "area": "link prediction",
        "statement_type": "observation",
        "claim_ready_statement": (
            f"The predeclared {main_method} method achieved mean ROC-AUC {main_link_row['roc_auc_mean']:.4f} "
            f"and mean average precision {main_link_row['average_precision_mean']:.4f}; means and uncertainty were "
            f"computed from {LINK_REPEATS} repeat-level blocks, each averaging {LINK_FOLDS} document folds."
        ),
        "statistically_validated": False,
        "scope": "Descriptive repeated cross-validation result.",
    },
    {
        "area": "link prediction",
        "statement_type": "exploratory inference",
        "claim_ready_statement": (
            f"Relative to the strongest non-topic baseline ({strongest_baseline['method']}), {main_method} had a mean "
            f"ROC-AUC difference of {link_auc_pair['mean_difference_a_minus_b']:.4f} "
            f"(repeat-level bootstrap 95% CI {link_auc_pair['ci_low']:.4f} to {link_auc_pair['ci_high']:.4f}; "
            f"Holm-adjusted Wilcoxon p={link_auc_pair['adjusted_p']:.4g})."
            if link_auc_pair else "The planned link-prediction comparison was unavailable."
        ),
        "statistically_validated": link_auc_pair["significant"] if link_auc_pair else False,
        "scope": "Exploratory repeat-level inference based on five repeat means; all evidence derives from Persian Wikipedia.",
    },
]
claim_ready_summary = pd.DataFrame(claim_rows)

limitations = pd.DataFrame([
    {
        "limitation": "Hash-based deduplication",
        "statement": "Corpus-scale deduplication uses pandas' stable 64-bit text hash for tractability. Collisions are extremely unlikely but are not cryptographically impossible; selected-document provenance retains the hash for audit.",
    },
    {
        "limitation": "Shared-source evaluation",
        "statement": "Preprocessing, topics, named entities, graph edges, and held-out links originate from the same Wikipedia source, although topic validation and link testing use mutually exclusive documents; domain alignment may still increase compatibility.",
    },
    {
        "limitation": "Domain specificity",
        "statement": "Results describe Persian Wikipedia and do not establish population-level generalization to social media, news, conversational text, or specialized domains.",
    },
    {
        "limitation": "CTM training budget",
        "statement": f"CTM uses the official CombinedTM.fit loop for ten epochs and the shared {len(shared_vocabulary):,}-term vocabulary; conclusions remain conditional on this computational budget.",
    },
    {
        "limitation": "ParsBERT pooling",
        "statement": "ParsBERT is a masked-language-model checkpoint converted to document embeddings through mean pooling; it is not a Persian sentence-similarity model fine-tuned for semantic clustering.",
    },
    {
        "limitation": "Encoder/parameter conditionality",
        "statement": "BERTopic conclusions are conditional on the selected encoders, 256-token truncation, UMAP, KMeans, Persian whitespace tokenization, and the official ClassTfidfTransformer configuration.",
    },
    {
        "limitation": "No human validation",
        "statement": "This pipeline contains no human topic-interpretability or edge-validity annotations and makes no inter-rater-reliability claim.",
    },
    {
        "limitation": "Three-seed uncertainty",
        "statement": "Topic-model means and seed-bootstrap intervals are based on only three predeclared random seeds; they characterize initialization sensitivity but are not population confidence intervals.",
    },
    {
        "limitation": "Repeated-fold inference",
        "statement": "Repeated cross-validation folds overlap; Wilcoxon tests and bootstrap intervals are exploratory rather than independent population-level inference.",
    },
    {
        "limitation": "NER truncation",
        "statement": f"NER processes at most the first {NER_MAX_CHARS_PER_DOC:,} characters of each document; entities appearing later in long documents are not observed.",
    },
    {
        "limitation": "Head-entity graph",
        "statement": f"The graph retains the {MAX_GRAPH_NODES:,} most frequent typed nodes, at most {MAX_ENTITIES_PER_DOCUMENT} retained entities per document, and the link evaluation uses the {LINK_PREDICTION_NODES:,} highest-document-frequency nodes; conclusions concern the graph head rather than the full entity tail.",
    },
    {
        "limitation": "Near-duplicate documents",
        "statement": "Exact text-hash duplicates are removed, but semantic or near-duplicate pages and revisions are not explicitly clustered; residual similarity may remain across train and test.",
    },
    {
        "limitation": "Surface-form entities",
        "statement": "Nodes are typed normalized surface forms. Homonyms are not disambiguated and aliases are not linked to canonical entities.",
    },
])

# Integrity checks that must pass before evidence files are finalized.
top_longest_rows = set(
    unique_candidate_meta.nlargest(WORKING_SAMPLE_SIZE, "raw_chars")["source_row"].astype(int)
)
selected_rows = set(sampled_meta["source_row"].astype(int))
population_stratum_proportions = unique_candidate_meta["raw_length_stratum"].value_counts(normalize=True).sort_index()
sample_stratum_proportions = sampled_meta["raw_length_stratum"].value_counts(normalize=True).sort_index()
max_stratum_proportion_difference = float(
    (population_stratum_proportions - sample_stratum_proportions).abs().max()
)
pre_output_checks = {
    "full_dataset_scanned_raw_row_count_positive": raw_row_count > 0,
    "full_dataset_second_pass_completed": row_offset == raw_row_count,
    "sampling_is_random_stratified_not_top_n_longest": selected_rows != top_longest_rows,
    "sampling_covers_all_populated_raw_length_strata": set(sampled_meta["raw_length_stratum"]) == set(unique_candidate_meta["raw_length_stratum"]),
    "sampling_preserves_stratum_proportions_within_0_5_percent": max_stratum_proportion_difference <= 0.005,
    "working_sample_size_50000": len(sample) == WORKING_SAMPLE_SIZE,
    "train_size_expected": len(train) == TRAIN_SIZE,
    "topic_validation_size_expected": len(topic_validation) == TOPIC_VALIDATION_SIZE,
    "link_test_size_expected": len(test) == LINK_TEST_SIZE,
    "all_analysis_role_overlaps_zero": not any(split_overlaps.values()),
    "core_four_models_present": set(core_runs["model"]) == {"LDA", "NMF", "CTM", "BERTopic"},
    "core_topic_runs_complete": len(core_runs) == expected_core_runs,
    "parsbert_sensitivity_runs_complete": len(all_runs[all_runs["model"] == "BERTopic-ParsBERT"]) == expected_parsbert_extra_runs,
    "total_topic_runs_complete": len(all_runs) == expected_total_runs,
    "all_core_metrics_finite": bool(np.isfinite(all_runs[core_metric_columns].to_numpy(dtype=float)).all()),
    "bertopic_two_encoders_present": set(bertopic_encoder_runs["encoder"].dropna()) == {"multilingual-MiniLM", "ParsBERT-mean-pooling"},
    "bertopic_all_runs_use_ctfidf": bool(bertopic_encoder_runs["c_tfidf_used"].fillna(False).all()),
    "bertopic_all_coherence_values_valid": bool(
        np.isfinite(bertopic_encoder_runs[["c_v", "c_npmi"]].to_numpy(dtype=float)).all()
        and (bertopic_encoder_runs["valid_topic_fraction"] >= 0.95).all()
    ),
    "ctm_uses_configured_training_documents": bool((core_runs.loc[core_runs["model"] == "CTM", "training_documents"] == CTM_TRAIN_DOCS).all()),
    "ctm_uses_configured_epochs": bool((core_runs.loc[core_runs["model"] == "CTM", "epochs"] == CTM_EPOCHS).all()),
    "ctm_uses_official_fit_loop": bool((core_runs.loc[core_runs["model"] == "CTM", "training_implementation"] == "official CombinedTM.fit").all()),
    "shared_vocabulary_size_within_cap": 100 <= len(shared_vocabulary) <= SHARED_VOCAB_SIZE,
    "all_core_models_record_shared_vocabulary": bool(
        all_runs.loc[all_runs["benchmark_role"] == "core", "shared_vocabulary_size"].eq(len(shared_vocabulary)).all()
    ),
    "ctm_vocabulary_matches_shared_vocabulary": bool((core_runs.loc[core_runs["model"] == "CTM", "controlled_bow_vocabulary"] == len(shared_vocabulary)).all()),
    "topic_friedman_tests_present": len(friedman_results) >= 5,
    "topic_pairwise_tests_holm_complete": bool(len(pairwise_topic_results) > 0 and pairwise_topic_results["holm_p"].notna().all()),
    "bootstrap_resamples_5000": BOOTSTRAP_RESAMPLES == 5_000,
    "statistical_grid_is_subset_of_descriptive_grid": set(STATISTICAL_TOPIC_COUNTS).issubset(TOPIC_COUNTS),
    "statistical_blocks_dynamic_and_complete": len(statistical_core_runs) == 4 * expected_statistical_blocks,
    "model_revisions_are_commit_like": all(bool(re.fullmatch(r"[0-9a-fA-F]{7,64}", revision)) for revision in MODEL_REVISIONS.values()),
    "stanza_resource_hashes_present": bool(stanza_resource_hashes),
    "package_versions_match_reference_environment": not PACKAGE_VERSION_MISMATCHES,
    "preprocessing_ablation_4x3_complete": len(ablation_runs) == 4 * len(SEEDS),
    "preprocessing_ablation_metrics_finite": bool(np.isfinite(ablation_runs[["c_v", "c_npmi", "diversity", "distinctness"]].to_numpy(dtype=float)).all()),
    "preprocessing_ablation_statistics_complete": len(ablation_friedman_results) == 4 and len(ablation_pairwise_tests) == 4 * math.comb(4, 2),
    "ner_train_documents_configured": train_ner_diagnostics["documents_processed"] == NER_TRAIN_DOCS,
    "ner_link_test_documents_configured": test_ner_diagnostics["documents_processed"] == NER_TEST_DOCS,
    "ner_train_error_rate_below_1_percent": train_ner_diagnostics["error_rate"] < 0.01,
    "ner_test_error_rate_below_1_percent": test_ner_diagnostics["error_rate"] < 0.01,
    "ner_no_fabricated_or_fallback_entities": not train_ner_diagnostics["dummy_or_fallback_entities_used"] and not test_ner_diagnostics["dummy_or_fallback_entities_used"],
    "ner_only_six_predeclared_types": set(train_mentions["entity_type"]) == set(ALLOWED_ENTITY_TYPES) and set(test_mentions["entity_type"]) == set(ALLOWED_ENTITY_TYPES),
    "graph_constructed_from_training_entities_only": True,
    "graph_node_cap_respected": train_graph.number_of_nodes() <= MAX_GRAPH_NODES,
    "graph_has_1000_evaluation_nodes": evaluation_graph.number_of_nodes() == LINK_PREDICTION_NODES,
    "graph_topic_sensitivity_k100_200_300_complete": set(entity_topic_vectors_by_k) == set(GRAPH_TOPIC_K_SENSITIVITY),
    "link_prediction_expected_evaluations_per_method": bool((link_folds.groupby("method").size() == LINK_REPEATS * LINK_FOLDS).all()),
    "link_prediction_repeat_means_complete": bool((link_repeat_means.groupby("method").size() == LINK_REPEATS).all()),
    "link_fold_assignments_complete": len(link_fold_assignments) == LINK_TEST_SIZE * LINK_REPEATS,
    "link_evaluation_diagnostics_complete": len(link_evaluation_diagnostics) == LINK_REPEATS * LINK_FOLDS,
    "link_pair_hashes_present": bool(
        link_evaluation_diagnostics[["positive_pair_sha256", "negative_pair_sha256"]].apply(
            lambda column: column.astype(str).str.fullmatch(r"[0-9a-f]{64}").all()
        ).all()
    ),
    "link_prediction_all_9_methods_present": set(link_folds["method"]) == set(expected_link_methods),
    "link_prediction_metrics_finite": bool(np.isfinite(link_folds[["roc_auc", "average_precision"]].to_numpy(dtype=float)).all()),
    "link_prediction_no_positive_train_overlap": int(link_folds["positive_train_overlap"].sum()) == 0,
    "link_prediction_no_forbidden_negatives": int(link_folds["negative_forbidden_overlap"].sum()) == 0,
    "link_prediction_no_self_class_or_fold_reuse": int(link_folds[["positive_negative_overlap", "positive_reuse_within_repeat", "negative_reuse_within_repeat", "self_pair_count"]].to_numpy().sum()) == 0,
    "link_friedman_tests_present": len(link_friedman_results) == 2,
    "link_pairwise_holm_tests_complete": bool(len(link_pairwise_tests) == 2 * math.comb(len(expected_link_methods), 2) and link_pairwise_tests["wilcoxon_holm_p"].notna().all()),
}
failed_pre_output = [name for name, passed in pre_output_checks.items() if not passed]
if failed_pre_output:
    raise RuntimeError(f"Pre-output integrity checks failed: {failed_pre_output}")

integrity_checks = dict(pre_output_checks)
integrity_checks.update({
    "json_file_created_and_valid": False,
    "markdown_report_created_and_valid": False,
    "output_directory_contains_only_two_public_files": False,
})

# Dataset hashing is intentionally performed once and recorded in the protocol.
log("Computing SHA-256 for the source dataset...")
dataset_sha256 = sha256_file(DATASET_FILE)


def build_protocol() -> dict[str, Any]:
    return {
        "run_note": RUN_NOTE,
        "run_started_utc": datetime.fromtimestamp(START_TIME, tz=timezone.utc).isoformat(),
        "run_finished_utc": datetime.now(timezone.utc).isoformat(),
        "elapsed_hours": (time.time() - START_TIME) / 3600,
        "alpha": ALPHA,
        "bootstrap_resamples": BOOTSTRAP_RESAMPLES,
        "dataset": {
            "public_source": "Kaggle dataset amirpourmand/fa-wikipedia",
            "local_file_name": DATASET_FILE.name,
            "file_size_bytes": DATASET_FILE.stat().st_size,
            "sha256": dataset_sha256,
            "text_column": TEXT_COLUMN,
            "title_column": TITLE_COLUMN,
            "raw_rows_scanned": raw_row_count,
        },
        "sampling": {
            "method": "full-corpus scan, stable uint64 text-hash deduplication, proportional raw-length-stratified random sampling",
            "deduplication_hash": "pandas.util.hash_pandas_object uint64",
            "not_top_n_longest": True,
            "raw_length_quantile_edges": raw_strata_edges.tolist(),
            "clean_token_length_quantile_edges": clean_strata_edges.tolist(),
            "working_sample_size": WORKING_SAMPLE_SIZE,
            "train_size": TRAIN_SIZE,
            "topic_validation_size": TOPIC_VALIDATION_SIZE,
            "link_test_size": LINK_TEST_SIZE,
            "random_seed": RANDOM_SEED,
            "role_separation": "topic_validation is used for coherence/NPMI and CTM inference; link_test is reserved for NER/link prediction",
            "maximum_absolute_stratum_proportion_difference": max_stratum_proportion_difference,
            "sample_provenance_rows_recorded": len(sample_provenance),
        },
        "topic_benchmark": {
            "core_models": ["LDA", "NMF", "CTM", "BERTopic"],
            "core_runs": expected_core_runs,
            "bertopic_encoder_sensitivity_extra_runs": expected_parsbert_extra_runs,
            "total_runs": expected_total_runs,
            "topic_counts_descriptive": TOPIC_COUNTS,
            "topic_counts_statistical": STATISTICAL_TOPIC_COUNTS,
            "seeds": SEEDS,
            "held_out_reference_documents": len(reference_texts),
            "top_n_words": TOP_N_WORDS,
            "shared_training_vocabulary": {
                "size": len(shared_vocabulary),
                "min_df": SHARED_VOCAB_MIN_DF,
                "max_df": SHARED_VOCAB_MAX_DF,
                "used_by": ["LDA", "NMF", "CTM", "BERTopic"],
            },
            "candidate_words_before_reference_matching": TOPIC_CANDIDATE_WORDS,
            "metrics": ["C_v", "NPMI", "diversity", "distinctness", "stability", "runtime", "reference coverage"],
            "composite_quality_score_used": False,
            "lda": {
                "passes": LDA_PASSES,
                "iterations": LDA_ITERATIONS,
                "alpha": LDA_ALPHA,
                "eta": LDA_ETA,
            },
            "nmf": {
                "init": NMF_INIT,
                "solver": "mu",
                "max_iter": NMF_MAX_ITER,
                "tol": NMF_TOL,
            },
            "ctm": {
                "architecture": "CombinedTM",
                "training_documents": CTM_TRAIN_DOCS,
                "test_documents": CTM_TEST_DOCS,
                "epochs": CTM_EPOCHS,
                "batch_size": CTM_BATCH_SIZE,
                "controlled_bow_max_features": CTM_MAX_FEATURES,
                "contextual_encoder": MULTILINGUAL_ENCODER_MODEL,
                "contextual_embeddings_l2_normalized": False,
                "training_implementation": "official CombinedTM.fit loop",
            },
            "bertopic": {
                "core_encoder": MULTILINGUAL_ENCODER_MODEL,
                "sensitivity_encoder": PARSBERT_ENCODER_MODEL,
                "parsbert_pooling": "mean pooling added through SentenceTransformers",
                "max_sequence_length": 256,
                "clusterer": "KMeans",
                "kmeans_n_init": BERTOPIC_KMEANS_N_INIT,
                "kmeans_max_iter": BERTOPIC_KMEANS_MAX_ITER,
                "manual_topic_interface": "BaseEmbedder + BaseDimensionalityReduction + BaseCluster; labels passed through y",
                "ctfidf": "official BERTopic ClassTfidfTransformer(reduce_frequent_words=True)",
                "lexical_input": "clean Persian unigrams",
                "contextual_input": "normalized raw Persian text",
                "contextual_embeddings_l2_normalized": False,
            },
            "statistics": {
                "friedman": True,
                "pairwise_wilcoxon": True,
                "holm_bonferroni": True,
                "rank_biserial_effect_size": True,
                "bootstrap_ci": "5,000 resamples; K-cluster bootstrap for topic-model differences",
                "alpha": ALPHA,
            },
        },
        "preprocessing_ablation": {
            "training_documents": ABLATION_TRAIN_DOCS,
            "test_documents": ABLATION_TEST_DOCS,
            "k": ABLATION_K,
            "variants": ["full", "no_lemmatization", "no_stopword_removal", "normalization_tokenization_only"],
        },
        "ner": {
            "tool": "Stanza Persian tokenize,ner pipeline",
            "train_documents": NER_TRAIN_DOCS,
            "test_documents": NER_TEST_DOCS,
            "max_characters_per_document": NER_MAX_CHARS_PER_DOC,
            "accepted_types": ALLOWED_ENTITY_TYPES,
            "maximum_error_rate_exclusive": MAX_ACCEPTABLE_NER_ERROR_RATE,
            "dummy_fallback_allowed": False,
        },
        "graph": {
            "node_definition": "typed normalized surface form (surface, entity_type)",
            "source": "training entities only",
            "max_graph_nodes": MAX_GRAPH_NODES,
            "max_entities_per_document": MAX_ENTITIES_PER_DOCUMENT,
            "edge_weight": "training-document co-occurrence count",
            "topic_vector_k_sensitivity": GRAPH_TOPIC_K_SENSITIVITY,
            "topic_vector_aggregation": "mean training-document LDA distribution per entity, L2 normalized",
        },
        "link_prediction": {
            "evaluation_nodes": LINK_PREDICTION_NODES,
            "evaluation_node_selection": "highest training-document-frequency nodes within the retained graph",
            "positive_pairs_disjoint_within_repeat": True,
            "negative_pairs_disjoint_within_repeat": True,
            "folds": LINK_FOLDS,
            "repeats": LINK_REPEATS,
            "evaluations_per_method": LINK_FOLDS * LINK_REPEATS,
            "methods": expected_link_methods,
            "novel_positive_definition": "link-test-document co-occurrence absent from the training graph",
            "negative_definition": "degree-bin-matched pair absent from the training graph and every link-test positive set",
            "metrics": ["ROC-AUC", "average precision"],
            "node2vec": {"p": NODE2VEC_P, "q": NODE2VEC_Q},
            "deepwalk": {"p": 1.0, "q": 1.0},
            "statistics": {
                "friedman": True,
                "all_pairwise_wilcoxon": True,
                "holm_bonferroni": True,
                "rank_biserial_effect_size": True,
                "bootstrap_ci": "5,000-resample bootstrap over five repeat means; descriptive because the number of repeat blocks is limited",
                "alpha": ALPHA,
                "scope": "exploratory; inferential blocks are repeat means, not individual folds",
            },
        },
        "human_validation": {
            "performed": False,
            "statement": "No human ratings were supplied or fabricated. Deterministic unscored topic and NER audit templates are generated for optional later annotation.",
        },
        "environment": {
            "python": sys.version,
            "platform": platform.platform(),
            "processor": platform.processor(),
            "device": DEVICE,
            "torch_version": torch.__version__,
            "cuda_available": torch.cuda.is_available(),
            "cuda_version": torch.version.cuda,
            "gpu_name": torch.cuda.get_device_name(0) if torch.cuda.is_available() else None,
            "package_versions": PACKAGE_VERSIONS,
            "expected_package_versions": EXPECTED_PACKAGE_VERSIONS,
            "package_version_mismatches": PACKAGE_VERSION_MISMATCHES,
            "strict_package_versions": STRICT_PACKAGE_VERSIONS,
            "huggingface_model_revisions": MODEL_REVISIONS,
            "stanza_resource_file_sha256": stanza_resource_hashes,
            "executed_notebook_or_script_source_sha256": executed_source_sha256(),
        },
        "limitations": limitations.to_dict(orient="records"),
    }


def build_final_evidence() -> dict[str, Any]:
    return {
        "protocol": build_protocol(),
        "integrity_checks": integrity_checks,
        "null_and_provenance_audit": null_audit,
        "preprocessing_outcomes": pd.DataFrame(sorted(preprocessing_reason_counts.items()), columns=["status", "documents"]),
        "split_distribution": split_table,
        "sample_provenance_50000": sample_provenance,
        "token_length_summary": valid_sample["token_count"].describe(percentiles=[0.1, 0.25, 0.5, 0.75, 0.9, 0.95, 0.99]).reset_index().rename(columns={"index": "statistic", "token_count": "value"}),
        "topic_data_summary": topic_data_summary,
        "topic_model_runs_all": all_runs,
        "topic_model_core_runs": core_runs,
        "topic_model_aggregate": aggregate,
        "topic_model_core_aggregate": core_aggregate,
        "topic_model_primary_common_k": common_k_results,
        "topic_model_metric_optima": metric_optima,
        "topic_model_core_pareto_front": core_pareto_front,
        "topic_best_configurations": best_by_model_display,
        "representative_topics": representative_topics,
        "all_topic_words": all_topic_words,
        "topic_human_audit_template_unscored": topic_audit_template,
        "topic_friedman_tests": friedman_results,
        "topic_pairwise_tests": pairwise_topic_results,
        "bertopic_encoder_runs": bertopic_encoder_runs,
        "bertopic_encoder_aggregate": bertopic_encoder_aggregate,
        "bertopic_encoder_tests": bertopic_encoder_tests,
        "preprocessing_ablation_runs": ablation_runs,
        "preprocessing_ablation_summary": ablation_summary,
        "preprocessing_ablation_friedman_tests": ablation_friedman_results,
        "preprocessing_ablation_pairwise_tests": ablation_pairwise_tests,
        "ner_summary": ner_summary,
        "ner_type_distribution": ner_type_summary,
        "ner_human_audit_template_unscored": ner_audit_template,
        "ner_top_surfaces_overall": top_entity_surfaces,
        "ner_top_surfaces_by_type": top_entity_surfaces_by_type,
        "ner_test_top_surfaces_overall": top_entity_surfaces_test,
        "ner_test_top_surfaces_by_type": top_entity_surfaces_by_type_test,
        "ner_surface_frequency_all": entity_surface_frequency_all,
        "ner_document_summary": ner_document_summary,
        "ner_errors": ner_errors,
        "entity_inventory_5000": entity_inventory,
        "graph_summary": graph_summary,
        "graph_type_distribution": graph_type_summary,
        "graph_degree_distribution": graph_degree_distribution,
        "graph_edge_weight_distribution": graph_edge_weight_distribution,
        "graph_component_distribution": graph_component_distribution,
        "graph_topic_vector_sensitivity": graph_topic_vector_summary,
        "link_prediction_folds": link_folds,
        "link_prediction_fold_assignments": link_fold_assignments,
        "link_prediction_evaluation_diagnostics": link_evaluation_diagnostics,
        "link_prediction_repeat_means": link_repeat_means,
        "link_prediction_summary": link_summary,
        "link_prediction_friedman_tests": link_friedman_results,
        "link_prediction_pairwise_tests": link_pairwise_tests,
        "link_prediction_main_comparisons": main_vs_baselines,
        "claim_ready_summary": claim_ready_summary,
        "explicit_limitations": limitations,
    }


def dataframe_markdown(frame: pd.DataFrame, columns: Sequence[str] | None = None, max_rows: int = 50) -> str:
    table = frame.copy()
    if columns is not None:
        table = table[list(columns)]
    if len(table) > max_rows:
        table = table.head(max_rows)
    # Try to use tabulate, fallback to string representation if not available
    try:
        return table.to_markdown(index=False, floatfmt=".4f")
    except ImportError:
        # Fallback to simple string representation if tabulate is not installed
        return table.to_string(index=False, float_format="%.4f")


def build_markdown_report() -> str:
    topic_columns = [
        "model", "encoder", "k", "c_v_mean", "c_v_sd", "c_npmi_mean", "c_npmi_sd",
        "diversity_mean", "distinctness_mean", "stability", "valid_topic_fraction_mean",
    ]
    link_columns = [
        "method", "fold_evaluations", "independent_repeat_blocks",
        "roc_auc_mean", "roc_auc_repeat_sd",
        "average_precision_mean", "average_precision_repeat_sd",
    ]
    lines = [
        "# Persian Topic Modeling and Entity-Association Graph: Reproducibility Report",
        "",
        f"- Run finished (UTC): {datetime.now(timezone.utc).isoformat()}",
        f"- Source dataset SHA-256: `{dataset_sha256}`",
        f"- Raw source rows scanned: {raw_row_count:,}",
        f"- Unique Persian-rich rows after hash deduplication: {len(unique_candidate_meta):,}",
        f"- Working sample: {len(sample):,}; train: {len(train):,}; test: {len(test):,}",
        f"- Descriptive topic grid: {list(TOPIC_COUNTS)}; statistical grid: {list(STATISTICAL_TOPIC_COUNTS)}; seeds: {list(SEEDS)}",
        f"- Core topic-model runs: {expected_core_runs}; ParsBERT sensitivity runs: {expected_parsbert_extra_runs}",
        "",
        "## Primary common-K topic-model comparison",
        "",
        dataframe_markdown(common_k_results, topic_columns),
        "",
        "## Coherence-maximizing configurations (metric-specific; not overall winners)",
        "",
        dataframe_markdown(best_by_model_display, topic_columns),
        "",
        "## Pareto-efficient core configurations",
        "",
        dataframe_markdown(core_pareto_front, topic_columns, max_rows=100),
        "",
        "## Named-entity recognition summary",
        "",
        dataframe_markdown(ner_summary),
        "",
        "## Entity graph summary",
        "",
        dataframe_markdown(graph_summary),
        "",
        "## Leakage-controlled link-prediction summary",
        "",
        dataframe_markdown(link_summary, link_columns),
        "",
        "## Claim-ready statements",
        "",
        dataframe_markdown(claim_ready_summary, max_rows=100),
        "",
        "## Explicit limitations",
        "",
        dataframe_markdown(limitations, max_rows=100),
        "",
        "## Integrity checks",
        "",
        dataframe_markdown(pd.DataFrame([{"check": key, "passed": value} for key, value in integrity_checks.items()]), max_rows=200),
        "",
        "Full run-level values, topic words, provenance, fold assignments, pair hashes, diagnostics, and tests are stored in `q1_final_evidence.json`.",
    ]
    return "\n".join(lines)


def write_evidence_files() -> None:
    evidence = build_final_evidence()
    FINAL_JSON.write_text(
        json.dumps(sanitize_json(evidence), ensure_ascii=False, indent=2, allow_nan=False),
        encoding="utf-8",
    )
    FINAL_REPORT.write_text(build_markdown_report(), encoding="utf-8")


# Draft write and physical validation, then a final write containing completed checks.
write_evidence_files()
with FINAL_JSON.open("r", encoding="utf-8") as handle:
    validated_json = json.load(handle)
if not isinstance(validated_json, dict):
    raise RuntimeError("Final JSON is not a top-level object.")
if not FINAL_REPORT.exists() or FINAL_REPORT.stat().st_size == 0:
    raise RuntimeError("Markdown report was not created.")

# Temporary resources are not public evidence files.
shutil.rmtree(TEMP_DIR, ignore_errors=True)
public_files = sorted(path.name for path in OUTPUT_DIR.iterdir() if path.is_file())

integrity_checks.update({
    "json_file_created_and_valid": FINAL_JSON.exists() and FINAL_JSON.stat().st_size > 0,
    "markdown_report_created_and_valid": FINAL_REPORT.exists() and FINAL_REPORT.stat().st_size > 0,
    "output_directory_contains_only_two_public_files": public_files == sorted([FINAL_JSON.name, FINAL_REPORT.name]),
})
failed_final = [name for name, passed in integrity_checks.items() if not passed]
if failed_final:
    raise RuntimeError(f"Final integrity checks failed: {failed_final}")

# Rewrite files so their integrity sections contain the final passed state.
write_evidence_files()
with FINAL_JSON.open("r", encoding="utf-8") as handle:
    json.load(handle)

print("\nIntegrity checks — all must be True")
display(pd.DataFrame([{"check": key, "passed": value} for key, value in integrity_checks.items()]))
print(f"\nPrimary publication table: common K={PRIMARY_COMMON_K}")
display(common_k_results)
print("\nMetric-specific coherence maxima — interpret with the Pareto table")
display(best_by_model_display)
print("\nPublication-ready link-prediction table")
display(link_summary)
print("\nClaim-ready statements")
display(claim_ready_summary)
print("\nExplicit limitations and inference scope")
display(limitations)

heading("9. Final files")
json_sha256 = sha256_file(FINAL_JSON)
report_sha256 = sha256_file(FINAL_REPORT)
elapsed_hours = (time.time() - START_TIME) / 3600
print("====================")
print("FINAL FILES")
print("====================")
print(f"JSON evidence: {FINAL_JSON}")
print(f"Markdown report: {FINAL_REPORT}")
print(f"JSON SHA-256: {json_sha256}")
print(f"Markdown SHA-256: {report_sha256}")
print(f"Dataset SHA-256: {dataset_sha256}")
print(f"Runtime: {elapsed_hours:.2f} hours")
print("\nAll integrity checks passed. No figures, dummy entities, fabricated topics, or fabricated statistical results were generated.")
print("Inference remains exploratory where stated and is not population-level generalization.")

[2026-07-24 07:01:52] Dataset: C:\Users\Amir\Desktop\My Desk\Desktop 20260506\Articles\Second article\FInilized\version 8 (last run)\data\wikipedia.csv
[2026-07-24 07:01:52] Output directory: C:\Users\Amir\Desktop\My Desk\Desktop 20260506\Articles\Second article\FInilized\version 8 (last run)\q1_final_run
[2026-07-24 07:01:52] Device: cpu

## 1. Full-dataset audit and sampling

[2026-07-24 07:01:57] Text column: content; title column: title

Pass 1/2: full corpus audit: 0it [00:00, ?it/s]

Pass 2/2: retrieve sampled documents: 0it [00:00, ?it/s]

Persian preprocessing:   0%|          | 0/50000 [00:00<?, ?it/s]

Null and provenance audit

                 stage                                   metric    value
0          raw_dataset                                     rows  2525369
1          raw_dataset                                text_null     6780
2          raw_dataset                      text_empty_non_null        0
3          raw_dataset                 text_non_string_non_null        0
4          raw_dataset                               title_null        6
5     raw_column_nulls                            null__content     6780
6     raw_column_nulls                               null__link        0
7     raw_column_nulls                              null__title        6
8          eligibility  eligible_rows_before_text_deduplication  1931265
9          eligibility       duplicate_eligible_texts_by_hash64  1340495
10         eligibility                     unique_eligible_rows   590770
11      working_sample                             sampled_rows    50000
12      working_sample                            raw_text_null        0
13      working_sample                               title_null        0
14      working_sample            clean_text_null_before_filter       23
15  post_preprocessing                               valid_rows    49977
16  post_preprocessing                          clean_text_null        0
17  post_preprocessing                         token_count_null        0
18               split                               train_rows    10000
19               split                    topic_validation_rows     5000
20               split                           link_test_rows    10000
21               split                        unused_valid_rows    24977
22               split                 train_validation_overlap        0
23               split                  train_link_test_overlap        0
24               split             validation_link_test_overlap        0

Duplicate-group distribution

                 group  unique_hash_groups
0          occurs_once              145030
1         occurs_twice              216103
2        occurs_3_to_5              167498
3       occurs_6_to_10               43306
4  occurs_more_than_10               18833

Largest exact-text hash groups

    occurrences  first_source_row  last_source_row   text_hash64_hex
0         31088           1679834          1823493  1ccc06eb95bdf9f5
1          9542             32659          2525334  aa4621e9835690ee
2          6989           1679987          1823375  96b0db2a4ae6077e
3          3455             32978          2524824  3c8566dc4d3685ab
4          2872            970615          1679699  89f84eb4f7c11918
5          2819             20740           492660  2ea7599dd963e903
6          1682             32475          2525114  f48b90427876df62
7          1443            970608          1679761  dcd827242b32e14e
8          1439            970605          1679720  139f5ab25f6ce6c7
9          1432            970606          1679713  c5be7f82462e33fd
10         1427            970653          1679762  e3c71e383875f3ef
11         1408            970610          1679709  fbf81875dfb73cde
12         1383            970639          1679765  bc1c314814ebab54
13         1380            970612          1679727  0f7f036efa01e124
14         1376            970650          1679715  c9850c7a38eaf902
15         1335            970604          1679766  682750cf42131fe5
16         1332            970644          1679701  6d276ea13b281abc
17         1328            970600          1679703  5cbee855079fdd37
18         1316            970634          1679710  15700e97355f9d9e
19         1311            970618          1679760  b0f4439dfaff2293

Preprocessing outcomes

                               status  documents
0  empty_or_short_after_preprocessing         23
1                            retained      49977

Length-stratified split

  stratum  valid_sample  train  topic_validation  link_test
0      Q1         11607   2322              1161       2323
1      Q2          5947   1190               595       1190
2      Q3          8515   1704               852       1704
3      Q4          7454   1492               746       1491
4      Q5          8155   1632               816       1631
5      Q6          8299   1660               830       1661

Token-length summary

        token_count
count  49977.000000
mean      75.830442
std      245.613290
min        3.000000
10%        7.000000
25%        9.000000
50%       14.000000
75%       49.000000
90%      163.000000
95%      315.200000
99%      976.240000
max     9839.000000

## 2. Topic-model benchmark

Shared training vocabulary: 10,000
Held-out topic-validation documents: 5,000
Held-out reference vocabulary represented: 9,611

,training_documents,topic_validation_documents,link_test_documents_reserved,shared_vocabulary_size,shared_vocabulary_min_df,shared_vocabulary_max_df,coherence_reference_documents,coherence_reference_vocabulary,top_n_words,candidate_words
0,10000,5000,10000,10000,5,0.5,5000,9611,10,30

Most frequent terms in the shared training vocabulary

        term  vocabulary_index  document_frequency  corpus_frequency
0        سال              4542                3519             11111
1    شده‌است              5071                3460              5848
2      عنوان              5717                1605              4100
3       قرار              6191                2215              4046
4        نام              7730                1688              3779
5       توسط              2636                1466              3264
6    استفاده               649                1015              3196
7       فیلم              6091                1106              3140
8       واقع              8468                2044              3094
9        نفر              7919                2404              3021
10      بازی              1404                1327              2914
11      کشور              9435                1295              2733
12       شهر              5178                1237              2658
13     جمعیت              2905                2163              2472
14     ایران              1237                 688              2399
15        آن               210                 804              2150
16       اهل              1153                2064              2124
17       کار              9213                 942              2040
18    میلادی              7638                1149              1976
19     اشاره               729                1664              1944
20     منطقه              7424                1342              1904
21     روستا              4266                 999              1884
22     تاریخ              2123                1155              1866
23      صورت              5391                 900              1856
24      زمان              4403                 845              1799
25      شرکت              5098                 749              1798
26  کرده‌است              9372                1210              1782
27      اصلی               778                 842              1772
28  بوده‌است              1943                1246              1695
29       دست              3714                 773              1587

LDA seed=42:   0%|          | 0/13 [00:00<?, ?it/s]

LDA seed=123:   0%|          | 0/13 [00:00<?, ?it/s]

LDA seed=456:   0%|          | 0/13 [00:00<?, ?it/s]

NMF seed=42:   0%|          | 0/13 [00:00<?, ?it/s]

NMF seed=123:   0%|          | 0/13 [00:00<?, ?it/s]

NMF seed=456:   0%|          | 0/13 [00:00<?, ?it/s]

[2026-07-24 10:22:41] Encoding 10,000 documents with multilingual core encoder (train): sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Batches:   0%|          | 0/157 [00:00<?, ?it/s]

[2026-07-24 10:28:54] Encoding 5,000 documents with multilingual core encoder (topic validation): sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Batches:   0%|          | 0/79 [00:00<?, ?it/s]

C:\Users\Amir\anaconda3\envs\persian_topic_env\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

BERTopic seed=42:   0%|          | 0/13 [00:00<?, ?it/s]

C:\Users\Amir\anaconda3\envs\persian_topic_env\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

BERTopic seed=123:   0%|          | 0/13 [00:00<?, ?it/s]

C:\Users\Amir\anaconda3\envs\persian_topic_env\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

BERTopic seed=456:   0%|          | 0/13 [00:00<?, ?it/s]

CTM seed=42:   0%|          | 0/13 [00:00<?, ?it/s]

Epoch: [10/10]	 Seen Samples: [99840/100000]	Train Loss: 579.4070710402268	Time: 0:00:12.782698: : 10it [02:09, 12.95s/it]

%|          | 0/79 [00:00<?, ?it/s]
%|▎         | 2/79 [00:00<00:03, 19.56it/s]
%|▋         | 5/79 [00:00<00:03, 20.36it/s]
%|█         | 8/79 [00:00<00:03, 20.29it/s]
%|█▍        | 11/79 [00:00<00:03, 20.45it/s]
%|█▊        | 14/79 [00:00<00:03, 20.90it/s]
%|██▏       | 17/79 [00:00<00:03, 20.47it/s]
%|██▌       | 20/79 [00:00<00:02, 20.95it/s]
%|██▉       | 23/79 [00:01<00:02, 21.11it/s]
%|███▎      | 26/79 [00:01<00:02, 21.13it/s]
%|███▋      | 29/79 [00:01<00:02, 21.00it/s]
%|████      | 32/79 [00:01<00:02, 20.74it/s]
%|████▍     | 35/79 [00:01<00:02, 20.75it/s]
%|████▊     | 38/79 [00:01<00:01, 20.64it/s]
%|█████▏    | 41/79 [00:01<00:01, 20.63it/s]
%|█████▌    | 44/79 [00:02<00:01, 20.94it/s]
%|█████▉    | 47/79 [00:02<00:01, 20.86it/s]
%|██████▎   | 50/79 [00:02<00:01, 20.96it/s]
%|██████▋   | 53/79 [00:02<00:01, 21.14it/s]
%|███████   | 56/79 [00:02<00:01, 21.10it/s]
%|███████▍  | 59/79 [00:02<00:00, 21.15it/s]
%|███████▊  | 62/79 [00:02<00:00, 21.07it/s]
%|████████▏ | 65/79 [00:03<00:00, 21.13it/s]
%|████████▌ | 68/79 [00:03<00:00, 21.11it/s]
%|████████▉ | 71/79 [00:03<00:00, 21.29it/s]
%|█████████▎| 74/79 [00:03<00:00, 21.01it/s]
100%|██████████| 79/79 [00:03<00:00, 21.10it/s]
Epoch: [10/10]	 Seen Samples: [99840/100000]	Train Loss: 571.2768581096942	Time: 0:00:13.763989: : 10it [02:18, 13.86s/it]

%|          | 0/79 [00:00<?, ?it/s]
%|▎         | 2/79 [00:00<00:03, 19.93it/s]
%|▌         | 4/79 [00:00<00:03, 19.24it/s]
%|▉         | 7/79 [00:00<00:03, 19.71it/s]
%|█▏        | 9/79 [00:00<00:03, 19.71it/s]
%|█▌        | 12/79 [00:00<00:03, 20.34it/s]
%|█▉        | 15/79 [00:00<00:03, 20.18it/s]
%|██▎       | 18/79 [00:00<00:02, 20.51it/s]
%|██▋       | 21/79 [00:01<00:02, 20.67it/s]
%|███       | 24/79 [00:01<00:02, 20.61it/s]
%|███▍      | 27/79 [00:01<00:02, 20.60it/s]
%|███▊      | 30/79 [00:01<00:02, 20.90it/s]
%|████▏     | 33/79 [00:01<00:02, 20.16it/s]
%|████▌     | 36/79 [00:01<00:02, 20.07it/s]
%|████▉     | 39/79 [00:01<00:01, 20.36it/s]
%|█████▎    | 42/79 [00:02<00:01, 20.21it/s]
%|█████▋    | 45/79 [00:02<00:01, 20.43it/s]
%|██████    | 48/79 [00:02<00:01, 20.42it/s]
%|██████▍   | 51/79 [00:02<00:01, 20.38it/s]
%|██████▊   | 54/79 [00:02<00:01, 20.19it/s]
%|███████▏  | 57/79 [00:02<00:01, 20.06it/s]
%|███████▌  | 60/79 [00:02<00:00, 20.37it/s]
%|███████▉  | 63/79 [00:03<00:00, 20.44it/s]
%|████████▎ | 66/79 [00:03<00:00, 20.33it/s]
%|████████▋ | 69/79 [00:03<00:00, 20.45it/s]
%|█████████ | 72/79 [00:03<00:00, 20.54it/s]
%|█████████▍| 75/79 [00:03<00:00, 20.65it/s]
100%|██████████| 79/79 [00:03<00:00, 20.51it/s]
Epoch: [10/10]	 Seen Samples: [99840/100000]	Train Loss: 568.0663639948918	Time: 0:00:13.422690: : 10it [02:12, 13.22s/it]

%|          | 0/79 [00:00<?, ?it/s]
%|▍         | 3/79 [00:00<00:03, 21.32it/s]
%|▊         | 6/79 [00:00<00:03, 21.22it/s]
%|█▏        | 9/79 [00:00<00:03, 21.28it/s]
%|█▌        | 12/79 [00:00<00:03, 21.52it/s]
%|█▉        | 15/79 [00:00<00:03, 21.14it/s]
%|██▎       | 18/79 [00:00<00:02, 20.71it/s]
%|██▋       | 21/79 [00:01<00:02, 20.20it/s]
%|███       | 24/79 [00:01<00:02, 20.20it/s]
%|███▍      | 27/79 [00:01<00:02, 20.26it/s]
%|███▊      | 30/79 [00:01<00:02, 20.60it/s]
%|████▏     | 33/79 [00:01<00:02, 20.88it/s]
%|████▌     | 36/79 [00:01<00:02, 20.86it/s]
%|████▉     | 39/79 [00:01<00:01, 20.93it/s]
%|█████▎    | 42/79 [00:02<00:01, 20.67it/s]
%|█████▋    | 45/79 [00:02<00:01, 21.00it/s]
%|██████    | 48/79 [00:02<00:01, 20.91it/s]
%|██████▍   | 51/79 [00:02<00:01, 20.91it/s]
%|██████▊   | 54/79 [00:02<00:01, 20.80it/s]
%|███████▏  | 57/79 [00:02<00:01, 20.96it/s]
%|███████▌  | 60/79 [00:02<00:00, 21.09it/s]
%|███████▉  | 63/79 [00:03<00:00, 21.16it/s]
%|████████▎ | 66/79 [00:03<00:00, 21.08it/s]
%|████████▋ | 69/79 [00:03<00:00, 21.23it/s]
%|█████████ | 72/79 [00:03<00:00, 21.05it/s]
%|█████████▍| 75/79 [00:03<00:00, 21.08it/s]
100%|██████████| 79/79 [00:03<00:00, 21.08it/s]
Epoch: [10/10]	 Seen Samples: [99840/100000]	Train Loss: 568.2087121621156	Time: 0:00:12.994342: : 10it [02:10, 13.03s/it]

%|          | 0/79 [00:00<?, ?it/s]
%|▍         | 3/79 [00:00<00:03, 20.20it/s]
%|▊         | 6/79 [00:00<00:03, 20.14it/s]
%|█▏        | 9/79 [00:00<00:03, 20.13it/s]
%|█▌        | 12/79 [00:00<00:03, 20.21it/s]
%|█▉        | 15/79 [00:00<00:03, 20.22it/s]
%|██▎       | 18/79 [00:00<00:02, 20.37it/s]
%|██▋       | 21/79 [00:01<00:02, 20.38it/s]
%|███       | 24/79 [00:01<00:02, 20.24it/s]
%|███▍      | 27/79 [00:01<00:02, 20.42it/s]
%|███▊      | 30/79 [00:01<00:02, 20.44it/s]
%|████▏     | 33/79 [00:01<00:02, 20.47it/s]
%|████▌     | 36/79 [00:01<00:02, 19.49it/s]
%|████▊     | 38/79 [00:01<00:02, 19.35it/s]
%|█████     | 40/79 [00:02<00:02, 19.43it/s]
%|█████▎    | 42/79 [00:02<00:02, 16.80it/s]
%|█████▋    | 45/79 [00:02<00:01, 17.87it/s]
%|█████▉    | 47/79 [00:02<00:01, 18.30it/s]
%|██████▎   | 50/79 [00:02<00:01, 19.23it/s]
%|██████▌   | 52/79 [00:02<00:01, 19.14it/s]
%|██████▉   | 55/79 [00:02<00:01, 19.66it/s]
%|███████▎  | 58/79 [00:02<00:01, 19.91it/s]
%|███████▋  | 61/79 [00:03<00:00, 20.19it/s]
%|████████  | 64/79 [00:03<00:00, 20.27it/s]
%|████████▍ | 67/79 [00:03<00:00, 20.33it/s]
%|████████▊ | 70/79 [00:03<00:00, 20.50it/s]
%|█████████▏| 73/79 [00:03<00:00, 20.47it/s]
%|█████████▌| 76/79 [00:03<00:00, 20.40it/s]
100%|██████████| 79/79 [00:03<00:00, 20.00it/s]
Epoch: [10/10]	 Seen Samples: [99840/100000]	Train Loss: 566.1877623337966	Time: 0:00:12.900203: : 10it [02:11, 13.16s/it]

%|          | 0/79 [00:00<?, ?it/s]
%|▍         | 3/79 [00:00<00:03, 20.31it/s]
%|▊         | 6/79 [00:00<00:03, 20.55it/s]
%|█▏        | 9/79 [00:00<00:03, 20.34it/s]
%|█▌        | 12/79 [00:00<00:03, 20.50it/s]
%|█▉        | 15/79 [00:00<00:03, 19.88it/s]
%|██▏       | 17/79 [00:00<00:03, 19.45it/s]
%|██▍       | 19/79 [00:00<00:03, 19.14it/s]
%|██▊       | 22/79 [00:01<00:02, 19.51it/s]
%|███▏      | 25/79 [00:01<00:02, 19.80it/s]
%|███▌      | 28/79 [00:01<00:02, 20.09it/s]
%|███▉      | 31/79 [00:01<00:02, 20.16it/s]
%|████▎     | 34/79 [00:01<00:02, 20.28it/s]
%|████▋     | 37/79 [00:01<00:02, 20.60it/s]
%|█████     | 40/79 [00:01<00:01, 20.16it/s]
%|█████▍    | 43/79 [00:02<00:01, 20.51it/s]
%|█████▊    | 46/79 [00:02<00:01, 20.40it/s]
%|██████▏   | 49/79 [00:02<00:01, 20.29it/s]
%|██████▌   | 52/79 [00:02<00:01, 20.40it/s]
%|██████▉   | 55/79 [00:02<00:01, 20.42it/s]
%|███████▎  | 58/79 [00:02<00:01, 20.29it/s]
%|███████▋  | 61/79 [00:03<00:00, 20.79it/s]
%|████████  | 64/79 [00:03<00:00, 20.18it/s]
%|████████▍ | 67/79 [00:03<00:00, 18.46it/s]
%|████████▊ | 70/79 [00:03<00:00, 18.79it/s]
%|█████████ | 72/79 [00:03<00:00, 18.86it/s]
%|█████████▍| 75/79 [00:03<00:00, 19.32it/s]
100%|██████████| 79/79 [00:03<00:00, 20.07it/s]
Epoch: [10/10]	 Seen Samples: [99840/100000]	Train Loss: 577.3673974061624	Time: 0:00:13.725255: : 10it [02:20, 14.06s/it]

%|          | 0/79 [00:00<?, ?it/s]
%|▍         | 3/79 [00:00<00:03, 19.92it/s]
%|▋         | 5/79 [00:00<00:03, 19.78it/s]
%|▉         | 7/79 [00:00<00:03, 19.77it/s]
%|█▎        | 10/79 [00:00<00:03, 20.59it/s]
%|█▋        | 13/79 [00:00<00:03, 20.35it/s]
%|██        | 16/79 [00:00<00:03, 20.41it/s]
%|██▍       | 19/79 [00:00<00:02, 20.32it/s]
%|██▊       | 22/79 [00:01<00:02, 20.19it/s]
%|███▏      | 25/79 [00:01<00:02, 20.35it/s]
%|███▌      | 28/79 [00:01<00:02, 20.34it/s]
%|███▉      | 31/79 [00:01<00:02, 20.33it/s]
%|████▎     | 34/79 [00:01<00:02, 20.42it/s]
%|████▋     | 37/79 [00:01<00:02, 20.53it/s]
%|█████     | 40/79 [00:01<00:01, 20.19it/s]
%|█████▍    | 43/79 [00:02<00:01, 20.16it/s]
%|█████▊    | 46/79 [00:02<00:01, 20.13it/s]
%|██████▏   | 49/79 [00:02<00:01, 19.92it/s]
%|██████▌   | 52/79 [00:02<00:01, 20.13it/s]
%|██████▉   | 55/79 [00:02<00:01, 20.53it/s]
%|███████▎  | 58/79 [00:02<00:01, 19.94it/s]
%|███████▋  | 61/79 [00:03<00:00, 19.89it/s]
%|███████▉  | 63/79 [00:03<00:00, 19.73it/s]
%|████████▏ | 65/79 [00:03<00:00, 19.73it/s]
%|████████▍ | 67/79 [00:03<00:00, 19.35it/s]
%|████████▊ | 70/79 [00:03<00:00, 20.18it/s]
%|█████████▏| 73/79 [00:03<00:00, 19.95it/s]
%|█████████▍| 75/79 [00:03<00:00, 19.66it/s]
100%|██████████| 79/79 [00:03<00:00, 20.27it/s]
Epoch: [10/10]	 Seen Samples: [99840/100000]	Train Loss: 590.8277151645758	Time: 0:00:14.058720: : 10it [02:20, 14.08s/it]

%|          | 0/79 [00:00<?, ?it/s]
%|▎         | 2/79 [00:00<00:03, 19.71it/s]
%|▌         | 4/79 [00:00<00:03, 19.37it/s]
%|▉         | 7/79 [00:00<00:03, 19.79it/s]
%|█▏        | 9/79 [00:00<00:03, 19.68it/s]
%|█▍        | 11/79 [00:00<00:03, 17.66it/s]
%|█▋        | 13/79 [00:00<00:03, 18.24it/s]
%|█▉        | 15/79 [00:00<00:03, 18.70it/s]
%|██▎       | 18/79 [00:00<00:03, 19.67it/s]
%|██▋       | 21/79 [00:01<00:02, 19.93it/s]
%|███       | 24/79 [00:01<00:02, 20.18it/s]
%|███▍      | 27/79 [00:01<00:02, 20.52it/s]
%|███▊      | 30/79 [00:01<00:02, 20.52it/s]
%|████▏     | 33/79 [00:01<00:02, 20.55it/s]
%|████▌     | 36/79 [00:01<00:02, 20.79it/s]
%|████▉     | 39/79 [00:01<00:01, 21.10it/s]
%|█████▎    | 42/79 [00:02<00:01, 20.65it/s]
%|█████▋    | 45/79 [00:02<00:01, 20.39it/s]
%|██████    | 48/79 [00:02<00:01, 20.43it/s]
%|██████▍   | 51/79 [00:02<00:01, 20.52it/s]
%|██████▊   | 54/79 [00:02<00:01, 20.47it/s]
%|███████▏  | 57/79 [00:02<00:01, 20.27it/s]
%|███████▌  | 60/79 [00:02<00:00, 20.44it/s]
%|███████▉  | 63/79 [00:03<00:00, 20.64it/s]
%|████████▎ | 66/79 [00:03<00:00, 20.40it/s]
%|████████▋ | 69/79 [00:03<00:00, 20.49it/s]
%|█████████ | 72/79 [00:03<00:00, 20.82it/s]
%|█████████▍| 75/79 [00:03<00:00, 20.84it/s]
100%|██████████| 79/79 [00:03<00:00, 20.51it/s]
Epoch: [10/10]	 Seen Samples: [99840/100000]	Train Loss: 607.3110226362179	Time: 0:00:14.878099: : 10it [02:29, 14.91s/it]

%|          | 0/79 [00:00<?, ?it/s]
%|▎         | 2/79 [00:00<00:04, 19.12it/s]
%|▌         | 4/79 [00:00<00:03, 19.29it/s]
%|▉         | 7/79 [00:00<00:03, 20.22it/s]
%|█▎        | 10/79 [00:00<00:03, 20.71it/s]
%|█▋        | 13/79 [00:00<00:03, 20.89it/s]
%|██        | 16/79 [00:00<00:02, 21.33it/s]
%|██▍       | 19/79 [00:00<00:02, 20.67it/s]
%|██▊       | 22/79 [00:01<00:02, 19.67it/s]
%|███▏      | 25/79 [00:01<00:02, 19.89it/s]
%|███▌      | 28/79 [00:01<00:02, 20.21it/s]
%|███▉      | 31/79 [00:01<00:02, 20.50it/s]
%|████▎     | 34/79 [00:01<00:02, 20.25it/s]
%|████▋     | 37/79 [00:01<00:02, 20.18it/s]
%|█████     | 40/79 [00:01<00:01, 20.33it/s]
%|█████▍    | 43/79 [00:02<00:01, 20.47it/s]
%|█████▊    | 46/79 [00:02<00:01, 20.83it/s]
%|██████▏   | 49/79 [00:02<00:01, 20.51it/s]
%|██████▌   | 52/79 [00:02<00:01, 20.39it/s]
%|██████▉   | 55/79 [00:02<00:01, 20.45it/s]
%|███████▎  | 58/79 [00:02<00:01, 20.59it/s]
%|███████▋  | 61/79 [00:02<00:00, 20.63it/s]
%|████████  | 64/79 [00:03<00:00, 20.74it/s]
%|████████▍ | 67/79 [00:03<00:00, 20.61it/s]
%|████████▊ | 70/79 [00:03<00:00, 20.70it/s]
%|█████████▏| 73/79 [00:03<00:00, 20.75it/s]
%|█████████▌| 76/79 [00:03<00:00, 20.60it/s]
100%|██████████| 79/79 [00:03<00:00, 20.66it/s]
Epoch: [10/10]	 Seen Samples: [99840/100000]	Train Loss: 627.2395070393881	Time: 0:00:14.973965: : 10it [02:28, 14.89s/it]

%|          | 0/79 [00:00<?, ?it/s]
%|▍         | 3/79 [00:00<00:03, 20.52it/s]
%|▊         | 6/79 [00:00<00:03, 20.22it/s]
%|█▏        | 9/79 [00:00<00:03, 19.98it/s]
%|█▌        | 12/79 [00:00<00:03, 20.14it/s]
%|█▉        | 15/79 [00:00<00:03, 20.19it/s]
%|██▎       | 18/79 [00:00<00:03, 17.84it/s]
%|██▌       | 20/79 [00:01<00:03, 18.18it/s]
%|██▊       | 22/79 [00:01<00:03, 18.55it/s]
%|███       | 24/79 [00:01<00:02, 18.71it/s]
%|███▎      | 26/79 [00:01<00:02, 18.78it/s]
%|███▋      | 29/79 [00:01<00:02, 19.53it/s]
%|███▉      | 31/79 [00:01<00:02, 19.65it/s]
%|████▎     | 34/79 [00:01<00:02, 19.97it/s]
%|████▌     | 36/79 [00:01<00:02, 19.81it/s]
%|████▊     | 38/79 [00:01<00:02, 19.52it/s]
%|█████     | 40/79 [00:02<00:01, 19.50it/s]
%|█████▎    | 42/79 [00:02<00:01, 19.35it/s]
%|█████▋    | 45/79 [00:02<00:01, 20.04it/s]
%|██████    | 48/79 [00:02<00:01, 20.26it/s]
%|██████▍   | 51/79 [00:02<00:01, 19.96it/s]
%|██████▋   | 53/79 [00:02<00:01, 19.97it/s]
%|██████▉   | 55/79 [00:02<00:01, 19.93it/s]
%|███████▏  | 57/79 [00:02<00:01, 19.93it/s]
%|███████▍  | 59/79 [00:03<00:01, 19.80it/s]
%|███████▋  | 61/79 [00:03<00:00, 19.18it/s]
%|███████▉  | 63/79 [00:03<00:00, 19.40it/s]
%|████████▏ | 65/79 [00:03<00:00, 19.51it/s]
%|████████▍ | 67/79 [00:03<00:00, 19.38it/s]
%|████████▋ | 69/79 [00:03<00:00, 19.54it/s]
%|█████████ | 72/79 [00:03<00:00, 20.06it/s]
%|█████████▍| 75/79 [00:03<00:00, 20.51it/s]
100%|██████████| 79/79 [00:03<00:00, 19.84it/s]
Epoch: [10/10]	 Seen Samples: [99840/100000]	Train Loss: 650.3545166406876	Time: 0:00:16.623762: : 10it [02:46, 16.65s/it]

%|          | 0/79 [00:00<?, ?it/s]
%|▎         | 2/79 [00:00<00:04, 18.59it/s]
%|▋         | 5/79 [00:00<00:03, 19.93it/s]
%|█         | 8/79 [00:00<00:03, 20.71it/s]
%|█▍        | 11/79 [00:00<00:03, 20.93it/s]
%|█▊        | 14/79 [00:00<00:03, 18.56it/s]
%|██        | 16/79 [00:00<00:03, 18.86it/s]
%|██▎       | 18/79 [00:00<00:03, 19.12it/s]
%|██▋       | 21/79 [00:01<00:02, 19.67it/s]
%|██▉       | 23/79 [00:01<00:02, 19.43it/s]
%|███▏      | 25/79 [00:01<00:02, 19.55it/s]
%|███▍      | 27/79 [00:01<00:02, 19.62it/s]
%|███▋      | 29/79 [00:01<00:02, 19.43it/s]
%|████      | 32/79 [00:01<00:02, 19.97it/s]
%|████▎     | 34/79 [00:01<00:02, 19.79it/s]
%|████▋     | 37/79 [00:01<00:02, 20.27it/s]
%|█████     | 40/79 [00:02<00:01, 20.41it/s]
%|█████▍    | 43/79 [00:02<00:01, 20.40it/s]
%|█████▊    | 46/79 [00:02<00:01, 20.45it/s]
%|██████▏   | 49/79 [00:02<00:01, 20.46it/s]
%|██████▌   | 52/79 [00:02<00:01, 20.35it/s]
%|██████▉   | 55/79 [00:02<00:01, 20.55it/s]
%|███████▎  | 58/79 [00:02<00:01, 20.50it/s]
%|███████▋  | 61/79 [00:03<00:00, 20.69it/s]
%|████████  | 64/79 [00:03<00:00, 21.04it/s]
%|████████▍ | 67/79 [00:03<00:00, 20.96it/s]
%|████████▊ | 70/79 [00:03<00:00, 20.79it/s]
%|█████████▏| 73/79 [00:03<00:00, 20.55it/s]
%|█████████▌| 76/79 [00:03<00:00, 20.79it/s]
100%|██████████| 79/79 [00:03<00:00, 20.39it/s]
Epoch: [10/10]	 Seen Samples: [99840/100000]	Train Loss: 670.0540472177358	Time: 0:00:16.114691: : 10it [02:40, 16.06s/it]

%|          | 0/79 [00:00<?, ?it/s]
%|▎         | 2/79 [00:00<00:04, 17.35it/s]
%|▌         | 4/79 [00:00<00:04, 18.42it/s]
%|▊         | 6/79 [00:00<00:03, 18.73it/s]
%|█         | 8/79 [00:00<00:04, 17.61it/s]
%|█▎        | 10/79 [00:00<00:03, 18.19it/s]
%|█▌        | 12/79 [00:00<00:03, 18.56it/s]
%|█▊        | 14/79 [00:00<00:03, 18.85it/s]
%|██        | 16/79 [00:00<00:03, 18.93it/s]
%|██▎       | 18/79 [00:00<00:03, 19.09it/s]
%|██▌       | 20/79 [00:01<00:03, 18.87it/s]
%|██▉       | 23/79 [00:01<00:02, 19.65it/s]
%|███▏      | 25/79 [00:01<00:02, 19.71it/s]
%|███▌      | 28/79 [00:01<00:02, 20.48it/s]
%|███▉      | 31/79 [00:01<00:02, 20.51it/s]
%|████▎     | 34/79 [00:01<00:02, 20.34it/s]
%|████▋     | 37/79 [00:01<00:02, 20.65it/s]
%|█████     | 40/79 [00:02<00:01, 20.50it/s]
%|█████▍    | 43/79 [00:02<00:01, 20.04it/s]
%|█████▊    | 46/79 [00:02<00:01, 20.48it/s]
%|██████▏   | 49/79 [00:02<00:01, 20.37it/s]
%|██████▌   | 52/79 [00:02<00:01, 22.38it/s]
%|██████▉   | 55/79 [00:02<00:01, 23.96it/s]
%|███████▍  | 59/79 [00:02<00:00, 25.96it/s]
%|███████▊  | 62/79 [00:02<00:00, 26.49it/s]
%|████████▏ | 65/79 [00:03<00:00, 24.64it/s]
%|████████▌ | 68/79 [00:03<00:00, 22.16it/s]
%|████████▉ | 71/79 [00:03<00:00, 21.21it/s]
%|█████████▎| 74/79 [00:03<00:00, 20.74it/s]
100%|██████████| 79/79 [00:03<00:00, 20.95it/s]
Epoch: [10/10]	 Seen Samples: [99840/100000]	Train Loss: 686.9402362138798	Time: 0:00:18.209045: : 10it [02:57, 17.76s/it]

%|          | 0/79 [00:00<?, ?it/s]
%|▎         | 2/79 [00:00<00:03, 19.46it/s]
%|▋         | 5/79 [00:00<00:03, 20.04it/s]
%|▉         | 7/79 [00:00<00:03, 20.02it/s]
%|█▎        | 10/79 [00:00<00:03, 19.91it/s]
%|█▌        | 12/79 [00:00<00:03, 19.67it/s]
%|█▉        | 15/79 [00:00<00:03, 19.93it/s]
%|██▎       | 18/79 [00:00<00:03, 20.08it/s]
%|██▋       | 21/79 [00:01<00:02, 19.70it/s]
%|███       | 24/79 [00:01<00:02, 20.04it/s]
%|███▍      | 27/79 [00:01<00:02, 20.77it/s]
%|███▊      | 30/79 [00:01<00:02, 19.67it/s]
%|████      | 32/79 [00:01<00:02, 18.57it/s]
%|████▎     | 34/79 [00:01<00:02, 18.54it/s]
%|████▋     | 37/79 [00:01<00:02, 19.91it/s]
%|████▉     | 39/79 [00:01<00:02, 19.56it/s]
%|█████▎    | 42/79 [00:02<00:01, 20.37it/s]
%|█████▋    | 45/79 [00:02<00:01, 19.82it/s]
%|██████    | 48/79 [00:02<00:01, 20.34it/s]
%|██████▍   | 51/79 [00:02<00:01, 20.15it/s]
%|██████▊   | 54/79 [00:02<00:01, 20.12it/s]
%|███████▏  | 57/79 [00:02<00:01, 20.33it/s]
%|███████▌  | 60/79 [00:03<00:00, 21.04it/s]
%|███████▉  | 63/79 [00:03<00:00, 20.14it/s]
%|████████▎ | 66/79 [00:03<00:00, 20.72it/s]
%|████████▋ | 69/79 [00:03<00:00, 20.15it/s]
%|█████████ | 72/79 [00:03<00:00, 19.91it/s]
%|█████████▍| 75/79 [00:03<00:00, 19.78it/s]
100%|██████████| 79/79 [00:03<00:00, 20.06it/s]
Epoch: [10/10]	 Seen Samples: [99840/100000]	Train Loss: 705.2480760231996	Time: 0:00:17.655880: : 10it [02:56, 17.68s/it]

%|          | 0/79 [00:00<?, ?it/s]
%|▎         | 2/79 [00:00<00:04, 18.86it/s]
%|▋         | 5/79 [00:00<00:03, 20.70it/s]
%|█         | 8/79 [00:00<00:03, 20.38it/s]
%|█▍        | 11/79 [00:00<00:03, 21.27it/s]
%|█▊        | 14/79 [00:00<00:03, 21.08it/s]
%|██▏       | 17/79 [00:00<00:02, 21.49it/s]
%|██▌       | 20/79 [00:00<00:02, 20.12it/s]
%|██▉       | 23/79 [00:01<00:02, 20.02it/s]
%|███▎      | 26/79 [00:01<00:02, 20.44it/s]
%|███▋      | 29/79 [00:01<00:02, 20.39it/s]
%|████      | 32/79 [00:01<00:02, 20.28it/s]
%|████▍     | 35/79 [00:01<00:02, 20.54it/s]
%|████▊     | 38/79 [00:01<00:02, 20.00it/s]
%|█████▏    | 41/79 [00:02<00:01, 20.06it/s]
%|█████▌    | 44/79 [00:02<00:01, 20.12it/s]
%|█████▉    | 47/79 [00:02<00:01, 21.00it/s]
%|██████▎   | 50/79 [00:02<00:01, 20.37it/s]
%|██████▋   | 53/79 [00:02<00:01, 20.19it/s]
%|███████   | 56/79 [00:02<00:01, 19.79it/s]
%|███████▎  | 58/79 [00:02<00:01, 19.72it/s]
%|███████▋  | 61/79 [00:02<00:00, 20.48it/s]
%|████████  | 64/79 [00:03<00:00, 20.75it/s]
%|████████▍ | 67/79 [00:03<00:00, 20.98it/s]
%|████████▊ | 70/79 [00:03<00:00, 21.36it/s]
%|█████████▏| 73/79 [00:03<00:00, 20.94it/s]
%|█████████▌| 76/79 [00:03<00:00, 21.91it/s]
100%|██████████| 79/79 [00:03<00:00, 20.81it/s]

CTM seed=123:   0%|          | 0/13 [00:00<?, ?it/s]

Epoch: [10/10]	 Seen Samples: [99840/100000]	Train Loss: 578.087289859087	Time: 0:00:13.654942: : 10it [02:17, 13.73s/it]

%|          | 0/79 [00:00<?, ?it/s]
%|▎         | 2/79 [00:00<00:03, 19.83it/s]
%|▋         | 5/79 [00:00<00:03, 20.33it/s]
%|█         | 8/79 [00:00<00:03, 20.40it/s]
%|█▍        | 11/79 [00:00<00:03, 20.58it/s]
%|█▊        | 14/79 [00:00<00:03, 21.32it/s]
%|██▏       | 17/79 [00:00<00:02, 21.54it/s]
%|██▌       | 20/79 [00:00<00:02, 21.92it/s]
%|██▉       | 23/79 [00:01<00:02, 22.07it/s]
%|███▎      | 26/79 [00:01<00:02, 21.65it/s]
%|███▋      | 29/79 [00:01<00:02, 22.69it/s]
%|████      | 32/79 [00:01<00:02, 22.25it/s]
%|████▍     | 35/79 [00:01<00:02, 21.86it/s]
%|████▊     | 38/79 [00:01<00:01, 22.11it/s]
%|█████▏    | 41/79 [00:01<00:01, 22.18it/s]
%|█████▌    | 44/79 [00:02<00:01, 21.96it/s]
%|█████▉    | 47/79 [00:02<00:01, 21.74it/s]
%|██████▎   | 50/79 [00:02<00:01, 21.03it/s]
%|██████▋   | 53/79 [00:02<00:01, 21.24it/s]
%|███████   | 56/79 [00:02<00:01, 21.28it/s]
%|███████▍  | 59/79 [00:02<00:00, 20.79it/s]
%|███████▊  | 62/79 [00:02<00:00, 21.15it/s]
%|████████▏ | 65/79 [00:03<00:00, 22.07it/s]
%|████████▌ | 68/79 [00:03<00:00, 22.44it/s]
%|████████▉ | 71/79 [00:03<00:00, 22.06it/s]
%|█████████▎| 74/79 [00:03<00:00, 21.86it/s]
100%|██████████| 79/79 [00:03<00:00, 21.72it/s]
Epoch: [10/10]	 Seen Samples: [99840/100000]	Train Loss: 571.0857630998661	Time: 0:00:13.231570: : 10it [02:12, 13.28s/it]

%|          | 0/79 [00:00<?, ?it/s]
%|▎         | 2/79 [00:00<00:04, 17.50it/s]
%|▋         | 5/79 [00:00<00:03, 21.08it/s]
%|█         | 8/79 [00:00<00:03, 21.52it/s]
%|█▍        | 11/79 [00:00<00:03, 21.94it/s]
%|█▊        | 14/79 [00:00<00:03, 21.28it/s]
%|██▏       | 17/79 [00:00<00:02, 21.86it/s]
%|██▌       | 20/79 [00:00<00:02, 20.81it/s]
%|██▉       | 23/79 [00:01<00:02, 20.88it/s]
%|███▎      | 26/79 [00:01<00:02, 20.59it/s]
%|███▋      | 29/79 [00:01<00:02, 20.91it/s]
%|████      | 32/79 [00:01<00:02, 20.93it/s]
%|████▍     | 35/79 [00:01<00:02, 20.81it/s]
%|████▊     | 38/79 [00:01<00:01, 20.57it/s]
%|█████▏    | 41/79 [00:01<00:01, 20.75it/s]
%|█████▌    | 44/79 [00:02<00:01, 20.80it/s]
%|█████▉    | 47/79 [00:02<00:01, 20.86it/s]
%|██████▎   | 50/79 [00:02<00:01, 20.88it/s]
%|██████▋   | 53/79 [00:02<00:01, 20.67it/s]
%|███████   | 56/79 [00:02<00:01, 20.78it/s]
%|███████▍  | 59/79 [00:02<00:00, 20.58it/s]
%|███████▊  | 62/79 [00:02<00:00, 20.86it/s]
%|████████▏ | 65/79 [00:03<00:00, 20.93it/s]
%|████████▌ | 68/79 [00:03<00:00, 21.68it/s]
%|████████▉ | 71/79 [00:03<00:00, 20.64it/s]
%|█████████▎| 74/79 [00:03<00:00, 21.04it/s]
100%|██████████| 79/79 [00:03<00:00, 21.14it/s]
Epoch: [10/10]	 Seen Samples: [99840/100000]	Train Loss: 567.8769274980594	Time: 0:00:13.974896: : 10it [02:20, 14.02s/it]

%|          | 0/79 [00:00<?, ?it/s]
%|▍         | 3/79 [00:00<00:03, 20.84it/s]
%|▊         | 6/79 [00:00<00:03, 20.56it/s]
%|█▏        | 9/79 [00:00<00:03, 21.42it/s]
%|█▌        | 12/79 [00:00<00:03, 20.54it/s]
%|█▉        | 15/79 [00:00<00:03, 20.65it/s]
%|██▎       | 18/79 [00:00<00:02, 20.91it/s]
%|██▋       | 21/79 [00:01<00:02, 21.06it/s]
%|███       | 24/79 [00:01<00:02, 21.75it/s]
%|███▍      | 27/79 [00:01<00:02, 21.58it/s]
%|███▊      | 30/79 [00:01<00:02, 21.74it/s]
%|████▏     | 33/79 [00:01<00:02, 21.37it/s]
%|████▌     | 36/79 [00:01<00:01, 21.58it/s]
%|████▉     | 39/79 [00:01<00:01, 21.79it/s]
%|█████▎    | 42/79 [00:01<00:01, 21.96it/s]
%|█████▋    | 45/79 [00:02<00:01, 22.79it/s]
%|██████    | 48/79 [00:02<00:01, 22.10it/s]
%|██████▍   | 51/79 [00:02<00:01, 21.69it/s]
%|██████▊   | 54/79 [00:02<00:01, 21.70it/s]
%|███████▏  | 57/79 [00:02<00:01, 21.58it/s]
%|███████▌  | 60/79 [00:02<00:00, 22.26it/s]
%|███████▉  | 63/79 [00:02<00:00, 21.81it/s]
%|████████▎ | 66/79 [00:03<00:00, 22.12it/s]
%|████████▋ | 69/79 [00:03<00:00, 21.68it/s]
%|█████████ | 72/79 [00:03<00:00, 21.60it/s]
%|█████████▍| 75/79 [00:03<00:00, 21.85it/s]
100%|██████████| 79/79 [00:03<00:00, 21.78it/s]
Epoch: [10/10]	 Seen Samples: [99840/100000]	Train Loss: 566.5004838796763	Time: 0:00:13.684357: : 10it [02:14, 13.46s/it]

%|          | 0/79 [00:00<?, ?it/s]
%|▎         | 2/79 [00:00<00:03, 19.56it/s]
%|▋         | 5/79 [00:00<00:03, 20.83it/s]
%|█         | 8/79 [00:00<00:03, 20.71it/s]
%|█▍        | 11/79 [00:00<00:03, 21.12it/s]
%|█▊        | 14/79 [00:00<00:03, 20.91it/s]
%|██▏       | 17/79 [00:00<00:02, 21.62it/s]
%|██▌       | 20/79 [00:00<00:02, 21.75it/s]
%|██▉       | 23/79 [00:01<00:02, 21.73it/s]
%|███▎      | 26/79 [00:01<00:02, 21.85it/s]
%|███▋      | 29/79 [00:01<00:02, 21.71it/s]
%|████      | 32/79 [00:01<00:02, 21.81it/s]
%|████▍     | 35/79 [00:01<00:02, 21.34it/s]
%|████▊     | 38/79 [00:01<00:01, 21.06it/s]
%|█████▏    | 41/79 [00:01<00:01, 21.20it/s]
%|█████▌    | 44/79 [00:02<00:01, 20.82it/s]
%|█████▉    | 47/79 [00:02<00:01, 20.33it/s]
%|██████▎   | 50/79 [00:02<00:01, 20.22it/s]
%|██████▋   | 53/79 [00:02<00:01, 20.16it/s]
%|███████   | 56/79 [00:02<00:01, 20.20it/s]
%|███████▍  | 59/79 [00:02<00:00, 20.61it/s]
%|███████▊  | 62/79 [00:02<00:00, 19.83it/s]
%|████████▏ | 65/79 [00:03<00:00, 20.41it/s]
%|████████▌ | 68/79 [00:03<00:00, 20.03it/s]
%|████████▉ | 71/79 [00:03<00:00, 20.25it/s]
%|█████████▎| 74/79 [00:03<00:00, 20.51it/s]
100%|██████████| 79/79 [00:03<00:00, 20.89it/s]
Epoch: [10/10]	 Seen Samples: [99840/100000]	Train Loss: 569.0541240985577	Time: 0:00:14.108987: : 10it [02:21, 14.10s/it]

%|          | 0/79 [00:00<?, ?it/s]
%|▎         | 2/79 [00:00<00:03, 19.74it/s]
%|▌         | 4/79 [00:00<00:03, 19.42it/s]
%|▉         | 7/79 [00:00<00:03, 20.03it/s]
%|█▏        | 9/79 [00:00<00:03, 20.02it/s]
%|█▍        | 11/79 [00:00<00:03, 19.94it/s]
%|█▊        | 14/79 [00:00<00:03, 20.88it/s]
%|██▏       | 17/79 [00:00<00:03, 20.13it/s]
%|██▌       | 20/79 [00:01<00:02, 20.27it/s]
%|██▉       | 23/79 [00:01<00:02, 19.65it/s]
%|███▏      | 25/79 [00:01<00:02, 19.62it/s]
%|███▌      | 28/79 [00:01<00:02, 20.27it/s]
%|███▉      | 31/79 [00:01<00:02, 20.53it/s]
%|████▎     | 34/79 [00:01<00:02, 20.54it/s]
%|████▋     | 37/79 [00:01<00:02, 20.31it/s]
%|█████     | 40/79 [00:01<00:01, 20.92it/s]
%|█████▍    | 43/79 [00:02<00:01, 21.16it/s]
%|█████▊    | 46/79 [00:02<00:01, 21.82it/s]
%|██████▏   | 49/79 [00:02<00:01, 21.32it/s]
%|██████▌   | 52/79 [00:02<00:01, 21.89it/s]
%|██████▉   | 55/79 [00:02<00:01, 21.16it/s]
%|███████▎  | 58/79 [00:02<00:00, 21.97it/s]
%|███████▋  | 61/79 [00:02<00:00, 20.98it/s]
%|████████  | 64/79 [00:03<00:00, 20.86it/s]
%|████████▍ | 67/79 [00:03<00:00, 21.02it/s]
%|████████▊ | 70/79 [00:03<00:00, 20.91it/s]
%|█████████▏| 73/79 [00:03<00:00, 21.19it/s]
%|█████████▌| 76/79 [00:03<00:00, 20.80it/s]
100%|██████████| 79/79 [00:03<00:00, 20.94it/s]
Epoch: [10/10]	 Seen Samples: [99840/100000]	Train Loss: 576.1971232096354	Time: 0:00:13.289382: : 10it [02:12, 13.22s/it]

%|          | 0/79 [00:00<?, ?it/s]
%|▎         | 2/79 [00:00<00:03, 19.64it/s]
%|▌         | 4/79 [00:00<00:03, 19.33it/s]
%|▉         | 7/79 [00:00<00:03, 20.28it/s]
%|█▎        | 10/79 [00:00<00:03, 20.44it/s]
%|█▋        | 13/79 [00:00<00:03, 20.47it/s]
%|██        | 16/79 [00:00<00:03, 20.73it/s]
%|██▍       | 19/79 [00:00<00:02, 20.13it/s]
%|██▊       | 22/79 [00:01<00:02, 20.42it/s]
%|███▏      | 25/79 [00:01<00:02, 20.84it/s]
%|███▌      | 28/79 [00:01<00:02, 20.85it/s]
%|███▉      | 31/79 [00:01<00:02, 20.76it/s]
%|████▎     | 34/79 [00:01<00:02, 20.34it/s]
%|████▋     | 37/79 [00:01<00:02, 20.63it/s]
%|█████     | 40/79 [00:01<00:01, 21.00it/s]
%|█████▍    | 43/79 [00:02<00:01, 20.41it/s]
%|█████▊    | 46/79 [00:02<00:01, 20.65it/s]
%|██████▏   | 49/79 [00:02<00:01, 20.66it/s]
%|██████▌   | 52/79 [00:02<00:01, 20.38it/s]
%|██████▉   | 55/79 [00:02<00:01, 20.35it/s]
%|███████▎  | 58/79 [00:02<00:01, 20.54it/s]
%|███████▋  | 61/79 [00:02<00:00, 20.79it/s]
%|████████  | 64/79 [00:03<00:00, 21.09it/s]
%|████████▍ | 67/79 [00:03<00:00, 20.83it/s]
%|████████▊ | 70/79 [00:03<00:00, 21.71it/s]
%|█████████▏| 73/79 [00:03<00:00, 20.96it/s]
%|█████████▌| 76/79 [00:03<00:00, 20.98it/s]
100%|██████████| 79/79 [00:03<00:00, 20.84it/s]
Epoch: [10/10]	 Seen Samples: [99840/100000]	Train Loss: 591.167610168457	Time: 0:00:14.606848: : 10it [02:29, 14.90s/it]

%|          | 0/79 [00:00<?, ?it/s]
%|▎         | 2/79 [00:00<00:04, 18.46it/s]
%|▋         | 5/79 [00:00<00:03, 20.76it/s]
%|█         | 8/79 [00:00<00:03, 21.23it/s]
%|█▍        | 11/79 [00:00<00:03, 21.20it/s]
%|█▊        | 14/79 [00:00<00:03, 20.95it/s]
%|██▏       | 17/79 [00:00<00:02, 21.22it/s]
%|██▌       | 20/79 [00:00<00:02, 21.95it/s]
%|██▉       | 23/79 [00:01<00:02, 21.28it/s]
%|███▎      | 26/79 [00:01<00:02, 21.80it/s]
%|███▋      | 29/79 [00:01<00:02, 22.37it/s]
%|████      | 32/79 [00:01<00:02, 21.35it/s]
%|████▍     | 35/79 [00:01<00:02, 21.45it/s]
%|████▊     | 38/79 [00:01<00:01, 21.36it/s]
%|█████▏    | 41/79 [00:01<00:01, 21.71it/s]
%|█████▌    | 44/79 [00:02<00:01, 21.43it/s]
%|█████▉    | 47/79 [00:02<00:01, 20.85it/s]
%|██████▎   | 50/79 [00:02<00:01, 21.03it/s]
%|██████▋   | 53/79 [00:02<00:01, 21.30it/s]
%|███████   | 56/79 [00:02<00:01, 20.73it/s]
%|███████▍  | 59/79 [00:02<00:00, 20.82it/s]
%|███████▊  | 62/79 [00:02<00:00, 20.88it/s]
%|████████▏ | 65/79 [00:03<00:00, 20.10it/s]
%|████████▌ | 68/79 [00:03<00:00, 19.77it/s]
%|████████▉ | 71/79 [00:03<00:00, 19.92it/s]
%|█████████▏| 73/79 [00:03<00:00, 19.90it/s]
%|█████████▍| 75/79 [00:03<00:00, 19.79it/s]
100%|██████████| 79/79 [00:03<00:00, 21.04it/s]
Epoch: [10/10]	 Seen Samples: [99840/100000]	Train Loss: 612.1801450680464	Time: 0:00:14.574533: : 10it [02:25, 14.56s/it]

%|          | 0/79 [00:00<?, ?it/s]
%|▎         | 2/79 [00:00<00:04, 18.88it/s]
%|▋         | 5/79 [00:00<00:03, 21.54it/s]
%|█         | 8/79 [00:00<00:03, 21.34it/s]
%|█▍        | 11/79 [00:00<00:03, 20.33it/s]
%|█▊        | 14/79 [00:00<00:03, 19.80it/s]
%|██        | 16/79 [00:00<00:03, 19.62it/s]
%|██▎       | 18/79 [00:00<00:03, 19.42it/s]
%|██▌       | 20/79 [00:01<00:03, 19.06it/s]
%|██▊       | 22/79 [00:01<00:03, 18.96it/s]
%|███       | 24/79 [00:01<00:02, 18.70it/s]
%|███▍      | 27/79 [00:01<00:02, 19.35it/s]
%|███▋      | 29/79 [00:01<00:02, 19.20it/s]
%|████      | 32/79 [00:01<00:02, 20.02it/s]
%|████▍     | 35/79 [00:01<00:02, 20.30it/s]
%|████▊     | 38/79 [00:01<00:02, 19.33it/s]
%|█████     | 40/79 [00:02<00:02, 19.07it/s]
%|█████▎    | 42/79 [00:02<00:01, 18.83it/s]
%|█████▌    | 44/79 [00:02<00:01, 19.00it/s]
%|█████▊    | 46/79 [00:02<00:01, 18.92it/s]
%|██████    | 48/79 [00:02<00:01, 18.59it/s]
%|██████▎   | 50/79 [00:02<00:01, 18.78it/s]
%|██████▌   | 52/79 [00:02<00:01, 18.88it/s]
%|██████▊   | 54/79 [00:02<00:01, 18.44it/s]
%|███████▏  | 57/79 [00:02<00:01, 19.28it/s]
%|███████▍  | 59/79 [00:03<00:01, 19.33it/s]
%|███████▋  | 61/79 [00:03<00:00, 19.17it/s]
%|███████▉  | 63/79 [00:03<00:00, 18.85it/s]
%|████████▎ | 66/79 [00:03<00:00, 19.58it/s]
%|████████▋ | 69/79 [00:03<00:00, 20.11it/s]
%|█████████ | 72/79 [00:03<00:00, 20.82it/s]
%|█████████▍| 75/79 [00:03<00:00, 21.12it/s]
100%|██████████| 79/79 [00:03<00:00, 19.83it/s]
Epoch: [10/10]	 Seen Samples: [99840/100000]	Train Loss: 629.3648532965244	Time: 0:00:14.142322: : 10it [02:20, 14.08s/it]

%|          | 0/79 [00:00<?, ?it/s]
%|▎         | 2/79 [00:00<00:04, 18.30it/s]
%|▋         | 5/79 [00:00<00:03, 20.08it/s]
%|▉         | 7/79 [00:00<00:03, 19.84it/s]
%|█▏        | 9/79 [00:00<00:03, 19.72it/s]
%|█▍        | 11/79 [00:00<00:03, 19.62it/s]
%|█▋        | 13/79 [00:00<00:03, 19.71it/s]
%|██        | 16/79 [00:00<00:02, 21.03it/s]
%|██▍       | 19/79 [00:00<00:02, 21.00it/s]
%|██▊       | 22/79 [00:01<00:02, 20.60it/s]
%|███▏      | 25/79 [00:01<00:02, 20.55it/s]
%|███▌      | 28/79 [00:01<00:02, 20.75it/s]
%|███▉      | 31/79 [00:01<00:02, 20.48it/s]
%|████▎     | 34/79 [00:01<00:02, 20.32it/s]
%|████▋     | 37/79 [00:01<00:02, 20.29it/s]
%|█████     | 40/79 [00:01<00:01, 20.50it/s]
%|█████▍    | 43/79 [00:02<00:01, 20.98it/s]
%|█████▊    | 46/79 [00:02<00:01, 20.42it/s]
%|██████▏   | 49/79 [00:02<00:01, 20.68it/s]
%|██████▌   | 52/79 [00:02<00:01, 20.44it/s]
%|██████▉   | 55/79 [00:02<00:01, 21.50it/s]
%|███████▎  | 58/79 [00:02<00:01, 20.61it/s]
%|███████▋  | 61/79 [00:02<00:00, 20.37it/s]
%|████████  | 64/79 [00:03<00:00, 20.33it/s]
%|████████▍ | 67/79 [00:03<00:00, 19.99it/s]
%|████████▊ | 70/79 [00:03<00:00, 20.33it/s]
%|█████████▏| 73/79 [00:03<00:00, 19.75it/s]
%|█████████▍| 75/79 [00:03<00:00, 19.67it/s]
100%|██████████| 79/79 [00:03<00:00, 20.41it/s]
Epoch: [10/10]	 Seen Samples: [99840/100000]	Train Loss: 646.729023860051	Time: 0:00:15.929936: : 10it [02:41, 16.12s/it]

%|          | 0/79 [00:00<?, ?it/s]
%|▎         | 2/79 [00:00<00:04, 18.38it/s]
%|▋         | 5/79 [00:00<00:03, 19.59it/s]
%|█         | 8/79 [00:00<00:03, 20.05it/s]
%|█▎        | 10/79 [00:00<00:03, 19.86it/s]
%|█▌        | 12/79 [00:00<00:03, 19.74it/s]
%|█▉        | 15/79 [00:00<00:03, 21.19it/s]
%|██▎       | 18/79 [00:00<00:03, 20.13it/s]
%|██▋       | 21/79 [00:01<00:02, 20.61it/s]
%|███       | 24/79 [00:01<00:02, 20.16it/s]
%|███▍      | 27/79 [00:01<00:02, 20.66it/s]
%|███▊      | 30/79 [00:01<00:02, 20.58it/s]
%|████▏     | 33/79 [00:01<00:02, 20.33it/s]
%|████▌     | 36/79 [00:01<00:02, 20.45it/s]
%|████▉     | 39/79 [00:01<00:01, 20.41it/s]
%|█████▎    | 42/79 [00:02<00:01, 20.62it/s]
%|█████▋    | 45/79 [00:02<00:01, 20.15it/s]
%|██████    | 48/79 [00:02<00:01, 21.01it/s]
%|██████▍   | 51/79 [00:02<00:01, 20.71it/s]
%|██████▊   | 54/79 [00:02<00:01, 20.43it/s]
%|███████▏  | 57/79 [00:02<00:01, 20.43it/s]
%|███████▌  | 60/79 [00:02<00:00, 20.52it/s]
%|███████▉  | 63/79 [00:03<00:00, 20.55it/s]
%|████████▎ | 66/79 [00:03<00:00, 20.54it/s]
%|████████▋ | 69/79 [00:03<00:00, 20.91it/s]
%|█████████ | 72/79 [00:03<00:00, 21.45it/s]
%|█████████▍| 75/79 [00:03<00:00, 21.16it/s]
100%|██████████| 79/79 [00:03<00:00, 20.77it/s]
Epoch: [10/10]	 Seen Samples: [99840/100000]	Train Loss: 672.0863938942933	Time: 0:00:16.379717: : 10it [02:42, 16.30s/it]

%|          | 0/79 [00:00<?, ?it/s]
%|▎         | 2/79 [00:00<00:04, 16.78it/s]
%|▋         | 5/79 [00:00<00:03, 20.08it/s]
%|▉         | 7/79 [00:00<00:03, 19.70it/s]
%|█▏        | 9/79 [00:00<00:03, 19.39it/s]
%|█▍        | 11/79 [00:00<00:03, 19.29it/s]
%|█▊        | 14/79 [00:00<00:03, 19.91it/s]
%|██        | 16/79 [00:00<00:03, 19.56it/s]
%|██▍       | 19/79 [00:00<00:02, 20.61it/s]
%|██▊       | 22/79 [00:01<00:02, 20.56it/s]
%|███▏      | 25/79 [00:01<00:02, 20.46it/s]
%|███▌      | 28/79 [00:01<00:02, 19.77it/s]
%|███▉      | 31/79 [00:01<00:02, 20.43it/s]
%|████▎     | 34/79 [00:01<00:02, 20.38it/s]
%|████▋     | 37/79 [00:01<00:02, 20.34it/s]
%|█████     | 40/79 [00:01<00:01, 21.77it/s]
%|█████▍    | 43/79 [00:02<00:01, 21.50it/s]
%|█████▊    | 46/79 [00:02<00:01, 20.73it/s]
%|██████▏   | 49/79 [00:02<00:01, 20.66it/s]
%|██████▌   | 52/79 [00:02<00:01, 20.43it/s]
%|██████▉   | 55/79 [00:02<00:01, 20.50it/s]
%|███████▎  | 58/79 [00:02<00:01, 19.64it/s]
%|███████▌  | 60/79 [00:02<00:00, 19.51it/s]
%|███████▊  | 62/79 [00:03<00:00, 19.40it/s]
%|████████▏ | 65/79 [00:03<00:00, 19.55it/s]
%|████████▍ | 67/79 [00:03<00:00, 19.52it/s]
%|████████▋ | 69/79 [00:03<00:00, 19.41it/s]
%|████████▉ | 71/79 [00:03<00:00, 19.55it/s]
%|█████████▏| 73/79 [00:03<00:00, 19.43it/s]
%|█████████▍| 75/79 [00:03<00:00, 19.50it/s]
100%|██████████| 79/79 [00:03<00:00, 20.17it/s]
Epoch: [10/10]	 Seen Samples: [99840/100000]	Train Loss: 690.2045123760516	Time: 0:00:16.894847: : 10it [02:49, 16.90s/it]

%|          | 0/79 [00:00<?, ?it/s]
%|▎         | 2/79 [00:00<00:04, 16.89it/s]
%|▌         | 4/79 [00:00<00:04, 18.11it/s]
%|▊         | 6/79 [00:00<00:03, 18.43it/s]
%|█         | 8/79 [00:00<00:03, 18.87it/s]
%|█▍        | 11/79 [00:00<00:03, 19.62it/s]
%|█▊        | 14/79 [00:00<00:03, 20.58it/s]
%|██▏       | 17/79 [00:00<00:03, 19.81it/s]
%|██▍       | 19/79 [00:00<00:03, 19.76it/s]
%|██▋       | 21/79 [00:01<00:02, 19.60it/s]
%|██▉       | 23/79 [00:01<00:02, 19.40it/s]
%|███▏      | 25/79 [00:01<00:02, 19.49it/s]
%|███▍      | 27/79 [00:01<00:02, 19.61it/s]
%|███▊      | 30/79 [00:01<00:02, 19.79it/s]
%|████      | 32/79 [00:01<00:02, 19.45it/s]
%|████▎     | 34/79 [00:01<00:02, 19.51it/s]
%|████▌     | 36/79 [00:01<00:02, 19.18it/s]
%|████▊     | 38/79 [00:01<00:02, 19.33it/s]
%|█████▏    | 41/79 [00:02<00:01, 19.60it/s]
%|█████▌    | 44/79 [00:02<00:01, 20.32it/s]
%|█████▉    | 47/79 [00:02<00:01, 20.47it/s]
%|██████▎   | 50/79 [00:02<00:01, 20.73it/s]
%|██████▋   | 53/79 [00:02<00:01, 20.51it/s]
%|███████   | 56/79 [00:02<00:01, 21.15it/s]
%|███████▍  | 59/79 [00:02<00:00, 20.68it/s]
%|███████▊  | 62/79 [00:03<00:00, 21.24it/s]
%|████████▏ | 65/79 [00:03<00:00, 20.76it/s]
%|████████▌ | 68/79 [00:03<00:00, 20.56it/s]
%|████████▉ | 71/79 [00:03<00:00, 20.80it/s]
%|█████████▎| 74/79 [00:03<00:00, 20.69it/s]
100%|██████████| 79/79 [00:03<00:00, 20.24it/s]
Epoch: [10/10]	 Seen Samples: [99840/100000]	Train Loss: 704.8529025346805	Time: 0:00:17.710531: : 10it [02:55, 17.54s/it]

%|          | 0/79 [00:00<?, ?it/s]
%|▎         | 2/79 [00:00<00:04, 16.17it/s]
%|▌         | 4/79 [00:00<00:04, 17.55it/s]
%|▊         | 6/79 [00:00<00:03, 18.41it/s]
%|█         | 8/79 [00:00<00:03, 18.91it/s]
%|█▎        | 10/79 [00:00<00:03, 19.00it/s]
%|█▋        | 13/79 [00:00<00:03, 20.36it/s]
%|██        | 16/79 [00:00<00:03, 20.36it/s]
%|██▍       | 19/79 [00:00<00:03, 19.75it/s]
%|██▋       | 21/79 [00:01<00:03, 18.91it/s]
%|██▉       | 23/79 [00:01<00:02, 19.05it/s]
%|███▏      | 25/79 [00:01<00:02, 18.98it/s]
%|███▍      | 27/79 [00:01<00:03, 15.82it/s]
%|███▊      | 30/79 [00:01<00:02, 17.49it/s]
%|████      | 32/79 [00:01<00:02, 18.00it/s]
%|████▎     | 34/79 [00:01<00:02, 18.45it/s]
%|████▌     | 36/79 [00:01<00:02, 18.56it/s]
%|████▉     | 39/79 [00:02<00:02, 19.19it/s]
%|█████▎    | 42/79 [00:02<00:01, 19.67it/s]
%|█████▋    | 45/79 [00:02<00:01, 19.51it/s]
%|█████▉    | 47/79 [00:02<00:01, 19.58it/s]
%|██████▎   | 50/79 [00:02<00:01, 20.08it/s]
%|██████▋   | 53/79 [00:02<00:01, 20.48it/s]
%|███████   | 56/79 [00:02<00:01, 19.82it/s]
%|███████▎  | 58/79 [00:03<00:01, 19.83it/s]
%|███████▋  | 61/79 [00:03<00:00, 20.23it/s]
%|████████  | 64/79 [00:03<00:00, 20.12it/s]
%|████████▍ | 67/79 [00:03<00:00, 19.97it/s]
%|████████▋ | 69/79 [00:03<00:00, 19.79it/s]
%|████████▉ | 71/79 [00:03<00:00, 19.18it/s]
%|█████████▏| 73/79 [00:03<00:00, 19.35it/s]
%|█████████▌| 76/79 [00:03<00:00, 19.76it/s]
100%|██████████| 79/79 [00:04<00:00, 19.41it/s]

CTM seed=456:   0%|          | 0/13 [00:00<?, ?it/s]

Epoch: [10/10]	 Seen Samples: [99840/100000]	Train Loss: 579.160010509002	Time: 0:00:12.952903: : 10it [02:13, 13.36s/it]

%|          | 0/79 [00:00<?, ?it/s]
%|▎         | 2/79 [00:00<00:04, 18.69it/s]
%|▌         | 4/79 [00:00<00:03, 19.42it/s]
%|▊         | 6/79 [00:00<00:03, 19.64it/s]
%|█         | 8/79 [00:00<00:03, 19.63it/s]
%|█▍        | 11/79 [00:00<00:03, 21.06it/s]
%|█▊        | 14/79 [00:00<00:02, 22.05it/s]
%|██▏       | 17/79 [00:00<00:02, 21.69it/s]
%|██▌       | 20/79 [00:00<00:02, 21.29it/s]
%|██▉       | 23/79 [00:01<00:02, 21.75it/s]
%|███▎      | 26/79 [00:01<00:02, 22.27it/s]
%|███▋      | 29/79 [00:01<00:02, 21.70it/s]
%|████      | 32/79 [00:01<00:02, 22.48it/s]
%|████▍     | 35/79 [00:01<00:01, 22.11it/s]
%|████▊     | 38/79 [00:01<00:01, 21.99it/s]
%|█████▏    | 41/79 [00:01<00:01, 21.60it/s]
%|█████▌    | 44/79 [00:02<00:01, 21.77it/s]
%|█████▉    | 47/79 [00:02<00:01, 21.75it/s]
%|██████▎   | 50/79 [00:02<00:01, 21.84it/s]
%|██████▋   | 53/79 [00:02<00:01, 21.65it/s]
%|███████   | 56/79 [00:02<00:01, 21.84it/s]
%|███████▍  | 59/79 [00:02<00:00, 22.59it/s]
%|███████▊  | 62/79 [00:02<00:00, 21.31it/s]
%|████████▏ | 65/79 [00:03<00:00, 21.07it/s]
%|████████▌ | 68/79 [00:03<00:00, 21.01it/s]
%|████████▉ | 71/79 [00:03<00:00, 20.88it/s]
%|█████████▎| 74/79 [00:03<00:00, 20.96it/s]
100%|██████████| 79/79 [00:03<00:00, 21.65it/s]
Epoch: [10/10]	 Seen Samples: [99840/100000]	Train Loss: 569.9974057124211	Time: 0:00:13.219471: : 10it [02:10, 13.06s/it]

%|          | 0/79 [00:00<?, ?it/s]
%|▎         | 2/79 [00:00<00:04, 18.34it/s]
%|▌         | 4/79 [00:00<00:04, 18.61it/s]
%|▊         | 6/79 [00:00<00:03, 19.18it/s]
%|█         | 8/79 [00:00<00:03, 18.80it/s]
%|█▎        | 10/79 [00:00<00:03, 18.90it/s]
%|█▋        | 13/79 [00:00<00:03, 20.41it/s]
%|██        | 16/79 [00:00<00:03, 19.86it/s]
%|██▎       | 18/79 [00:00<00:03, 19.33it/s]
%|██▋       | 21/79 [00:01<00:02, 19.85it/s]
%|███       | 24/79 [00:01<00:02, 20.22it/s]
%|███▍      | 27/79 [00:01<00:02, 20.09it/s]
%|███▊      | 30/79 [00:01<00:02, 19.90it/s]
%|████▏     | 33/79 [00:01<00:02, 20.35it/s]
%|████▌     | 36/79 [00:01<00:02, 20.16it/s]
%|████▉     | 39/79 [00:01<00:01, 20.71it/s]
%|█████▎    | 42/79 [00:02<00:01, 20.58it/s]
%|█████▋    | 45/79 [00:02<00:01, 20.30it/s]
%|██████    | 48/79 [00:02<00:01, 20.31it/s]
%|██████▍   | 51/79 [00:02<00:01, 20.54it/s]
%|██████▊   | 54/79 [00:02<00:01, 19.88it/s]
%|███████▏  | 57/79 [00:02<00:01, 19.78it/s]
%|███████▌  | 60/79 [00:03<00:00, 20.16it/s]
%|███████▉  | 63/79 [00:03<00:00, 19.41it/s]
%|████████▏ | 65/79 [00:03<00:00, 19.37it/s]
%|████████▍ | 67/79 [00:03<00:00, 19.13it/s]
%|████████▋ | 69/79 [00:03<00:00, 19.22it/s]
%|████████▉ | 71/79 [00:03<00:00, 19.33it/s]
%|█████████▏| 73/79 [00:03<00:00, 19.36it/s]
%|█████████▍| 75/79 [00:03<00:00, 19.39it/s]
100%|██████████| 79/79 [00:03<00:00, 20.03it/s]
Epoch: [10/10]	 Seen Samples: [99840/100000]	Train Loss: 563.810546483749	Time: 0:00:14.171578: : 10it [02:20, 14.00s/it]

%|          | 0/79 [00:00<?, ?it/s]
%|▎         | 2/79 [00:00<00:04, 17.45it/s]
%|▋         | 5/79 [00:00<00:03, 19.62it/s]
%|█         | 8/79 [00:00<00:03, 20.20it/s]
%|█▍        | 11/79 [00:00<00:03, 20.81it/s]
%|█▊        | 14/79 [00:00<00:03, 20.98it/s]
%|██▏       | 17/79 [00:00<00:02, 20.85it/s]
%|██▌       | 20/79 [00:00<00:02, 21.21it/s]
%|██▉       | 23/79 [00:01<00:02, 20.99it/s]
%|███▎      | 26/79 [00:01<00:02, 21.30it/s]
%|███▋      | 29/79 [00:01<00:02, 21.28it/s]
%|████      | 32/79 [00:01<00:02, 21.51it/s]
%|████▍     | 35/79 [00:01<00:02, 21.49it/s]
%|████▊     | 38/79 [00:01<00:01, 22.25it/s]
%|█████▏    | 41/79 [00:01<00:01, 22.09it/s]
%|█████▌    | 44/79 [00:02<00:01, 21.16it/s]
%|█████▉    | 47/79 [00:02<00:01, 21.14it/s]
%|██████▎   | 50/79 [00:02<00:01, 21.08it/s]
%|██████▋   | 53/79 [00:02<00:01, 21.83it/s]
%|███████   | 56/79 [00:02<00:01, 21.07it/s]
%|███████▍  | 59/79 [00:02<00:00, 21.29it/s]
%|███████▊  | 62/79 [00:02<00:00, 21.62it/s]
%|████████▏ | 65/79 [00:03<00:00, 21.83it/s]
%|████████▌ | 68/79 [00:03<00:00, 21.60it/s]
%|████████▉ | 71/79 [00:03<00:00, 21.54it/s]
%|█████████▎| 74/79 [00:03<00:00, 21.61it/s]
100%|██████████| 79/79 [00:03<00:00, 21.56it/s]
Epoch: [10/10]	 Seen Samples: [99840/100000]	Train Loss: 564.3492824847882	Time: 0:00:13.033734: : 10it [02:09, 12.99s/it]

%|          | 0/79 [00:00<?, ?it/s]
%|▍         | 3/79 [00:00<00:03, 20.48it/s]
%|▊         | 6/79 [00:00<00:03, 21.31it/s]
%|█▏        | 9/79 [00:00<00:03, 20.65it/s]
%|█▌        | 12/79 [00:00<00:03, 20.73it/s]
%|█▉        | 15/79 [00:00<00:03, 20.72it/s]
%|██▎       | 18/79 [00:00<00:02, 21.33it/s]
%|██▋       | 21/79 [00:00<00:02, 21.87it/s]
%|███       | 24/79 [00:01<00:02, 22.21it/s]
%|███▍      | 27/79 [00:01<00:02, 22.66it/s]
%|███▊      | 30/79 [00:01<00:02, 22.13it/s]
%|████▏     | 33/79 [00:01<00:02, 21.36it/s]
%|████▌     | 36/79 [00:01<00:01, 21.76it/s]
%|████▉     | 39/79 [00:01<00:01, 21.48it/s]
%|█████▎    | 42/79 [00:01<00:01, 21.52it/s]
%|█████▋    | 45/79 [00:02<00:01, 21.34it/s]
%|██████    | 48/79 [00:02<00:01, 21.31it/s]
%|██████▍   | 51/79 [00:02<00:01, 21.36it/s]
%|██████▊   | 54/79 [00:02<00:01, 21.57it/s]
%|███████▏  | 57/79 [00:02<00:01, 21.72it/s]
%|███████▌  | 60/79 [00:02<00:00, 22.28it/s]
%|███████▉  | 63/79 [00:02<00:00, 22.71it/s]
%|████████▎ | 66/79 [00:03<00:00, 22.07it/s]
%|████████▋ | 69/79 [00:03<00:00, 22.25it/s]
%|█████████ | 72/79 [00:03<00:00, 22.00it/s]
%|█████████▍| 75/79 [00:03<00:00, 22.50it/s]
100%|██████████| 79/79 [00:03<00:00, 21.88it/s]
Epoch: [10/10]	 Seen Samples: [99840/100000]	Train Loss: 567.5480266473232	Time: 0:00:13.915984: : 10it [02:18, 13.89s/it]

%|          | 0/79 [00:00<?, ?it/s]
%|▎         | 2/79 [00:00<00:04, 16.22it/s]
%|▌         | 4/79 [00:00<00:04, 17.91it/s]
%|▊         | 6/79 [00:00<00:03, 18.38it/s]
%|█▏        | 9/79 [00:00<00:03, 19.73it/s]
%|█▌        | 12/79 [00:00<00:03, 20.07it/s]
%|█▉        | 15/79 [00:00<00:03, 20.25it/s]
%|██▎       | 18/79 [00:00<00:02, 20.45it/s]
%|██▋       | 21/79 [00:01<00:02, 21.04it/s]
%|███       | 24/79 [00:01<00:02, 20.52it/s]
%|███▍      | 27/79 [00:01<00:02, 20.44it/s]
%|███▊      | 30/79 [00:01<00:02, 20.68it/s]
%|████▏     | 33/79 [00:01<00:02, 20.57it/s]
%|████▌     | 36/79 [00:01<00:02, 20.32it/s]
%|████▉     | 39/79 [00:01<00:01, 20.18it/s]
%|█████▎    | 42/79 [00:02<00:01, 20.48it/s]
%|█████▋    | 45/79 [00:02<00:01, 20.41it/s]
%|██████    | 48/79 [00:02<00:01, 20.21it/s]
%|██████▍   | 51/79 [00:02<00:01, 20.35it/s]
%|██████▊   | 54/79 [00:02<00:01, 20.41it/s]
%|███████▏  | 57/79 [00:02<00:01, 20.63it/s]
%|███████▌  | 60/79 [00:02<00:00, 20.33it/s]
%|███████▉  | 63/79 [00:03<00:00, 20.32it/s]
%|████████▎ | 66/79 [00:03<00:00, 20.52it/s]
%|████████▋ | 69/79 [00:03<00:00, 20.35it/s]
%|█████████ | 72/79 [00:03<00:00, 20.58it/s]
%|█████████▍| 75/79 [00:03<00:00, 20.25it/s]
100%|██████████| 79/79 [00:03<00:00, 20.44it/s]
Epoch: [10/10]	 Seen Samples: [99840/100000]	Train Loss: 575.0231692974384	Time: 0:00:13.093948: : 10it [02:11, 13.16s/it]

%|          | 0/79 [00:00<?, ?it/s]
%|▎         | 2/79 [00:00<00:04, 17.33it/s]
%|▋         | 5/79 [00:00<00:03, 20.22it/s]
%|█         | 8/79 [00:00<00:03, 20.63it/s]
%|█▍        | 11/79 [00:00<00:03, 20.10it/s]
%|█▊        | 14/79 [00:00<00:03, 20.21it/s]
%|██▏       | 17/79 [00:00<00:03, 20.60it/s]
%|██▌       | 20/79 [00:00<00:02, 20.73it/s]
%|██▉       | 23/79 [00:01<00:02, 20.33it/s]
%|███▎      | 26/79 [00:01<00:02, 20.35it/s]
%|███▋      | 29/79 [00:01<00:02, 20.02it/s]
%|████      | 32/79 [00:01<00:02, 20.68it/s]
%|████▍     | 35/79 [00:01<00:02, 20.91it/s]
%|████▊     | 38/79 [00:01<00:01, 20.56it/s]
%|█████▏    | 41/79 [00:02<00:01, 20.39it/s]
%|█████▌    | 44/79 [00:02<00:01, 20.19it/s]
%|█████▉    | 47/79 [00:02<00:01, 20.54it/s]
%|██████▎   | 50/79 [00:02<00:01, 20.64it/s]
%|██████▋   | 53/79 [00:02<00:01, 19.95it/s]
%|███████   | 56/79 [00:02<00:01, 19.87it/s]
%|███████▍  | 59/79 [00:02<00:00, 20.15it/s]
%|███████▊  | 62/79 [00:03<00:00, 20.43it/s]
%|████████▏ | 65/79 [00:03<00:00, 20.67it/s]
%|████████▌ | 68/79 [00:03<00:00, 20.21it/s]
%|████████▉ | 71/79 [00:03<00:00, 20.33it/s]
%|█████████▎| 74/79 [00:03<00:00, 20.64it/s]
100%|██████████| 79/79 [00:03<00:00, 20.56it/s]
Epoch: [10/10]	 Seen Samples: [99840/100000]	Train Loss: 591.3800296294384	Time: 0:00:14.666457: : 10it [02:26, 14.70s/it]

%|          | 0/79 [00:00<?, ?it/s]
%|▎         | 2/79 [00:00<00:04, 16.84it/s]
%|▌         | 4/79 [00:00<00:04, 18.21it/s]
%|▉         | 7/79 [00:00<00:03, 19.99it/s]
%|█▎        | 10/79 [00:00<00:03, 20.36it/s]
%|█▋        | 13/79 [00:00<00:03, 20.55it/s]
%|██        | 16/79 [00:00<00:02, 21.17it/s]
%|██▍       | 19/79 [00:00<00:02, 20.72it/s]
%|██▊       | 22/79 [00:01<00:02, 20.83it/s]
%|███▏      | 25/79 [00:01<00:02, 21.03it/s]
%|███▌      | 28/79 [00:01<00:02, 20.74it/s]
%|███▉      | 31/79 [00:01<00:02, 21.15it/s]
%|████▎     | 34/79 [00:01<00:02, 21.03it/s]
%|████▋     | 37/79 [00:01<00:01, 21.17it/s]
%|█████     | 40/79 [00:01<00:01, 21.13it/s]
%|█████▍    | 43/79 [00:02<00:01, 20.86it/s]
%|█████▊    | 46/79 [00:02<00:01, 21.05it/s]
%|██████▏   | 49/79 [00:02<00:01, 20.88it/s]
%|██████▌   | 52/79 [00:02<00:01, 21.28it/s]
%|██████▉   | 55/79 [00:02<00:01, 21.22it/s]
%|███████▎  | 58/79 [00:02<00:00, 21.16it/s]
%|███████▋  | 61/79 [00:02<00:00, 21.18it/s]
%|████████  | 64/79 [00:03<00:00, 20.96it/s]
%|████████▍ | 67/79 [00:03<00:00, 21.18it/s]
%|████████▊ | 70/79 [00:03<00:00, 21.22it/s]
%|█████████▏| 73/79 [00:03<00:00, 21.46it/s]
%|█████████▌| 76/79 [00:03<00:00, 21.83it/s]
100%|██████████| 79/79 [00:03<00:00, 21.18it/s]
Epoch: [10/10]	 Seen Samples: [99840/100000]	Train Loss: 612.2596858097957	Time: 0:00:14.440261: : 10it [02:23, 14.37s/it]

%|          | 0/79 [00:00<?, ?it/s]
%|▎         | 2/79 [00:00<00:03, 19.95it/s]
%|▌         | 4/79 [00:00<00:03, 19.91it/s]
%|▉         | 7/79 [00:00<00:03, 20.20it/s]
%|█▎        | 10/79 [00:00<00:03, 20.40it/s]
%|█▋        | 13/79 [00:00<00:03, 20.86it/s]
%|██        | 16/79 [00:00<00:02, 21.01it/s]
%|██▍       | 19/79 [00:00<00:02, 21.42it/s]
%|██▊       | 22/79 [00:01<00:02, 21.21it/s]
%|███▏      | 25/79 [00:01<00:02, 20.99it/s]
%|███▌      | 28/79 [00:01<00:02, 20.89it/s]
%|███▉      | 31/79 [00:01<00:02, 21.16it/s]
%|████▎     | 34/79 [00:01<00:02, 21.70it/s]
%|████▋     | 37/79 [00:01<00:02, 20.91it/s]
%|█████     | 40/79 [00:01<00:01, 20.81it/s]
%|█████▍    | 43/79 [00:02<00:01, 20.99it/s]
%|█████▊    | 46/79 [00:02<00:01, 20.68it/s]
%|██████▏   | 49/79 [00:02<00:01, 21.16it/s]
%|██████▌   | 52/79 [00:02<00:01, 20.50it/s]
%|██████▉   | 55/79 [00:02<00:01, 21.10it/s]
%|███████▎  | 58/79 [00:02<00:00, 21.10it/s]
%|███████▋  | 61/79 [00:02<00:00, 21.39it/s]
%|████████  | 64/79 [00:03<00:00, 21.10it/s]
%|████████▍ | 67/79 [00:03<00:00, 22.05it/s]
%|████████▊ | 70/79 [00:03<00:00, 20.85it/s]
%|█████████▏| 73/79 [00:03<00:00, 21.80it/s]
%|█████████▌| 76/79 [00:03<00:00, 21.12it/s]
100%|██████████| 79/79 [00:03<00:00, 21.27it/s]
Epoch: [10/10]	 Seen Samples: [99840/100000]	Train Loss: 627.9268771440555	Time: 0:00:14.758820: : 10it [02:27, 14.75s/it]

%|          | 0/79 [00:00<?, ?it/s]
%|▎         | 2/79 [00:00<00:04, 18.42it/s]
%|▋         | 5/79 [00:00<00:03, 20.94it/s]
%|█         | 8/79 [00:00<00:03, 20.62it/s]
%|█▍        | 11/79 [00:00<00:03, 20.12it/s]
%|█▊        | 14/79 [00:00<00:03, 20.59it/s]
%|██▏       | 17/79 [00:00<00:03, 20.29it/s]
%|██▌       | 20/79 [00:00<00:02, 20.59it/s]
%|██▉       | 23/79 [00:01<00:02, 20.41it/s]
%|███▎      | 26/79 [00:01<00:02, 20.27it/s]
%|███▋      | 29/79 [00:01<00:02, 20.36it/s]
%|████      | 32/79 [00:01<00:02, 20.24it/s]
%|████▍     | 35/79 [00:01<00:02, 20.38it/s]
%|████▊     | 38/79 [00:01<00:02, 19.92it/s]
%|█████▏    | 41/79 [00:02<00:01, 20.28it/s]
%|█████▌    | 44/79 [00:02<00:01, 19.87it/s]
%|█████▊    | 46/79 [00:02<00:01, 19.81it/s]
%|██████▏   | 49/79 [00:02<00:01, 20.59it/s]
%|██████▌   | 52/79 [00:02<00:01, 21.02it/s]
%|██████▉   | 55/79 [00:02<00:01, 21.15it/s]
%|███████▎  | 58/79 [00:02<00:00, 21.50it/s]
%|███████▋  | 61/79 [00:02<00:00, 20.71it/s]
%|████████  | 64/79 [00:03<00:00, 20.42it/s]
%|████████▍ | 67/79 [00:03<00:00, 20.93it/s]
%|████████▊ | 70/79 [00:03<00:00, 20.06it/s]
%|█████████▏| 73/79 [00:03<00:00, 20.26it/s]
%|█████████▌| 76/79 [00:03<00:00, 20.34it/s]
100%|██████████| 79/79 [00:03<00:00, 20.58it/s]
Epoch: [10/10]	 Seen Samples: [99840/100000]	Train Loss: 648.4994371854342	Time: 0:00:17.075728: : 10it [02:49, 16.91s/it]

%|          | 0/79 [00:00<?, ?it/s]
%|▎         | 2/79 [00:00<00:04, 17.44it/s]
%|▋         | 5/79 [00:00<00:03, 19.50it/s]
%|█         | 8/79 [00:00<00:03, 20.45it/s]
%|█▍        | 11/79 [00:00<00:03, 21.43it/s]
%|█▊        | 14/79 [00:00<00:03, 21.07it/s]
%|██▏       | 17/79 [00:00<00:02, 21.02it/s]
%|██▌       | 20/79 [00:00<00:02, 20.66it/s]
%|██▉       | 23/79 [00:01<00:02, 20.71it/s]
%|███▎      | 26/79 [00:01<00:02, 21.26it/s]
%|███▋      | 29/79 [00:01<00:02, 20.89it/s]
%|████      | 32/79 [00:01<00:02, 21.42it/s]
%|████▍     | 35/79 [00:01<00:02, 21.00it/s]
%|████▊     | 38/79 [00:01<00:01, 21.14it/s]
%|█████▏    | 41/79 [00:01<00:01, 20.60it/s]
%|█████▌    | 44/79 [00:02<00:01, 20.56it/s]
%|█████▉    | 47/79 [00:02<00:01, 20.63it/s]
%|██████▎   | 50/79 [00:02<00:01, 21.03it/s]
%|██████▋   | 53/79 [00:02<00:01, 20.22it/s]
%|███████   | 56/79 [00:02<00:01, 20.10it/s]
%|███████▍  | 59/79 [00:02<00:01, 19.97it/s]
%|███████▊  | 62/79 [00:03<00:00, 19.98it/s]
%|████████▏ | 65/79 [00:03<00:00, 19.69it/s]
%|████████▍ | 67/79 [00:03<00:00, 19.66it/s]
%|████████▊ | 70/79 [00:03<00:00, 19.78it/s]
%|█████████▏| 73/79 [00:03<00:00, 19.75it/s]
%|█████████▍| 75/79 [00:03<00:00, 19.79it/s]
100%|██████████| 79/79 [00:03<00:00, 20.61it/s]
Epoch: [10/10]	 Seen Samples: [99840/100000]	Train Loss: 667.6464223617162	Time: 0:00:16.117895: : 10it [02:41, 16.14s/it]

%|          | 0/79 [00:00<?, ?it/s]
%|▎         | 2/79 [00:00<00:04, 15.78it/s]
%|▌         | 4/79 [00:00<00:04, 17.08it/s]
%|▊         | 6/79 [00:00<00:04, 17.79it/s]
%|█▏        | 9/79 [00:00<00:03, 19.07it/s]
%|█▍        | 11/79 [00:00<00:03, 18.74it/s]
%|█▊        | 14/79 [00:00<00:03, 20.42it/s]
%|██▏       | 17/79 [00:00<00:02, 21.16it/s]
%|██▌       | 20/79 [00:01<00:02, 20.75it/s]
%|██▉       | 23/79 [00:01<00:02, 21.44it/s]
%|███▎      | 26/79 [00:01<00:02, 22.34it/s]
%|███▋      | 29/79 [00:01<00:02, 21.36it/s]
%|████      | 32/79 [00:01<00:02, 21.31it/s]
%|████▍     | 35/79 [00:01<00:02, 21.07it/s]
%|████▊     | 38/79 [00:01<00:01, 21.10it/s]
%|█████▏    | 41/79 [00:02<00:01, 21.07it/s]
%|█████▌    | 44/79 [00:02<00:01, 19.98it/s]
%|█████▉    | 47/79 [00:02<00:01, 20.16it/s]
%|██████▎   | 50/79 [00:02<00:01, 20.91it/s]
%|██████▋   | 53/79 [00:02<00:01, 20.73it/s]
%|███████   | 56/79 [00:02<00:01, 20.50it/s]
%|███████▍  | 59/79 [00:02<00:00, 21.13it/s]
%|███████▊  | 62/79 [00:02<00:00, 21.42it/s]
%|████████▏ | 65/79 [00:03<00:00, 22.03it/s]
%|████████▌ | 68/79 [00:03<00:00, 21.08it/s]
%|████████▉ | 71/79 [00:03<00:00, 20.92it/s]
%|█████████▎| 74/79 [00:03<00:00, 21.80it/s]
100%|██████████| 79/79 [00:03<00:00, 21.03it/s]
Epoch: [10/10]	 Seen Samples: [99840/100000]	Train Loss: 685.8992442595653	Time: 0:00:16.455629: : 10it [02:47, 16.70s/it]

%|          | 0/79 [00:00<?, ?it/s]
%|▍         | 3/79 [00:00<00:03, 20.59it/s]
%|▊         | 6/79 [00:00<00:03, 20.71it/s]
%|█▏        | 9/79 [00:00<00:03, 20.75it/s]
%|█▌        | 12/79 [00:00<00:03, 20.39it/s]
%|█▉        | 15/79 [00:00<00:03, 20.73it/s]
%|██▎       | 18/79 [00:00<00:02, 20.52it/s]
%|██▋       | 21/79 [00:01<00:02, 20.70it/s]
%|███       | 24/79 [00:01<00:02, 20.75it/s]
%|███▍      | 27/79 [00:01<00:02, 21.04it/s]
%|███▊      | 30/79 [00:01<00:02, 21.02it/s]
%|████▏     | 33/79 [00:01<00:02, 20.69it/s]
%|████▌     | 36/79 [00:01<00:02, 20.82it/s]
%|████▉     | 39/79 [00:01<00:01, 20.47it/s]
%|█████▎    | 42/79 [00:02<00:01, 20.39it/s]
%|█████▋    | 45/79 [00:02<00:01, 21.65it/s]
%|██████    | 48/79 [00:02<00:01, 21.05it/s]
%|██████▍   | 51/79 [00:02<00:01, 20.99it/s]
%|██████▊   | 54/79 [00:02<00:01, 21.03it/s]
%|███████▏  | 57/79 [00:02<00:01, 21.43it/s]
%|███████▌  | 60/79 [00:02<00:00, 21.43it/s]
%|███████▉  | 63/79 [00:03<00:00, 21.67it/s]
%|████████▎ | 66/79 [00:03<00:00, 21.62it/s]
%|████████▋ | 69/79 [00:03<00:00, 21.42it/s]
%|█████████ | 72/79 [00:03<00:00, 22.24it/s]
%|█████████▍| 75/79 [00:03<00:00, 21.43it/s]
100%|██████████| 79/79 [00:03<00:00, 21.29it/s]
Epoch: [10/10]	 Seen Samples: [99840/100000]	Train Loss: 709.9896518022587	Time: 0:00:17.163973: : 10it [02:50, 17.05s/it]

%|          | 0/79 [00:00<?, ?it/s]
%|▎         | 2/79 [00:00<00:04, 17.14it/s]
%|▋         | 5/79 [00:00<00:03, 19.22it/s]
%|█         | 8/79 [00:00<00:03, 20.91it/s]
%|█▍        | 11/79 [00:00<00:03, 20.85it/s]
%|█▊        | 14/79 [00:00<00:03, 21.29it/s]
%|██▏       | 17/79 [00:00<00:03, 20.57it/s]
%|██▌       | 20/79 [00:00<00:02, 20.94it/s]
%|██▉       | 23/79 [00:01<00:02, 20.89it/s]
%|███▎      | 26/79 [00:01<00:02, 20.63it/s]
%|███▋      | 29/79 [00:01<00:02, 20.17it/s]
%|████      | 32/79 [00:01<00:02, 20.79it/s]
%|████▍     | 35/79 [00:01<00:02, 20.44it/s]
%|████▊     | 38/79 [00:01<00:02, 20.39it/s]
%|█████▏    | 41/79 [00:01<00:01, 20.68it/s]
%|█████▌    | 44/79 [00:02<00:01, 20.77it/s]
%|█████▉    | 47/79 [00:02<00:01, 20.96it/s]
%|██████▎   | 50/79 [00:02<00:01, 20.82it/s]
%|██████▋   | 53/79 [00:02<00:01, 20.39it/s]
%|███████   | 56/79 [00:02<00:01, 20.52it/s]
%|███████▍  | 59/79 [00:02<00:00, 20.05it/s]
%|███████▊  | 62/79 [00:03<00:00, 20.37it/s]
%|████████▏ | 65/79 [00:03<00:00, 21.00it/s]
%|████████▌ | 68/79 [00:03<00:00, 20.78it/s]
%|████████▉ | 71/79 [00:03<00:00, 20.40it/s]
%|█████████▎| 74/79 [00:03<00:00, 20.97it/s]
100%|██████████| 79/79 [00:03<00:00, 20.75it/s]

[2026-07-24 13:01:03] Encoding 10,000 documents with ParsBERT mean-pooled encoder sensitivity: HooshvareLab/bert-base-parsbert-uncased

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertModel LOAD REPORT from: HooshvareLab/bert-base-parsbert-uncased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.decoder.bias               | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
C:\Users\Amir\anaconda3\envs\persian_topic_env\lib\site-packages\transformers\models\bert\tokenization_bert.py:104: DeprecationWarning: Deprecated in 0.9.0: WordPiece.__init__ will not create from files anymore, try `WordPiece.from_file` instead
  self._tokenizer = Tokenizer(WordPiece(self._vocab, unk_token=str(unk_token)))
C:\Users\Amir\AppData\Local\Temp\ipykernel_2532\667818745.py:351: FutureWarning: The `get_word_embedding_dimension` method has been renamed to `get_embedding_dimension`.
  if hasattr(transformer, "get_word_embedding_dimension"):
C:\Users\Amir\AppData\Local\Temp\ipykernel_2532\667818745.py:352: FutureWarning: The `get_word_embedding_dimension` method has been renamed to `get_embedding_dimension`.
  dimension = transformer.get_word_embedding_dimension()

Batches:   0%|          | 0/625 [00:00<?, ?it/s]

C:\Users\Amir\anaconda3\envs\persian_topic_env\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

BERTopic-ParsBERT seed=42:   0%|          | 0/13 [00:00<?, ?it/s]

C:\Users\Amir\anaconda3\envs\persian_topic_env\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

BERTopic-ParsBERT seed=123:   0%|          | 0/13 [00:00<?, ?it/s]

C:\Users\Amir\anaconda3\envs\persian_topic_env\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

BERTopic-ParsBERT seed=456:   0%|          | 0/13 [00:00<?, ?it/s]

All topic-model runs: 156 core runs + 39 ParsBERT sensitivity runs

,model,model_family,benchmark_role,encoder,k,seed,c_v,c_npmi,topic_coherence_sd,diversity,distinctness,raw_topic_count,canonical_topic_count,valid_topic_count,valid_topic_fraction,mean_matched_words_per_topic,reference_match_rate,training_seconds,training_documents,shared_vocabulary_size,converged,n_iter,encoder_model_id,actual_topics,minimum_cluster_size,maximum_cluster_size,topic_level_vocabulary,empty_topic_documents_before_fit,c_tfidf_used,ctfidf_implementation,cluster_labels,lexical_input,contextual_input,topic_validation_documents_reserved,topic_validation_topic_distribution_shape,epochs,batch_size,controlled_bow_vocabulary,training_implementation
0,BERTopic,BERTopic,core,multilingual-MiniLM,5,42,0.556283,0.232046,0.159480,0.940000,0.983626,5,5,5,1.0,10.000000,1.000000,11.672734,10000,10000,NaN,NaN,sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2,5.0,325.0,5433.0,10000.0,0.0,True,BERTopic ClassTfidfTransformer (official manual-label workflow),external UMAP+KMeans labels passed via y,clean Persian whitespace-tokenized unigrams,normalized raw Persian text,NaN,NaN,NaN,NaN,NaN,NaN
1,BERTopic,BERTopic,core,multilingual-MiniLM,5,123,0.556283,0.232046,0.159480,0.940000,0.983626,5,5,5,1.0,10.000000,1.000000,10.988305,10000,10000,NaN,NaN,sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2,5.0,325.0,5435.0,10000.0,0.0,True,BERTopic ClassTfidfTransformer (official manual-label workflow),external UMAP+KMeans labels passed via y,clean Persian whitespace-tokenized unigrams,normalized raw Persian text,NaN,NaN,NaN,NaN,NaN,NaN
2,BERTopic,BERTopic,core,multilingual-MiniLM,5,456,0.526064,0.174995,0.172617,0.920000,0.977778,5,5,5,1.0,10.000000,1.000000,11.182721,10000,10000,NaN,NaN,sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2,5.0,760.0,3443.0,10000.0,0.0,True,BERTopic ClassTfidfTransformer (official manual-label workflow),external UMAP+KMeans labels passed via y,clean Persian whitespace-tokenized unigrams,normalized raw Persian text,NaN,NaN,NaN,NaN,NaN,NaN
3,BERTopic,BERTopic,core,multilingual-MiniLM,10,42,0.639943,0.254543,0.121091,0.860000,0.982206,10,10,10,1.0,10.000000,1.000000,13.518254,10000,10000,NaN,NaN,sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2,10.0,170.0,2153.0,10000.0,0.0,True,BERTopic ClassTfidfTransformer (official manual-label workflow),external UMAP+KMeans labels passed via y,clean Persian whitespace-tokenized unigrams,normalized raw Persian text,NaN,NaN,NaN,NaN,NaN,NaN
4,BERTopic,BERTopic,core,multilingual-MiniLM,10,123,0.639943,0.254543,0.121091,0.860000,0.982206,10,10,10,1.0,10.000000,1.000000,12.980780,10000,10000,NaN,NaN,sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2,10.0,171.0,2127.0,10000.0,0.0,True,BERTopic ClassTfidfTransformer (official manual-label workflow),external UMAP+KMeans labels passed via y,clean Persian whitespace-tokenized unigrams,normalized raw Persian text,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190,BERTopic-ParsBERT,BERTopic,encoder_sensitivity,ParsBERT-mean-pooling,350,123,0.453204,-0.155166,0.094346,0.644699,0.994380,350,350,350,1.0,9.648571,0.964857,99.276159,10000,10000,NaN,NaN,HooshvareLab/bert-base-parsbert-uncased,350.0,1.0,83.0,10000.0,0.0,True,BERTopic ClassTfidfTransformer (official manual-label workflow),external UMAP+KMeans labels passed via y,clean Persian whitespace-tokenized unigrams,normalized raw Persian text,NaN,NaN,NaN,NaN,NaN,NaN
191,BERTopic-ParsBERT,BERTopic,encoder_sensitivity,ParsBERT-mean-pooling,350,456,0.449913,-0.155463,0.093504,0.644044,0.994650,350,350,350,1.0,9.657143,0.965714,99.894992,10000,10000,NaN,NaN,HooshvareLab/bert-base-parsbert-uncased,350.0,1.0,98.0,10000.0,0.0,True,BERTopic ClassTfidfTransformer (official manual-label workflow),external UMAP+KMeans labels passed via y,clean Persian whitespace-tokenized unigrams,normalized raw Persian text,NaN,NaN,NaN,NaN,NaN,NaN
192,BERTopic-ParsBERT,BERTopic,encoder_sensitivity,ParsBERT-mean-pooling,400,42,0.454306,-0.164758,0.097555,0.629166,0.994749,400,400,400,1.0,9.645000,0.964500,111.076798,10000,10000,NaN,NaN,HooshvareLab/bert-base-parsbert-uncased,400.0,4.0,74.0,10000.0,0.0,True,BERTopic ClassTfidfTransformer (official manual-label workflow),external UMAP+KMeans labels passed via y,clean Persian whitespace-tokenized unigrams,normalized raw Persian text,NaN,NaN,NaN,NaN,NaN,NaN
193,BERTopic-ParsBERT,BERTopic,encoder_sensitivity,ParsBERT-mean-pooling,400,123,0.452413,-0.161464,0.097606,0.626222,0.994353,400,400,400,1.0,9.657500,0.965750,111.060922,10000,10000,NaN,NaN,HooshvareLab/bert-base-parsbert-uncased,400.0,3.0,107.0,10000.0,0.0,True,BERTopic ClassTfidfTransformer (official manual-label workflow),external UMAP+KMeans labels passed via y,clean Persian whitespace-tokenized unigrams,normalized raw Persian text,NaN,NaN,NaN,NaN,NaN,NaN
194,BERTopic-ParsBERT,BERTopic,encoder_sensitivity,ParsBERT-mean-pooling,400,456,0.456601,-0.163280,0.097591,0.632213,0.994444,400,400,400,1.0,9.662500,0.966250,113.115707,10000,10000,NaN,NaN,HooshvareLab/bert-base-parsbert-uncased,400.0,2.0,83.0,10000.0,0.0,True,BERTopic ClassTfidfTransformer (official manual-label workflow),external UMAP+KMeans labels passed via y,clean Persian whitespace-tokenized unigrams,normalized raw Persian text,NaN,NaN,NaN,NaN,NaN,NaN

Core four-model run-level results

,model,model_family,benchmark_role,encoder,k,seed,c_v,c_npmi,topic_coherence_sd,diversity,distinctness,raw_topic_count,canonical_topic_count,valid_topic_count,valid_topic_fraction,mean_matched_words_per_topic,reference_match_rate,training_seconds,training_documents,shared_vocabulary_size,converged,n_iter,encoder_model_id,actual_topics,minimum_cluster_size,maximum_cluster_size,topic_level_vocabulary,empty_topic_documents_before_fit,c_tfidf_used,ctfidf_implementation,cluster_labels,lexical_input,contextual_input,topic_validation_documents_reserved,topic_validation_topic_distribution_shape,epochs,batch_size,controlled_bow_vocabulary,training_implementation
0,BERTopic,BERTopic,core,multilingual-MiniLM,5,42,0.556283,0.232046,0.159480,0.940000,0.983626,5,5,5,1.0,10.000000,1.000000,11.672734,10000,10000,NaN,NaN,sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2,5.0,325.0,5433.0,10000.0,0.0,True,BERTopic ClassTfidfTransformer (official manual-label workflow),external UMAP+KMeans labels passed via y,clean Persian whitespace-tokenized unigrams,normalized raw Persian text,NaN,NaN,NaN,NaN,NaN,NaN
1,BERTopic,BERTopic,core,multilingual-MiniLM,5,123,0.556283,0.232046,0.159480,0.940000,0.983626,5,5,5,1.0,10.000000,1.000000,10.988305,10000,10000,NaN,NaN,sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2,5.0,325.0,5435.0,10000.0,0.0,True,BERTopic ClassTfidfTransformer (official manual-label workflow),external UMAP+KMeans labels passed via y,clean Persian whitespace-tokenized unigrams,normalized raw Persian text,NaN,NaN,NaN,NaN,NaN,NaN
2,BERTopic,BERTopic,core,multilingual-MiniLM,5,456,0.526064,0.174995,0.172617,0.920000,0.977778,5,5,5,1.0,10.000000,1.000000,11.182721,10000,10000,NaN,NaN,sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2,5.0,760.0,3443.0,10000.0,0.0,True,BERTopic ClassTfidfTransformer (official manual-label workflow),external UMAP+KMeans labels passed via y,clean Persian whitespace-tokenized unigrams,normalized raw Persian text,NaN,NaN,NaN,NaN,NaN,NaN
3,BERTopic,BERTopic,core,multilingual-MiniLM,10,42,0.639943,0.254543,0.121091,0.860000,0.982206,10,10,10,1.0,10.000000,1.000000,13.518254,10000,10000,NaN,NaN,sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2,10.0,170.0,2153.0,10000.0,0.0,True,BERTopic ClassTfidfTransformer (official manual-label workflow),external UMAP+KMeans labels passed via y,clean Persian whitespace-tokenized unigrams,normalized raw Persian text,NaN,NaN,NaN,NaN,NaN,NaN
4,BERTopic,BERTopic,core,multilingual-MiniLM,10,123,0.639943,0.254543,0.121091,0.860000,0.982206,10,10,10,1.0,10.000000,1.000000,12.980780,10000,10000,NaN,NaN,sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2,10.0,171.0,2127.0,10000.0,0.0,True,BERTopic ClassTfidfTransformer (official manual-label workflow),external UMAP+KMeans labels passed via y,clean Persian whitespace-tokenized unigrams,normalized raw Persian text,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
151,NMF,NMF,core,None,350,123,0.548934,-0.245340,0.062479,0.096000,0.363121,350,350,350,1.0,9.997143,0.999714,143.797861,10000,10000,True,230.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
152,NMF,NMF,core,None,350,456,0.549020,-0.243226,0.061700,0.096571,0.367610,350,350,350,1.0,9.997143,0.999714,159.749748,10000,10000,True,260.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
153,NMF,NMF,core,None,400,42,0.550950,-0.258914,0.057956,0.083750,0.318369,400,400,400,1.0,9.997500,0.999750,158.958346,10000,10000,True,230.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
154,NMF,NMF,core,None,400,123,0.550025,-0.255674,0.056982,0.086500,0.330527,400,400,400,1.0,9.997500,0.999750,187.510518,10000,10000,True,270.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
155,NMF,NMF,core,None,400,456,0.550559,-0.258809,0.057227,0.085500,0.322468,400,400,400,1.0,9.997500,0.999750,174.032400,10000,10000,True,250.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Seed-aggregated topic-model results with 5,000-resample bootstrap intervals

,model,model_family,benchmark_role,encoder,k,seeds,valid_topic_fraction_mean,reference_match_rate_mean,training_seconds_mean,training_seconds_sd,c_v_mean,c_v_sd,c_v_bootstrap_ci_low,c_v_bootstrap_ci_high,c_npmi_mean,c_npmi_sd,c_npmi_bootstrap_ci_low,c_npmi_bootstrap_ci_high,diversity_mean,diversity_sd,diversity_bootstrap_ci_low,diversity_bootstrap_ci_high,distinctness_mean,distinctness_sd,distinctness_bootstrap_ci_low,distinctness_bootstrap_ci_high,stability
0,BERTopic,BERTopic,core,multilingual-MiniLM,5,3,1.0,1.000000,11.281253,0.352693,0.546210,0.017447,0.526064,0.556283,0.213029,0.032939,0.174995,0.232046,0.933333,0.011547,0.920000,0.940000,0.981676,0.003376,0.977778,0.983626,0.721789
1,BERTopic,BERTopic,core,multilingual-MiniLM,10,3,1.0,1.000000,13.118121,0.352156,0.637101,0.004921,0.631418,0.639943,0.250526,0.006957,0.242492,0.254543,0.860000,0.000000,0.860000,0.860000,0.982206,0.000000,0.982206,0.982206,0.987879
2,BERTopic,BERTopic,core,multilingual-MiniLM,15,3,1.0,0.993333,13.956450,0.285099,0.627965,0.013260,0.612653,0.635620,0.178854,0.017314,0.158862,0.188850,0.838912,0.001885,0.836735,0.840000,0.983841,0.000616,0.983129,0.984197,0.899182
3,BERTopic,BERTopic,core,multilingual-MiniLM,20,3,1.0,0.985000,14.878748,0.691835,0.578918,0.012552,0.564654,0.588276,0.127846,0.014675,0.111583,0.140101,0.808799,0.002931,0.807107,0.812183,0.985135,0.000166,0.985029,0.985327,0.901941
4,BERTopic,BERTopic,core,multilingual-MiniLM,30,3,1.0,0.988889,17.105445,0.230980,0.546043,0.011756,0.538970,0.559614,0.082531,0.011424,0.071114,0.093962,0.812570,0.008473,0.804714,0.821549,0.989015,0.001121,0.987745,0.989868,0.815588
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,NMF,NMF,core,None,200,3,1.0,0.999500,132.881331,8.590555,0.536375,0.000559,0.536018,0.537019,-0.162265,0.003184,-0.165497,-0.159132,0.175833,0.002754,0.173000,0.178500,0.604242,0.006211,0.598057,0.610479,0.983712
61,NMF,NMF,core,None,250,3,1.0,0.999600,130.835059,20.433033,0.542451,0.000295,0.542220,0.542784,-0.202444,0.000171,-0.202609,-0.202268,0.138267,0.000231,0.138000,0.138400,0.495632,0.000010,0.495621,0.495641,0.991577
62,NMF,NMF,core,None,300,3,1.0,0.999667,126.325367,1.729492,0.546686,0.000298,0.546401,0.546996,-0.226079,0.001195,-0.227455,-0.225305,0.114667,0.000882,0.113667,0.115333,0.423716,0.002924,0.420340,0.425430,0.993737
63,NMF,NMF,core,None,350,3,1.0,0.999714,150.953764,8.101424,0.548970,0.000045,0.548934,0.549020,-0.243445,0.001795,-0.245340,-0.241769,0.097143,0.001512,0.096000,0.098857,0.369095,0.006839,0.363121,0.376554,0.990823
64,NMF,NMF,core,None,400,3,1.0,0.999750,173.500422,14.283518,0.550511,0.000464,0.550025,0.550950,-0.257799,0.001841,-0.258914,-0.255674,0.085250,0.001392,0.083750,0.086500,0.323788,0.006186,0.318369,0.330527,0.990303

Primary matched comparison at common K=30

,model,model_family,benchmark_role,encoder,k,seeds,valid_topic_fraction_mean,reference_match_rate_mean,training_seconds_mean,training_seconds_sd,c_v_mean,c_v_sd,c_v_bootstrap_ci_low,c_v_bootstrap_ci_high,c_npmi_mean,c_npmi_sd,c_npmi_bootstrap_ci_low,c_npmi_bootstrap_ci_high,diversity_mean,diversity_sd,diversity_bootstrap_ci_low,diversity_bootstrap_ci_high,distinctness_mean,distinctness_sd,distinctness_bootstrap_ci_low,distinctness_bootstrap_ci_high,stability
0,BERTopic,BERTopic,core,multilingual-MiniLM,30,3,1.0,0.988889,17.105445,0.230980,0.546043,0.011756,0.538970,0.559614,0.082531,0.011424,0.071114,0.093962,0.812570,0.008473,0.804714,0.821549,0.989015,0.001121,0.987745,0.989868,0.815588
1,LDA,LDA,core,None,30,3,1.0,1.000000,86.158133,1.990793,0.521497,0.015000,0.504799,0.533830,0.062277,0.021771,0.038949,0.082056,0.716667,0.011547,0.710000,0.730000,0.971326,0.001837,0.969690,0.973314,0.378720
2,NMF,NMF,core,None,30,3,1.0,1.000000,18.697926,0.156333,0.497694,0.007968,0.490068,0.505964,0.162876,0.011360,0.152661,0.175111,0.545556,0.023413,0.523333,0.570000,0.947564,0.005277,0.941863,0.952277,0.785295
3,CTM,CTM,core,multilingual-MiniLM,30,3,1.0,1.000000,155.878748,4.527172,0.472204,0.009472,0.461361,0.478867,-0.072760,0.045493,-0.121539,-0.031487,0.691111,0.015396,0.673333,0.700000,0.978477,0.000668,0.977857,0.979185,0.221490

Metric-specific optima (no composite quality score)

                model       benchmark_role                encoder             metric    k     value
0            BERTopic                 core    multilingual-MiniLM           c_v_mean   10  0.637101
1            BERTopic                 core    multilingual-MiniLM        c_npmi_mean   10  0.250526
2            BERTopic                 core    multilingual-MiniLM     diversity_mean    5  0.933333
3            BERTopic                 core    multilingual-MiniLM  distinctness_mean  400  0.995897
4            BERTopic                 core    multilingual-MiniLM          stability   10  0.987879
5   BERTopic-ParsBERT  encoder_sensitivity  ParsBERT-mean-pooling           c_v_mean   10  0.586569
6   BERTopic-ParsBERT  encoder_sensitivity  ParsBERT-mean-pooling        c_npmi_mean   10  0.252213
7   BERTopic-ParsBERT  encoder_sensitivity  ParsBERT-mean-pooling     diversity_mean    5  0.960000
8   BERTopic-ParsBERT  encoder_sensitivity  ParsBERT-mean-pooling  distinctness_mean  400  0.994515
9   BERTopic-ParsBERT  encoder_sensitivity  ParsBERT-mean-pooling          stability   15  0.948822
10                CTM                 core    multilingual-MiniLM           c_v_mean   20  0.493161
11                CTM                 core    multilingual-MiniLM        c_npmi_mean   60 -0.065673
12                CTM                 core    multilingual-MiniLM     diversity_mean    5  0.933333
13                CTM                 core    multilingual-MiniLM  distinctness_mean  350  0.991034
14                CTM                 core    multilingual-MiniLM          stability   60  0.266192
15                LDA                 core                   None           c_v_mean   30  0.521497
16                LDA                 core                   None        c_npmi_mean   10  0.108828
17                LDA                 core                   None     diversity_mean  200  0.879333
18                LDA                 core                   None  distinctness_mean  200  0.998264
19                LDA                 core                   None          stability    5  0.558124
20                NMF                 core                   None           c_v_mean    5  0.622230
21                NMF                 core                   None        c_npmi_mean    5  0.344959
22                NMF                 core                   None     diversity_mean    5  0.880000
23                NMF                 core                   None  distinctness_mean    5  0.967251
24                NMF                 core                   None          stability    5  1.000000

Pareto-efficient core configurations across C_v, NPMI, diversity, distinctness, and stability

,model,model_family,benchmark_role,encoder,k,seeds,valid_topic_fraction_mean,reference_match_rate_mean,training_seconds_mean,training_seconds_sd,c_v_mean,c_v_sd,c_v_bootstrap_ci_low,c_v_bootstrap_ci_high,c_npmi_mean,c_npmi_sd,c_npmi_bootstrap_ci_low,c_npmi_bootstrap_ci_high,diversity_mean,diversity_sd,diversity_bootstrap_ci_low,diversity_bootstrap_ci_high,distinctness_mean,distinctness_sd,distinctness_bootstrap_ci_low,distinctness_bootstrap_ci_high,stability
0,BERTopic,BERTopic,core,multilingual-MiniLM,5,3,1.0,1.000000,11.281253,0.352693,0.546210,0.017447,0.526064,0.556283,0.213029,3.293863e-02,0.174995,0.232046,0.933333,0.011547,0.920000,0.940000,0.981676,0.003376,0.977778,0.983626,0.721789
1,BERTopic,BERTopic,core,multilingual-MiniLM,10,3,1.0,1.000000,13.118121,0.352156,0.637101,0.004921,0.631418,0.639943,0.250526,6.957303e-03,0.242492,0.254543,0.860000,0.000000,0.860000,0.860000,0.982206,0.000000,0.982206,0.982206,0.987879
2,BERTopic,BERTopic,core,multilingual-MiniLM,15,3,1.0,0.993333,13.956450,0.285099,0.627965,0.013260,0.612653,0.635620,0.178854,1.731358e-02,0.158862,0.188850,0.838912,0.001885,0.836735,0.840000,0.983841,0.000616,0.983129,0.984197,0.899182
3,BERTopic,BERTopic,core,multilingual-MiniLM,20,3,1.0,0.985000,14.878748,0.691835,0.578918,0.012552,0.564654,0.588276,0.127846,1.467524e-02,0.111583,0.140101,0.808799,0.002931,0.807107,0.812183,0.985135,0.000166,0.985029,0.985327,0.901941
4,BERTopic,BERTopic,core,multilingual-MiniLM,30,3,1.0,0.988889,17.105445,0.230980,0.546043,0.011756,0.538970,0.559614,0.082531,1.142411e-02,0.071114,0.093962,0.812570,0.008473,0.804714,0.821549,0.989015,0.001121,0.987745,0.989868,0.815588
5,BERTopic,BERTopic,core,multilingual-MiniLM,100,3,1.0,0.985000,30.411522,0.191320,0.472904,0.003675,0.469511,0.476807,-0.030621,5.899146e-03,-0.035120,-0.023942,0.728185,0.007961,0.719157,0.734203,0.990218,0.000560,0.989599,0.990687,0.766866
6,BERTopic,BERTopic,core,multilingual-MiniLM,150,3,1.0,0.979111,39.687396,0.317736,0.460587,0.002576,0.458541,0.463480,-0.078721,3.920091e-03,-0.082186,-0.074466,0.705188,0.000771,0.704743,0.706079,0.990731,0.000335,0.990363,0.991017,0.662531
7,BERTopic,BERTopic,core,multilingual-MiniLM,200,3,1.0,0.975833,50.230546,0.462409,0.453487,0.002813,0.450415,0.455937,-0.121208,4.746713e-03,-0.126593,-0.117631,0.706533,0.007750,0.700551,0.715288,0.992831,0.000145,0.992681,0.992969,0.643049
8,BERTopic,BERTopic,core,multilingual-MiniLM,250,3,1.0,0.972000,59.720268,0.340253,0.448600,0.002369,0.446271,0.451006,-0.149326,4.043778e-03,-0.152179,-0.144698,0.698196,0.005241,0.694589,0.704208,0.994128,0.000105,0.994007,0.994198,0.613665
9,BERTopic,BERTopic,core,multilingual-MiniLM,300,3,1.0,0.968444,72.769024,0.326490,0.447427,0.000534,0.446837,0.447878,-0.175360,3.783381e-04,-0.175716,-0.174963,0.689130,0.002964,0.685810,0.691511,0.994970,0.000227,0.994756,0.995208,0.593283
10,BERTopic,BERTopic,core,multilingual-MiniLM,350,3,1.0,0.966381,82.906462,1.112985,0.445749,0.002599,0.442989,0.448150,-0.199211,1.536245e-03,-0.200419,-0.197482,0.685823,0.003839,0.681753,0.689379,0.995737,0.000183,0.995530,0.995879,0.580312
11,BERTopic,BERTopic,core,multilingual-MiniLM,400,3,1.0,0.965750,98.594142,1.070061,0.451214,0.000763,0.450438,0.451963,-0.207658,3.699465e-03,-0.211700,-0.204440,0.670233,0.004942,0.664830,0.674524,0.995897,0.000297,0.995597,0.996191,0.565081
12,LDA,LDA,core,None,100,3,1.0,0.992667,205.663108,17.108879,0.490849,0.008811,0.480683,0.496269,-0.133165,5.000196e-03,-0.138598,-0.128756,0.829667,0.016623,0.812000,0.845000,0.994167,0.000782,0.993264,0.994627,0.212490
13,LDA,LDA,core,None,150,3,1.0,0.985778,242.488861,3.471445,0.496014,0.003836,0.492603,0.500166,-0.189982,3.182516e-03,-0.193179,-0.186815,0.864889,0.013537,0.849333,0.874000,0.997061,0.000488,0.996598,0.997570,0.184593
14,LDA,LDA,core,None,200,3,1.0,0.979333,279.665893,2.639534,0.490046,0.003834,0.485722,0.493034,-0.222623,3.375954e-03,-0.226061,-0.219313,0.879333,0.003253,0.876000,0.882500,0.998264,0.000135,0.998137,0.998405,0.166010
15,LDA,LDA,core,None,250,3,1.0,0.974667,313.460613,6.174076,0.493713,0.004302,0.489231,0.497810,-0.245361,5.561460e-03,-0.249750,-0.239106,0.856667,0.002663,0.854400,0.859600,0.998103,0.000091,0.998003,0.998181,0.171968
16,LDA,LDA,core,None,300,3,1.0,0.973778,353.869310,10.096249,0.491599,0.003836,0.487528,0.495146,-0.252021,3.235586e-03,-0.254552,-0.248375,0.832778,0.006432,0.827667,0.840000,0.998024,0.000278,0.997707,0.998222,0.180526
17,LDA,LDA,core,None,350,3,1.0,0.970571,379.400697,7.577573,0.492032,0.002147,0.490044,0.494309,-0.263083,1.122389e-03,-0.264378,-0.262404,0.791524,0.004860,0.786571,0.796286,0.996067,0.000115,0.995973,0.996195,0.204790
18,LDA,LDA,core,None,400,3,1.0,0.968583,400.800047,4.186437,0.486017,0.002217,0.483755,0.488185,-0.263765,5.605018e-03,-0.269392,-0.258182,0.748583,0.014518,0.734500,0.763500,0.993434,0.002535,0.991494,0.996303,0.216148
19,NMF,NMF,core,None,5,3,1.0,1.000000,9.468156,0.364525,0.622230,0.000000,0.622230,0.622230,0.344959,6.798700e-17,0.344959,0.344959,0.880000,0.000000,0.880000,0.880000,0.967251,0.000000,0.967251,0.967251,1.000000

Coherence-maximizing configuration for each model/encoder variant

,model,model_family,benchmark_role,encoder,k,seeds,valid_topic_fraction_mean,reference_match_rate_mean,training_seconds_mean,training_seconds_sd,c_v_mean,c_v_sd,c_v_bootstrap_ci_low,c_v_bootstrap_ci_high,c_npmi_mean,c_npmi_sd,c_npmi_bootstrap_ci_low,c_npmi_bootstrap_ci_high,diversity_mean,diversity_sd,diversity_bootstrap_ci_low,diversity_bootstrap_ci_high,distinctness_mean,distinctness_sd,distinctness_bootstrap_ci_low,distinctness_bootstrap_ci_high,stability
0,BERTopic,BERTopic,core,multilingual-MiniLM,10,3,1.0,1.000,13.118121,0.352156,0.637101,0.004921,0.631418,0.639943,0.250526,6.957303e-03,0.242492,0.254543,0.860000,0.000000,0.860,0.86,0.982206,0.000000,0.982206,0.982206,0.987879
1,NMF,NMF,core,None,5,3,1.0,1.000,9.468156,0.364525,0.622230,0.000000,0.622230,0.622230,0.344959,6.798700e-17,0.344959,0.344959,0.880000,0.000000,0.880,0.88,0.967251,0.000000,0.967251,0.967251,1.000000
2,BERTopic-ParsBERT,BERTopic,encoder_sensitivity,ParsBERT-mean-pooling,10,3,1.0,1.000,12.688086,0.254662,0.586569,0.004719,0.583571,0.592008,0.252213,8.799375e-03,0.242052,0.257295,0.786667,0.005774,0.780,0.79,0.965800,0.001100,0.964597,0.966754,0.799822
3,LDA,LDA,core,None,30,3,1.0,1.000,86.158133,1.990793,0.521497,0.015000,0.504799,0.533830,0.062277,2.177140e-02,0.038949,0.082056,0.716667,0.011547,0.710,0.73,0.971326,0.001837,0.969690,0.973314,0.378720
4,CTM,CTM,core,multilingual-MiniLM,20,3,1.0,0.995,148.839394,3.278685,0.493161,0.022098,0.469742,0.513644,-0.089281,4.427812e-03,-0.092597,-0.084253,0.771667,0.033292,0.735,0.80,0.980462,0.003000,0.977023,0.982543,0.224601

Representative topics from each coherence-maximizing configuration

       model              encoder   k  seed  topic_index                                                                             top_words
0   BERTopic  multilingual-MiniLM  10    42            0                      ایران | سال | شهر | کتاب | نام | حزب | کشور | دوره | عنوان | جنگ
1   BERTopic  multilingual-MiniLM  10    42            1     فیلم | نقش | تلویزیون | منتشر | آلبوم | کارگردانی | سال | بازیگر | ترانه | موسیقی
2   BERTopic  multilingual-MiniLM  10    42            2  جمعیت | نفر | روستا | خانوار | روستایی | توابع | سرشماری | بوده‌است | مسکونی | منطقه
3   BERTopic  multilingual-MiniLM  10    42            3            استفاده | تولید | سیستم | شرکت | صورت | توسط | مدل | معمولا | ایجاد | مواد
4   BERTopic  multilingual-MiniLM  10    42            4        تیم | بازی | فوتبال | باشگاه | مسابقات | ملی | اهل | مسابقه | قهرمانی | بازیکن
..       ...                  ...  ..   ...          ...                                                                                   ...
60       CTM  multilingual-MiniLM  20    42           15     به‌عنوان | اسفند | روستایی | صندوق | ثبت | واقع‌شده | محافظ | خانوار | توابع | سم
61       CTM  multilingual-MiniLM  20    42           16                      رنگ | گونه | سفید | جنس | قهوه | منشا | برگ | سبز | سرده | درمان
62       CTM  multilingual-MiniLM  20    42           17       بنیان | گران | تاریخچه | رفاه | هردو | نبوده | خیابانی | گلوله | درآمده | متصدی
63       CTM  multilingual-MiniLM  20    42           18              سال | مجلس | ایران | عنوان | فعالیت | طاهر | درگذشت | حضور | شعر | فرزند
64       CTM  multilingual-MiniLM  20    42           19           شده‌است | منطقه | جمعیت | شهر | واقع | قرار | نام | روستا | بوده‌است | جنوب

[65 rows x 6 columns]

Complete topic-word evidence contains 28,350 topic rows and is saved in the final JSON evidence.

        model model_family benchmark_role              encoder   k  seed  topic_index  word_count                                                                              top_words
0    BERTopic     BERTopic           core  multilingual-MiniLM   5    42            0          10                    سال | عنوان | نام | فیلم | استفاده | توسط | قرار | آن | ایران | کار
1    BERTopic     BERTopic           core  multilingual-MiniLM   5    42            1          10          جمعیت | واقع | نفر | شده‌است | مسکونی | روستا | مساحت | بالاتر | منطقه | دریا
2    BERTopic     BERTopic           core  multilingual-MiniLM   5    42            2          10         باشگاه | بازی | تیم | اهل | کرده‌است | فوتبال | مسابقات | اشاره | ملی | مسابقه
3    BERTopic     BERTopic           core  multilingual-MiniLM   5    42            3          10          کشف | فرودگاه | سیارک | باند | هزار | متری | همگانی | ارتفاع | دریا | شده‌است
4    BERTopic     BERTopic           core  multilingual-MiniLM   5    42            4          10       ثبت | واقع‌شده | به‌عنوان | شماره | تاریخ | اسفند | روستا | دهستان | مرکزی | سده
..        ...          ...            ...                  ...  ..   ...          ...         ...                                                                                    ...
195  BERTopic     BERTopic           core  multilingual-MiniLM  30   123           15          10       ثبت | واقع‌شده | به‌عنوان | شماره | اسفند | تاریخ | دهستان | روستا | مرکزی | سده
196  BERTopic     BERTopic           core  multilingual-MiniLM  30   123           16          10  سرشماری | شهری | جمعیت | نفر | میلادی | ایالت | شهرستان | جغرافیایی | کشور | بوده‌است
197  BERTopic     BERTopic           core  multilingual-MiniLM  30   123           17          10       جنگنده | شرکت | هواپیما | خودرو | موتور | پرواز | فروند | سامانه | هواگرد | موشک
198  BERTopic     BERTopic           core  multilingual-MiniLM  30   123           18          10                  حافظ | شعر | تهران | غزل | مسجد | ایران | محمد | اشعار | سید | موسیقی
199  BERTopic     BERTopic           core  multilingual-MiniLM  30   123           19          10                        باغ | موزه | ساختمان | شهر | بنا | برج | سنگ | تل | بازار | صحن

[200 rows x 9 columns]

Unscored topic human-audit template (complete template saved in JSON)

,model,k,seed,topic_index,top_words,proposed_label,semantic_coherence_1_to_5,intruder_word_if_any,annotator,notes
0,LDA,30,42,0,ویروس | جکسون | سلول | بیماری | پروتئین | ژن | ماهی | عصبی | عفونت | ملا,,,,,
1,LDA,30,42,3,نیرو | جنگ | ارتش | نمود | نظامی | شوروی | افغانستان | سرباز | نبرد | نیروی,,,,,
2,LDA,30,42,6,فیلم | سریال | نقش | شخصیت | قسمت | ساخت | عنوان | ماه | فیلمبرداری | مجموعه,,,,,
3,LDA,30,42,9,استفاده | حلقه | صورت | روش | مثال | عنوان | عنصر | نشان | معمولا | مقدار,,,,,
4,LDA,30,42,12,سال | دانشگاه | ایران | تهران | عنوان | سازمان | رشته | کشور | فعالیت | عضو,,,,,
5,LDA,30,42,16,مواد | آن | تولید | آب | استفاده | عنوان | ماده | واکنش | توسط | بتن,,,,,
6,LDA,30,42,19,اجتماعی | جامعه | انسان | زندگی | نظریه | اقتصادی | انسانی | زنان | همگانی | خودکشی,,,,,
7,LDA,30,42,22,دارو | مصرف | درمان | بیماری | بیمار | واکسن | خون | آب | پوست | پزشکی,,,,,
8,LDA,30,42,25,بن | علی | محمد | امین | طاهر | حسین | خراسان | عبدالله | امیر | تهران,,,,,
9,LDA,30,42,29,سال | نام | زندگی | خانواده | داستان | ازدواج | عنوان | زن | خانه | همسر,,,,,
10,NMF,30,42,0,مسکونی | منطقه | واقع | جمعیت | نفر | شده‌است | مساحت | بالاتر | واقع‌شده | دریا,,,,,
11,NMF,30,42,3,تلویزیون | نقش | فیلم | داشته‌است | اشاره | برنامه | اهل | نمود | مجموعه | آن,,,,,
12,NMF,30,42,6,کشوری | مسابقات | مجموع | بین‌المللی | برنده | اهل | شده‌است | ورزشکار | دسامبر | مارس,,,,,
13,NMF,30,42,9,فرودگاه | متری | باند | ارتفاع | همگانی | کشور | قرار | دریا | سطح | واقع‌شده,,,,,
14,NMF,30,42,12,بازیگر | منتشر | فیلم | کارگردانی | اشاره | سال | ژانر | آمریکایی | سینما | سبک,,,,,
15,NMF,30,42,16,فیلم | بازیگرانی | محصول | کارگردانی | ایفا | نقش | کرد | سال | بازی | سینمایی,,,,,
16,NMF,30,42,19,جوایز | برنده | شده‌است | اهل | نظامی | دانشمند | دسامبر | ژوئیه | مارس | زمینه,,,,,
17,NMF,30,42,22,کشتی | فوت | اینچ | سال | زیردریایی | میلیمتر | ارتفاع | حالت | طبیعی | خودرویی,,,,,
18,NMF,30,42,25,ژوئن | اهل | اشاره | فیلم | نقش | درگذشته | بازیکن | رکاب | زده‌است | ورزشکار,,,,,
19,NMF,30,42,29,جغرافیایی | موقعیت | شرح | اطراف | مناطق | شهر | جمعیت | نفر | واقع | شده‌است,,,,,
20,CTM,30,42,0,ثبت | به‌عنوان | واقع‌شده | شماره | اسفند | مرکزی | شرق | غرب | دهستان | کیلومتری,,,,,
21,CTM,30,42,3,سیارک | کشف | فرودگاه | همگانی | باند | صد | ظاهری | دنده | ام | اینچ,,,,,
22,CTM,30,42,6,استفاده | ایجاد | مختلف | صورت | معمولا | به‌طور | زمانی | تاثیر | عمل | نشان,,,,,
23,CTM,30,42,9,داشته‌است | بازیگرانی | ایفا | تلویزیون | کارگردانی | محصول | مشغول | جوایز | دانش‌آموخته | نقشی,,,,,
24,CTM,30,42,12,سال | کار | شده‌است | آن | استفاده | عنوان | کتاب | اشاره | نام | توسط,,,,,
25,CTM,30,42,16,واقع‌شده | ثبت | به‌عنوان | شماره | مرداد | منظر | اسفند | رسیده‌است | کوچه | خرداد,,,,,
26,CTM,30,42,19,موقع | اهل | قایق | اولویت | تجدید | بلافاصله | اشخاص | ظاهرا | خودشان | رفاه,,,,,
27,CTM,30,42,22,جمعیت | سرشماری | روستایی | توابع | خانوار | پیگیری | نفر | سفری | آستانه | کلاه,,,,,
28,CTM,30,42,25,فیلم | نقش | کارگردانی | منتشر | شخصیت | سال | نام | عنوان | دریافت | آلبوم,,,,,
29,CTM,30,42,29,سال | عنوان | بازی | قرار | تیم | نام | نفر | توسط | روز | زمان,,,,,
30,BERTopic,30,42,0,بالاتر | واقع | دریا | سطح | مساحت | مسکونی | شده‌است | جمعیت | منطقه | نفر,,,,,
31,BERTopic,30,42,3,طاهر | پادشاه | بن | حکومت | امین | پسر | جنگ | شاه | قرن | سرزمین,,,,,
32,BERTopic,30,42,6,تجاوز | استفاده | حافظه | نرم‌افزار | داده | سیستم | مالیات | کد | جنسی | مثال,,,,,
33,BERTopic,30,42,9,سلول | ویروس | مواد | دارو | پروتئین | انرژی | استفاده | ماده | بتن | واکنش,,,,,
34,BERTopic,30,42,12,مسابقات | کشوری | مجموع | برنده | بین‌المللی | ورزشکار | مدال | اهل | کمربند | باتیستا,,,,,
35,BERTopic,30,42,16,فیلم | بازیگر | سینما | جوایز | بازیگری | اهل | نقش | جایزه | سریال | سالگی,,,,,
36,BERTopic,30,42,19,باغ | موزه | ساختمان | شهر | بنا | برج | سنگ | تل | بازار | صحن,,,,,
37,BERTopic,30,42,22,گیاه | اژد | نان | گونه | تخم | ماهی | نر | گیاهان | جانور | انسان,,,,,
38,BERTopic,30,42,25,فرودگاه | باند | متری | همگانی | ارتفاع | دریا | واقع‌شده | سطح | کشور | بهره‌برداری,,,,,
39,BERTopic,30,42,29,زیردریایی | فوت | اینچ | غرق | کلاس | سال | ارتفاع,,,,,
40,BERTopic-ParsBERT,30,42,0,استفاده | معمولا | سیستم | صورت | سلول | فرایند | مواد | ساختار | ماده | تولید,,,,,
41,BERTopic-ParsBERT,30,42,3,بالاتر | واقع | دریا | سطح | مساحت | مسکونی | شده‌است | جمعیت | منطقه | نفر,,,,,
42,BERTopic-ParsBERT,30,42,6,تلویزیون | اهل | داشته‌است | نقش | اشاره | فیلم | مشغول | برنامه | جوایز | فعالیت,,,,,
43,BERTopic-ParsBERT,30,42,9,خانوار | توابع | روستایی | روستا | بوده‌است | جمعیت | نفر | سرشماری | قرار | دهستانی,,,,,
44,BERTopic-ParsBERT,30,42,12,ثبت | واقع‌شده | به‌عنوان | شماره | اسفند | تاریخ | دهستان | روستا | مرکزی | سده,,,,,
45,BERTopic-ParsBERT,30,42,16,کشف | سیارک | هزار | هشتصد | ششصد | بیست | هفتصد | هشتمین | پنجاه | هفتمین,,,,,
46,BERTopic-ParsBERT,30,42,19,اندیس | تصویب | ممتنع | قطعنامه | سندی | دیرینگی | موافق | حوالی | ام | میزبان,,,,,
47,BERTopic-ParsBERT,30,42,22,پایه | خانوار | روستایی | روستا | جمعیت | نفر | بوده‌است | مکان | پیام | نور,,,,,
48,BERTopic-ParsBERT,30,42,25,دویست | روز | کبیسه | پایان | عادی | نودمین | مانده‌است | باقی | نود | گذشته,,,,,
49,BERTopic-ParsBERT,30,42,29,نصف‌النهار | گرینویچ | ختم | مین | زمانی | اختلاف | دقیقه | گذشته | ساعت | مناطق,,,,,

## 3. Statistical testing

Friedman tests

,analysis,metric,block_unit,blocks,models,friedman_chi_square,raw_p,kendalls_w,alpha,significant_0_05,inference_scope
0,core_topic_models,c_v,K × seed,27,"LDA, NMF, CTM, BERTopic",66.511111,2.382711e-14,0.821125,0.05,True,Exploratory repeated-configuration comparison; K and seed blocks are not population samples.
1,core_topic_models,c_npmi,K × seed,27,"LDA, NMF, CTM, BERTopic",39.844444,1.149553e-08,0.491907,0.05,True,Exploratory repeated-configuration comparison; K and seed blocks are not population samples.
2,core_topic_models,diversity,K × seed,27,"LDA, NMF, CTM, BERTopic",77.800000,9.096050e-17,0.960494,0.05,True,Exploratory repeated-configuration comparison; K and seed blocks are not population samples.
3,core_topic_models,distinctness,K × seed,27,"LDA, NMF, CTM, BERTopic",69.400000,5.737585e-15,0.856790,0.05,True,Exploratory repeated-configuration comparison; K and seed blocks are not population samples.
4,core_topic_models,stability,K,9,"LDA, NMF, CTM, BERTopic",23.533333,3.125962e-05,0.871605,0.05,True,Exploratory stability comparison across 9 predeclared statistical K values.

Wilcoxon pairwise tests with Holm correction, rank-biserial effects, and 5,000-resample CIs

,analysis,metric,model_a,model_b,paired_blocks,mean_difference_a_minus_b,cluster_bootstrap_95_ci_low,cluster_bootstrap_95_ci_high,bootstrap_clusters,bootstrap_resamples,wilcoxon_statistic,raw_p,rank_biserial,alpha,inference_scope,holm_p,significant_holm_0_05
0,core_topic_models,c_v,LDA,NMF,27,-0.035848,-0.050984,-0.017332,K,5000,18.0,3.769994e-06,-0.904762,0.05,Exploratory; paired K × seed results with K-cluster bootstrap.,1.130998e-05,True
1,core_topic_models,c_v,LDA,CTM,27,0.052229,0.042606,0.061037,K,5000,0.0,1.490116e-08,1.000000,0.05,Exploratory; paired K × seed results with K-cluster bootstrap.,8.940697e-08,True
2,core_topic_models,c_v,LDA,BERTopic,27,0.024810,0.007937,0.039203,K,5000,46.0,2.668798e-04,0.756614,0.05,Exploratory; paired K × seed results with K-cluster bootstrap.,2.668798e-04,True
3,core_topic_models,c_v,NMF,CTM,27,0.088076,0.063972,0.110219,K,5000,0.0,1.490116e-08,1.000000,0.05,Exploratory; paired K × seed results with K-cluster bootstrap.,8.940697e-08,True
4,core_topic_models,c_v,NMF,BERTopic,27,0.060657,0.026221,0.089100,K,5000,21.0,6.660819e-06,0.888889,0.05,Exploratory; paired K × seed results with K-cluster bootstrap.,1.332164e-05,True
5,core_topic_models,c_v,CTM,BERTopic,27,-0.027419,-0.039962,-0.018779,K,5000,0.0,1.490116e-08,-1.000000,0.05,Exploratory; paired K × seed results with K-cluster bootstrap.,8.940697e-08,True
6,core_topic_models,c_npmi,LDA,NMF,27,-0.075284,-0.113818,-0.039332,K,5000,1.0,2.980232e-08,-0.994709,0.05,Exploratory; paired K × seed results with K-cluster bootstrap.,1.490116e-07,True
7,core_topic_models,c_npmi,LDA,CTM,27,-0.054864,-0.095305,0.002605,K,5000,64.0,1.858577e-03,-0.661376,0.05,Exploratory; paired K × seed results with K-cluster bootstrap.,7.434309e-03,True
8,core_topic_models,c_npmi,LDA,BERTopic,27,-0.080764,-0.097095,-0.061436,K,5000,0.0,1.490116e-08,-1.000000,0.05,Exploratory; paired K × seed results with K-cluster bootstrap.,8.940697e-08,True
9,core_topic_models,c_npmi,NMF,CTM,27,0.020420,-0.050399,0.104354,K,5000,176.0,7.676084e-01,0.068783,0.05,Exploratory; paired K × seed results with K-cluster bootstrap.,1.000000e+00,False
10,core_topic_models,c_npmi,NMF,BERTopic,27,-0.005480,-0.037596,0.033129,K,5000,187.0,9.717257e-01,0.010582,0.05,Exploratory; paired K × seed results with K-cluster bootstrap.,1.000000e+00,False
11,core_topic_models,c_npmi,CTM,BERTopic,27,-0.025901,-0.069644,0.012421,K,5000,143.0,2.792418e-01,-0.243386,0.05,Exploratory; paired K × seed results with K-cluster bootstrap.,8.377253e-01,False
12,core_topic_models,diversity,LDA,NMF,27,0.566599,0.436068,0.678059,K,5000,0.0,5.597410e-06,1.000000,0.05,Exploratory; paired K × seed results with K-cluster bootstrap.,1.119482e-05,True
13,core_topic_models,diversity,LDA,CTM,27,0.320661,0.232965,0.388298,K,5000,0.0,1.490116e-08,1.000000,0.05,Exploratory; paired K × seed results with K-cluster bootstrap.,8.940697e-08,True
14,core_topic_models,diversity,LDA,BERTopic,27,0.097219,0.041998,0.139194,K,5000,31.0,3.522635e-05,0.835979,0.05,Exploratory; paired K × seed results with K-cluster bootstrap.,3.522635e-05,True
15,core_topic_models,diversity,NMF,CTM,27,-0.245938,-0.301612,-0.185945,K,5000,0.0,1.490116e-08,-1.000000,0.05,Exploratory; paired K × seed results with K-cluster bootstrap.,8.940697e-08,True
16,core_topic_models,diversity,NMF,BERTopic,27,-0.469381,-0.545296,-0.387298,K,5000,0.0,1.490116e-08,-1.000000,0.05,Exploratory; paired K × seed results with K-cluster bootstrap.,8.940697e-08,True
17,core_topic_models,diversity,CTM,BERTopic,27,-0.223443,-0.250202,-0.192249,K,5000,0.0,1.490116e-08,-1.000000,0.05,Exploratory; paired K × seed results with K-cluster bootstrap.,8.940697e-08,True
18,core_topic_models,distinctness,LDA,NMF,27,0.350499,0.193072,0.505296,K,5000,0.0,1.490116e-08,1.000000,0.05,Exploratory; paired K × seed results with K-cluster bootstrap.,8.940697e-08,True
19,core_topic_models,distinctness,LDA,CTM,27,0.008237,0.003843,0.011861,K,5000,23.0,9.536743e-06,0.878307,0.05,Exploratory; paired K × seed results with K-cluster bootstrap.,1.907349e-05,True
20,core_topic_models,distinctness,LDA,BERTopic,27,0.000428,-0.004594,0.004077,K,5000,110.0,5.847424e-02,0.417989,0.05,Exploratory; paired K × seed results with K-cluster bootstrap.,5.847424e-02,False
21,core_topic_models,distinctness,NMF,CTM,27,-0.342261,-0.498617,-0.185756,K,5000,0.0,1.490116e-08,-1.000000,0.05,Exploratory; paired K × seed results with K-cluster bootstrap.,8.940697e-08,True
22,core_topic_models,distinctness,NMF,BERTopic,27,-0.350070,-0.505569,-0.187495,K,5000,0.0,1.490116e-08,-1.000000,0.05,Exploratory; paired K × seed results with K-cluster bootstrap.,8.940697e-08,True
23,core_topic_models,distinctness,CTM,BERTopic,27,-0.007809,-0.008765,-0.006842,K,5000,0.0,1.490116e-08,-1.000000,0.05,Exploratory; paired K × seed results with K-cluster bootstrap.,8.940697e-08,True
24,core_topic_models,stability,LDA,NMF,9,-0.730218,-0.798036,-0.634785,K values,5000,0.0,3.906250e-03,-1.000000,0.05,Exploratory; only nine K-level stability observations.,2.343750e-02,True
25,core_topic_models,stability,LDA,CTM,9,0.002536,-0.031354,0.049534,K values,5000,19.0,7.343750e-01,-0.155556,0.05,Exploratory; only nine K-level stability observations.,7.343750e-01,False
26,core_topic_models,stability,LDA,BERTopic,9,-0.449334,-0.489716,-0.409396,K values,5000,0.0,3.906250e-03,-1.000000,0.05,Exploratory; only nine K-level stability observations.,2.343750e-02,True
27,core_topic_models,stability,NMF,CTM,9,0.732754,0.673420,0.781919,K values,5000,0.0,3.906250e-03,1.000000,0.05,Exploratory; only nine K-level stability observations.,2.343750e-02,True
28,core_topic_models,stability,NMF,BERTopic,9,0.280884,0.176322,0.369436,K values,5000,1.0,7.812500e-03,0.955556,0.05,Exploratory; only nine K-level stability observations.,2.343750e-02,True
29,core_topic_models,stability,CTM,BERTopic,9,-0.451870,-0.501243,-0.409647,K values,5000,0.0,3.906250e-03,-1.000000,0.05,Exploratory; only nine K-level stability observations.,2.343750e-02,True

BERTopic encoder sensitivity tests

,analysis,metric,model_a,model_b,paired_blocks,mean_difference_a_minus_b,cluster_bootstrap_95_ci_low,cluster_bootstrap_95_ci_high,wilcoxon_statistic,raw_p,rank_biserial,alpha,inference_scope,holm_p,significant_holm_0_05
0,bertopic_encoder_sensitivity,c_v,BERTopic-ParsBERT,BERTopic,27,0.008727,0.004957,0.013296,19.0,4.574656e-06,0.899471,0.05,Encoder sensitivity conditional on fixed BERTopic/UMAP/KMeans/c-TF-IDF settings.,4.574656e-06,True
1,bertopic_encoder_sensitivity,c_npmi,BERTopic-ParsBERT,BERTopic,27,0.054502,0.049056,0.060580,0.0,1.490116e-08,1.000000,0.05,Encoder sensitivity conditional on fixed BERTopic/UMAP/KMeans/c-TF-IDF settings.,5.960464e-08,True
2,bertopic_encoder_sensitivity,diversity,BERTopic-ParsBERT,BERTopic,27,-0.049966,-0.062872,-0.037319,0.0,1.490116e-08,-1.000000,0.05,Encoder sensitivity conditional on fixed BERTopic/UMAP/KMeans/c-TF-IDF settings.,5.960464e-08,True
3,bertopic_encoder_sensitivity,distinctness,BERTopic-ParsBERT,BERTopic,27,-0.002686,-0.003345,-0.002014,0.0,1.490116e-08,-1.000000,0.05,Encoder sensitivity conditional on fixed BERTopic/UMAP/KMeans/c-TF-IDF settings.,5.960464e-08,True

## 4. Preprocessing ablation

Ablation full train:   0%|          | 0/2000 [00:00<?, ?it/s]

Ablation full test:   0%|          | 0/1000 [00:00<?, ?it/s]

Ablation no_lemmatization train:   0%|          | 0/2000 [00:00<?, ?it/s]

Ablation no_lemmatization test:   0%|          | 0/1000 [00:00<?, ?it/s]

Ablation no_stopword_removal train:   0%|          | 0/2000 [00:00<?, ?it/s]

Ablation no_stopword_removal test:   0%|          | 0/1000 [00:00<?, ?it/s]

Ablation normalization_tokenization_only train:   0%|          | 0/2000 [00:00<?, ?it/s]

Ablation normalization_tokenization_only test:   0%|          | 0/1000 [00:00<?, ?it/s]

Preprocessing-ablation run-level results

,variant,seed,k,train_documents_requested,validation_documents_requested,train_documents_retained,validation_documents_retained,c_v,c_npmi,diversity,distinctness,valid_topic_count,training_seconds
0,full,42,30,2000,1000,2000,1000,0.391870,-0.045480,0.636667,0.945932,30,18.545028
1,full,123,30,2000,1000,2000,1000,0.391586,-0.096237,0.646667,0.946168,30,19.559992
2,full,456,30,2000,1000,2000,1000,0.398911,-0.101425,0.686667,0.958640,30,18.893193
3,no_lemmatization,42,30,2000,1000,2000,1000,0.357098,-0.144107,0.606667,0.917118,30,18.014860
4,no_lemmatization,123,30,2000,1000,2000,1000,0.358757,-0.116349,0.626667,0.943913,30,17.967509
5,no_lemmatization,456,30,2000,1000,2000,1000,0.377761,-0.118616,0.620000,0.929460,30,18.404350
6,no_stopword_removal,42,30,2000,1000,2000,1000,0.381379,-0.007189,0.360000,0.764764,30,36.424419
7,no_stopword_removal,123,30,2000,1000,2000,1000,0.383134,0.008430,0.366667,0.785002,30,35.370110
8,no_stopword_removal,456,30,2000,1000,2000,1000,0.360377,-0.021167,0.343333,0.711117,30,33.841359
9,normalization_tokenization_only,42,30,2000,1000,2000,1000,0.358838,-0.039803,0.420000,0.800198,30,34.970225
10,normalization_tokenization_only,123,30,2000,1000,2000,1000,0.352661,-0.052183,0.433333,0.810368,30,36.534411
11,normalization_tokenization_only,456,30,2000,1000,2000,1000,0.374242,-0.035707,0.486667,0.843543,30,32.268617

Preprocessing-ablation aggregate results

,variant,runs,k,train_documents_retained,validation_documents_retained,valid_topic_count_mean,c_v_mean,c_v_sd,c_v_bootstrap_ci_low,c_v_bootstrap_ci_high,c_npmi_mean,c_npmi_sd,c_npmi_bootstrap_ci_low,c_npmi_bootstrap_ci_high,diversity_mean,diversity_sd,diversity_bootstrap_ci_low,diversity_bootstrap_ci_high,distinctness_mean,distinctness_sd,distinctness_bootstrap_ci_low,distinctness_bootstrap_ci_high
0,full,3,30,2000,1000,30.0,0.394123,0.004150,0.391586,0.398911,-0.081047,0.030911,-0.101425,-0.045480,0.656667,0.026458,0.636667,0.686667,0.950247,0.007270,0.945932,0.958640
1,no_lemmatization,3,30,2000,1000,30.0,0.364539,0.011481,0.357098,0.377761,-0.126357,0.015413,-0.144107,-0.116349,0.617778,0.010184,0.606667,0.626667,0.930164,0.013411,0.917118,0.943913
2,no_stopword_removal,3,30,2000,1000,30.0,0.374963,0.012663,0.360377,0.383134,-0.006642,0.014806,-0.021167,0.008430,0.356667,0.012019,0.343333,0.366667,0.753628,0.038181,0.711117,0.785002
3,normalization_tokenization_only,3,30,2000,1000,30.0,0.361914,0.011114,0.352661,0.374242,-0.042564,0.008578,-0.052183,-0.035707,0.446667,0.035277,0.420000,0.486667,0.818037,0.022667,0.800198,0.843543

Preprocessing-ablation Friedman tests

,metric,block_unit,blocks,variants,friedman_chi_square,raw_p,kendalls_w,alpha,significant_0_05,inference_scope
0,c_v,seed,3,"full, no_lemmatization, no_stopword_removal, normalization_tokenization_only",5.8,0.121757,0.644444,0.05,False,Exploratory ablation inference with only three seeds; low statistical power.
1,c_npmi,seed,3,"full, no_lemmatization, no_stopword_removal, normalization_tokenization_only",9.0,0.029291,1.000000,0.05,True,Exploratory ablation inference with only three seeds; low statistical power.
2,diversity,seed,3,"full, no_lemmatization, no_stopword_removal, normalization_tokenization_only",9.0,0.029291,1.000000,0.05,True,Exploratory ablation inference with only three seeds; low statistical power.
3,distinctness,seed,3,"full, no_lemmatization, no_stopword_removal, normalization_tokenization_only",9.0,0.029291,1.000000,0.05,True,Exploratory ablation inference with only three seeds; low statistical power.

Preprocessing-ablation pairwise tests with Holm correction

,metric,variant_a,variant_b,paired_seeds,mean_difference_a_minus_b,bootstrap_95_ci_low,bootstrap_95_ci_high,bootstrap_resamples,wilcoxon_statistic,raw_p,rank_biserial,alpha,inference_scope,holm_p,significant_holm_0_05
0,c_v,full,no_lemmatization,3,0.029584,0.021150,0.034772,5000,0.0,0.25,1.000000,0.05,Exploratory; three paired seeds only.,1.0,False
1,c_v,full,no_stopword_removal,3,0.019159,0.008452,0.038534,5000,0.0,0.25,1.000000,0.05,Exploratory; three paired seeds only.,1.0,False
2,c_v,full,normalization_tokenization_only,3,0.032209,0.024670,0.038925,5000,0.0,0.25,1.000000,0.05,Exploratory; three paired seeds only.,1.0,False
3,c_v,no_lemmatization,no_stopword_removal,3,-0.010424,-0.024377,0.017384,5000,1.0,0.50,-0.666667,0.05,Exploratory; three paired seeds only.,1.0,False
4,c_v,no_lemmatization,normalization_tokenization_only,3,0.002625,-0.001740,0.006097,5000,1.0,0.50,0.666667,0.05,Exploratory; three paired seeds only.,1.0,False
5,c_v,no_stopword_removal,normalization_tokenization_only,3,0.013050,-0.013865,0.030473,5000,1.0,0.50,0.666667,0.05,Exploratory; three paired seeds only.,1.0,False
6,c_npmi,full,no_lemmatization,3,0.045310,0.017191,0.098627,5000,0.0,0.25,1.000000,0.05,Exploratory; three paired seeds only.,1.0,False
7,c_npmi,full,no_stopword_removal,3,-0.074405,-0.104667,-0.038291,5000,0.0,0.25,-1.000000,0.05,Exploratory; three paired seeds only.,1.0,False
8,c_npmi,full,normalization_tokenization_only,3,-0.038483,-0.065718,-0.005677,5000,0.0,0.25,-1.000000,0.05,Exploratory; three paired seeds only.,1.0,False
9,c_npmi,no_lemmatization,no_stopword_removal,3,-0.119715,-0.136918,-0.097449,5000,0.0,0.25,-1.000000,0.05,Exploratory; three paired seeds only.,1.0,False
10,c_npmi,no_lemmatization,normalization_tokenization_only,3,-0.083793,-0.104304,-0.064166,5000,0.0,0.25,-1.000000,0.05,Exploratory; three paired seeds only.,1.0,False
11,c_npmi,no_stopword_removal,normalization_tokenization_only,3,0.035922,0.014539,0.060613,5000,0.0,0.25,1.000000,0.05,Exploratory; three paired seeds only.,1.0,False
12,diversity,full,no_lemmatization,3,0.038889,0.020000,0.066667,5000,0.0,0.25,1.000000,0.05,Exploratory; three paired seeds only.,1.0,False
13,diversity,full,no_stopword_removal,3,0.300000,0.276667,0.343333,5000,0.0,0.25,1.000000,0.05,Exploratory; three paired seeds only.,1.0,False
14,diversity,full,normalization_tokenization_only,3,0.210000,0.200000,0.216667,5000,0.0,0.25,1.000000,0.05,Exploratory; three paired seeds only.,1.0,False
15,diversity,no_lemmatization,no_stopword_removal,3,0.261111,0.246667,0.276667,5000,0.0,0.25,1.000000,0.05,Exploratory; three paired seeds only.,1.0,False
16,diversity,no_lemmatization,normalization_tokenization_only,3,0.171111,0.133333,0.193333,5000,0.0,0.25,1.000000,0.05,Exploratory; three paired seeds only.,1.0,False
17,diversity,no_stopword_removal,normalization_tokenization_only,3,-0.090000,-0.143333,-0.060000,5000,0.0,0.25,-1.000000,0.05,Exploratory; three paired seeds only.,1.0,False
18,distinctness,full,no_lemmatization,3,0.020083,0.002256,0.029180,5000,0.0,0.25,1.000000,0.05,Exploratory; three paired seeds only.,1.0,False
19,distinctness,full,no_stopword_removal,3,0.196619,0.161166,0.247523,5000,0.0,0.25,1.000000,0.05,Exploratory; three paired seeds only.,1.0,False
20,distinctness,full,normalization_tokenization_only,3,0.132210,0.115098,0.145734,5000,0.0,0.25,1.000000,0.05,Exploratory; three paired seeds only.,1.0,False
21,distinctness,no_lemmatization,no_stopword_removal,3,0.176536,0.152354,0.218343,5000,0.0,0.25,1.000000,0.05,Exploratory; three paired seeds only.,1.0,False
22,distinctness,no_lemmatization,normalization_tokenization_only,3,0.112127,0.085918,0.133544,5000,0.0,0.25,1.000000,0.05,Exploratory; three paired seeds only.,1.0,False
23,distinctness,no_stopword_removal,normalization_tokenization_only,3,-0.064409,-0.132426,-0.025366,5000,0.0,0.25,-1.000000,0.05,Exploratory; three paired seeds only.,1.0,False

## 5. Persian named-entity recognition

Stanza NER train:   0%|          | 0/10000 [00:00<?, ?it/s]

Stanza NER link_test:   0%|          | 0/10000 [00:00<?, ?it/s]

NER diagnostics

,split,documents_processed,documents_with_entities,documents_with_errors,error_rate,max_characters_per_document,total_mentions,unique_surface_forms,unique_typed_surface_nodes,excluded_unknown_type_mentions,excluded_unknown_type_counts,dummy_or_fallback_entities_used
0,train,10000,6055,0,0.0,5000,47493,23941,24811,0,{},False
1,link_test,10000,6211,0,0.0,5000,45947,22968,23811,0,{},False

Entity-type distribution

    entity_type  train_mentions  test_mentions  train_percent  test_percent
0        Person           15756          14598      33.175415     31.771389
1      Location           15936          16061      33.554419     34.955492
2  Organization           10062           9903      21.186280     21.553094
3       Product            3061           3006       6.445160      6.542320
4      Facility            1970           1620       4.147980      3.525801
5         Event             708            759       1.490746      1.651903

Top entity surface forms overall

           surface   entity_type  mentions
0            ایران      Location      1233
1         آمریکایی  Organization       390
2            تهران      Location       342
3           آمریکا      Location       335
4           ایرانی  Organization       323
5          انگلیسی  Organization       222
6            آلمان      Location       200
7           فرانسه      Location       177
8     ایالات متحده      Location       169
9           آلمانی  Organization       163
10       ویکی پدیا  Organization       161
11           اروپا      Location       152
12            ژاپن      Location       146
13         فرانسوی  Organization       134
14           روسیه      Location       120
15          اصفهان      Location       119
16        بریتانیا      Location       118
17           ایران  Organization       117
18  تیم ملی فوتبال  Organization       116
19             هند      Location       107
20        استرالیا      Location       104
21       افغانستان      Location       103
22        انگلستان      Location        96
23       بخش مرکزی      Location        95
24             چین      Location        94
25         ایتالیا      Location        93
26             مصر      Location        90
27       آذربایجان      Location        87
28            عراق      Location        87
29            چینی  Organization        76

Top training entity surface forms by type

                  surface entity_type  mentions
0     جام باشگاه های آسیا       Event         5
1               جام جهانی       Event         5
2                جام حذفی       Event         5
3    مسابقات قهرمانی جهان       Event         5
4    سومین دوره جایزه شعر       Event         4
..                    ...         ...       ...
115  تنسور گشتاور مرکزوار     Product         7
116                   طلا     Product         7
117                 مانگا     Product         7
118                   هلو     Product         7
119                  کتان     Product         7

[120 rows x 3 columns]

Top test entity surface forms overall

           surface   entity_type  mentions
0            ایران      Location      1254
1         آمریکایی  Organization       373
2            تهران      Location       345
3           ایرانی  Organization       327
4           فرانسه      Location       279
5           آمریکا      Location       272
6     ایالات متحده      Location       242
7          انگلیسی  Organization       211
8            اروپا      Location       184
9             ژاپن      Location       177
10           آلمان      Location       158
11           روسیه      Location       149
12          آلمانی  Organization       148
13  تیم ملی فوتبال  Organization       145
14       ویکی پدیا  Organization       145
15         فرانسوی  Organization       143
16           ایران  Organization       137
17        بریتانیا      Location       120
18       افغانستان      Location       117
19        انگلستان      Location       115
20           ترکیه      Location       106
21          کانادا      Location       100
22             هند      Location        95
23        استرالیا      Location        94
24       بخش مرکزی      Location        94
25             چین      Location        92
26         ایتالیا      Location        84
27       ایتالیایی  Organization        79
28            محمد        Person        78
29          اصفهان      Location        77

Top test entity surface forms by type

                   surface entity_type  mentions
0                جام جهانی       Event        20
1    انتخابات ریاست جمهوری       Event        12
2                 جام حذفی       Event         6
3         جام ملت های آسیا       Event         6
4       جام ملت های آفریقا       Event         6
..                     ...         ...       ...
115                سیلیسیم     Product         7
116                   قرآن     Product         7
117             مایکروسافت     Product         7
118                 ویندوز     Product         7
119                  کولار     Product         7

[120 rows x 3 columns]

Complete NER document diagnostics contain 20,000 rows and are saved in the final JSON evidence.

     split  doc_position  doc_id  mention_count  unique_typed_entity_count  has_entity  processing_error
0    train             0     281              1                          1        True             False
1    train             1     470              0                          0       False             False
2    train             2    1252              0                          0       False             False
3    train             3    1341             12                         10        True             False
4    train             4    2444              0                          0       False             False
..     ...           ...     ...            ...                        ...         ...               ...
195  train           195   42059              0                          0       False             False
196  train           196   42089              1                          1        True             False
197  train           197   42249             15                          8        True             False
198  train           198   42354              1                          1        True             False
199  train           199   42356              0                          0       False             False

[200 rows x 7 columns]

Unscored NER human-audit template (complete template saved in JSON)

,split,doc_position,doc_id,surface,entity_type,raw_ner_type,document_excerpt,boundary_correct,type_correct,canonical_entity_or_alias,annotator,notes
0,link_test,1206,276814,جام یوفا,Event,event,باشگاه فوتبال اینتر میلان یکی از پرافتخارترین تیم‌های ایتالیا و نهمین تیم پرافتخار در پنج لیگ معتبر اروپایی با کسب ۴...,,,,,
1,link_test,1411,330390,چهارمین دوره مجلس شورای اسلامی,Event,event,(زاده در ) نماینده از است. وی نماینده چهارمین دوره مجلس شورای اسلامی از حوزه انتخابیه بود.\n امان نریمانی در ، با مش...,,,,,
2,link_test,1489,355722,انتخابات پارلمان اروپا,Event,event,در تاریخ ۴ تا ۷ ژوئن سال در بین ۲۷ کشور عضو برگزار شد. در این انتخابات ۷۳۶ نماینده به نمایندگی از بیش از ۵۰۰ میلیون ...,,,,,
3,link_test,2004,529947,جام حذفی,Event,event,Football club (به : ) یک باشگاه فوتبال است که در شهر قرار دارد. این باشگاه در بازی می‌کند و تاکنون ۸ بار قهرمان بوند...,,,,,
4,link_test,2425,618800,جام جهانی هاکی,Event,event,(متولد ۱۵ خرداد ۱۳۶۵)، بازیکن و کاپیتان تیم ملی هاکی جمهوری اسلامی ایران است. \nاو از سن ۹ سالگی فعالیت ورزشی خود را...,,,,,
5,link_test,2425,618800,سه دوره جام جهانی هاکی سالنی,Event,event,(متولد ۱۵ خرداد ۱۳۶۵)، بازیکن و کاپیتان تیم ملی هاکی جمهوری اسلامی ایران است. \nاو از سن ۹ سالگی فعالیت ورزشی خود را...,,,,,
6,link_test,3254,812187,یکصدمین سالگرد تسلیم,Event,event,(John Lester Barstow) (زادهٔ ۲۱ فوریه ۱۸۳۲ – درگذشتهٔ ۲۸ ژوئن ۱۹۱۳)، ، ، و بود که به عنوان سی و نهمین فرماندار ، یکی...,,,,,
7,link_test,3502,866634,هفتادمین دوره مراسم اعطای جوایز اسکار,Event,event,هفتادمین دوره مراسم اعطای جوایز اسکار (انگلیسی: 70th Academy Awards) در ۲۳ مارس ۱۹۹۸ در ، لس آنجلس برگزار شد. در این...,,,,,
8,link_test,4578,1152310,لیگ برتر کشتی آزاد ایران,Event,event,(زادهٔ ۲۶ تیر ۱۳۸۱) کشتی‌گیر آزادکار ایرانی است. وی در ردهٔ نوجوانان دو بار قهرمان آسیا و دو بار قهرمان جهان شده‌ اس...,,,,,
9,link_test,4934,1251988,هجدهمین فستیوال سالانه «نیکلودین,Event,event,(به : ) دومین کانادایی است. این آلبوم به صورت جهانی در ۲۵ مه ۲۰۴ عرضه شد و آخرین آلبوم لوین همراه با بود. آلبوم توان...,,,,,
10,link_test,5183,1309881,جام اتحادیه,Event,event,( : ؛ زاده ۱۴ ژوئیهٔ ۱۹۹۵) یک اهل است که برای تیم در آلمان بازی می‌کند. \n او فوتبال حرفه ای خود را در سال ۲۰۱۲ با ت...,,,,,
11,link_test,6274,1615846,مسابقات تور دو فرانس,Event,event,( : ‎؛ زادهٔ ۲۲ ژوئیهٔ ۱۹۷۸) اهل است. وی در مسابقات تور دو فرانس و جیرو دیتالیا شرکت کرده است.,,,,,
12,link_test,6564,1685757,جام جهانی ۲۰۱۴,Event,event,فوتبالیست حرفه ای بازنشسته هلندی است که در پست بازی می‌کرد. او در ژوئن ۲۰۰۵ اولین بازی خود را برای کشورش انجام داد و...,,,,,
13,link_test,6616,1697716,لیگ ملی ای اف ال,Event,event,(به : ) یکی از انواع بازی فوتبال است که در زمره مهمترین کشور قرار می‌گیرد. این رشته در استرالیا معمولاً یا نامیده می...,,,,,
14,link_test,7685,1943659,بیستمین دوره لیگ برتر,Event,event,بیستمین دوره مسابقات و چهل و هشتمین دوره از است. در این دوره همانند دوره‌های گذشته شانزده تیم در مسابقات حضور دارند ...,,,,,
15,link_test,8813,2232165,جام جهانی,Event,event,بازیکن بازنشستهٔ زن آلمان است. \n نیا کانزر در شهر و در کشور با نام کامل وی نیا تی شالفلو کانزر (نام کوچک او به به م...,,,,,
16,link_test,9729,2457104,لیگ برتر والیبال لهستان,Event,event,(به : ) ، لیگ برتر والیبال لهستان، یک لیگ حرفه‌ای است. پلوس لیگا بالاترین سطح مسابقات باشگاهی والیبال در لهستان است....,,,,,
17,link_test,606,115607,حوزه علوم سیاسی,Facility,fac,(متولد ۱۳۵۶ در ) پژوهشگر ایرانی حوزه علوم سیاسی و ، استادیار دانشکده مطالعات جهان و مدیر گروه مطالعات ایران این دانش...,,,,,
18,link_test,829,173418,موزه عبرت فعلی,Facility,fac,(زاده ۱۳۲۶) سیاستمدار ایرانی است که نماینده دوره اول و دوم در از حوزهٔ انتخابیهٔ شهرستان نطنز و بخش قمصر کاشان بوده‌...,,,,,
19,link_test,1783,429249,صحن بقعه صفویان,Facility,fac,(به لهجهٔ : یا )، نام تعدادی گروه از است که در بخش‌هایی از شمال غرب ایران به ویژه و و نواحی و ، واقع در میان و تهران...,,,,,
20,link_test,2295,586263,سه راه فردوسی,Facility,fac,کلان شهر دارای تعداد زیادی می‌باشد که نام آن‌ها در این فهرست گردآوری شده‌اند و عبارتند از:\n بزرگراه میثاق ( هاشمی ر...,,,,,
21,link_test,3296,820773,میدان سنت جیمز لندن,Facility,fac,(به : ) با نام کامل (به : ) یک و در شهر است که به تحلیل چالش‌های استراتژیک می‌پردازد. از چتم هاوس به عنوان کشور یاد ...,,,,,
22,link_test,3858,941284,خیابان لطفعلی خان زند,Facility,fac,مربوط به است و در ، خیابان لطفعلی خان زند، کوچه ۷۳ واقع شده‌است. این اثر در تاریخ ۸ مرداد ۱۳۸۱ با شمارهٔ ثبت ۶۰۶۵ به...,,,,,
23,link_test,4069,1026044,دانشگاه لا تروب,Facility,fac,(به : ) یک در است که در ، در قرار دارد. این دانشگاه دارای چند محوطه است که محوطه اصلی آن در شهر باندورا در حومه ملبو...,,,,,
24,link_test,6046,1560163,دانشگاه تهران,Facility,fac,(زادهٔ در ) پژوهشگر و متخصص زبان‌های باستانی و ، ایلام‌شناس و از آخرین بازماندگان مترجم در جهان و از مهم‌ترین کتیبه‌...,,,,,
25,link_test,6053,1561830,مدرسه صفوی,Facility,fac,، (زاده ۱۲۹۱ در تهران - درگذشته ۱۷ بهمن ۱۳۸۱ آشتیان) پدر علم ایران و مؤسس است.\n عبدالکریم قریب گَرَکانی در سال ۱۲۹۱...,,,,,
26,link_test,6385,1640537,فرودگاه همگانی بهره برداری هوایی,Facility,fac,(به : ) یک فرودگاه همگانی بهره‌برداری هوایی با HEE است که یک دارد و طول باند آن ۱۵۲۴ متر است. این فرودگاه در کشور قر...,,,,,
27,link_test,7209,1863977,خیابان ماتیس,Facility,fac,(به : )؛ مدرسه تئاتر است که در سال ۱۹۶۷ توسط فرانسوا فلوران تأسیس شد. این مدرسه سه ساختمان در نوزدهم دارد (خیابان آر...,,,,,
28,link_test,7236,1867253,خیابان فلسطین,Facility,fac,(به : ) یکی از در مرکز است.\n این کنیسه در سال ۱۳۴۴ در خیابان فلسطین (کاخ سابق) بنیادگذاری شده‌است. زمین کلیسا توسط ...,,,,,
29,link_test,7259,1870477,ایستگاه قطار,Facility,fac,(به : ) در و نزدیک شهر قرار دارد. ارتفاع این کوه ۶۹۴ متر است. کوه سکیرُو یکی از کوه‌های محسوب می‌شود. در مسیر این را...,,,,,

## 6. Entity-association graph

LDA K=100 document-topic inference:   0%|          | 0/10000 [00:00<?, ?it/s]

LDA K=200 document-topic inference:   0%|          | 0/10000 [00:00<?, ?it/s]

LDA K=300 document-topic inference:   0%|          | 0/10000 [00:00<?, ?it/s]

Graph summary

,source_split,all_typed_nodes_before_cap,retained_graph_nodes,node_cap,train_edges,density,connected_components,giant_component_nodes,giant_component_fraction,isolates,mean_degree,degree_sd,median_degree,max_degree,mean_edge_weight,edge_weight_sd,median_edge_weight,max_edge_weight,approximate_average_clustering
0,training only,24811,5000,5000,57696,0.004617,569,4292,0.8584,496,23.0784,48.628621,15.0,1664,1.184346,1.245199,1.0,124,0.712

Entity inventory contains 5,000 typed surface-form nodes; complete table is saved in the final JSON evidence.

     entity_id      surface   entity_type  mention_frequency  document_frequency
0            0        ایران      Location               1233                 557
1            1     آمریکایی  Organization                390                 318
2            2       آمریکا      Location                335                 240
3            3       ایرانی  Organization                323                 223
4            4      انگلیسی  Organization                222                 193
..         ...          ...           ...                ...                 ...
195        195        توکیو      Location                 12                  10
196        196    توابع بخش      Location                 10                  10
197        197          کرج      Location                 10                  10
198        198  شمال آفریقا      Location                 11                  10
199        199     اشکانیان  Organization                 17                  10

[200 rows x 5 columns]

Graph node-type distribution

    entity_type  retained_nodes  percent
0        Person            1872    37.44
1      Location            1317    26.34
2  Organization            1032    20.64
3       Product             459     9.18
4      Facility             215     4.30
5         Event             105     2.10

Degree distribution

       variable  quantile    value
0   node_degree      0.00     0.00
1   node_degree      0.01     0.00
2   node_degree      0.05     0.00
3   node_degree      0.10     1.00
4   node_degree      0.25     6.00
5   node_degree      0.50    15.00
6   node_degree      0.75    29.00
7   node_degree      0.90    40.00
8   node_degree      0.95    62.05
9   node_degree      0.99   185.04
10  node_degree      1.00  1664.00

Edge-weight distribution

       variable  quantile  value
0   edge_weight      0.00    1.0
1   edge_weight      0.01    1.0
2   edge_weight      0.05    1.0
3   edge_weight      0.10    1.0
4   edge_weight      0.25    1.0
5   edge_weight      0.50    1.0
6   edge_weight      0.75    1.0
7   edge_weight      0.90    1.0
8   edge_weight      0.95    2.0
9   edge_weight      0.99    5.0
10  edge_weight      1.00  124.0

Connected-component size distribution

          variable  quantile   value
0   component_size      0.00     1.0
1   component_size      0.01     1.0
2   component_size      0.05     1.0
3   component_size      0.10     1.0
4   component_size      0.25     1.0
5   component_size      0.50     1.0
6   component_size      0.75     1.0
7   component_size      0.90     2.0
8   component_size      0.95     3.0
9   component_size      0.99     6.0
10  component_size      1.00  4292.0

Entity-topic vector sensitivity summary

   topic_k  entities  vector_dimensions  finite_values  nonzero_entity_vectors                                                                           construction
0      100      5000                100           True                    4671  mean training-document LDA topic distribution per typed entity, then L2 normalization
1      200      5000                200           True                    4671  mean training-document LDA topic distribution per typed entity, then L2 normalization
2      300      5000                300           True                    4671  mean training-document LDA topic distribution per typed entity, then L2 normalization

## 7. Leakage-controlled novel-link prediction

All repeated-fold link-prediction results

,repeat,fold,evaluation_id,method,roc_auc,average_precision,positive_edges,negative_edges,evaluation_nodes,training_edges,positive_train_overlap,negative_forbidden_overlap,positive_negative_overlap,positive_reuse_within_repeat,negative_reuse_within_repeat,self_pair_count
0,1,1,R1F1,Topic-K100,0.617402,0.599031,1884,1884,1000,19168,0,0,0,0,0,0
1,1,1,R1F1,Topic-K200,0.607708,0.590925,1884,1884,1000,19168,0,0,0,0,0,0
2,1,1,R1F1,Topic-K300,0.622114,0.608240,1884,1884,1000,19168,0,0,0,0,0,0
3,1,1,R1F1,Node2Vec,0.617923,0.601105,1884,1884,1000,19168,0,0,0,0,0,0
4,1,1,R1F1,DeepWalk,0.636607,0.621513,1884,1884,1000,19168,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
220,5,5,R5F5,DeepWalk,0.620614,0.601948,1582,1582,1000,19168,0,0,0,0,0,0
221,5,5,R5F5,Jaccard,0.608744,0.604978,1582,1582,1000,19168,0,0,0,0,0,0
222,5,5,R5F5,Adamic-Adar,0.615954,0.630461,1582,1582,1000,19168,0,0,0,0,0,0
223,5,5,R5F5,Preferential-Attachment,0.566470,0.597496,1582,1582,1000,19168,0,0,0,0,0,0
224,5,5,R5F5,Random,0.500150,0.505134,1582,1582,1000,19168,0,0,0,0,0,0

Link-prediction evaluation diagnostics and pair-set hashes

,repeat,fold,evaluation_id,fold_documents,positive_edges,negative_edges,positive_pair_sha256,negative_pair_sha256,positive_train_overlap,negative_forbidden_overlap,positive_negative_overlap,positive_reuse_within_repeat,negative_reuse_within_repeat,self_pair_count
0,1,1,R1F1,2000,1884,1884,ff04c48f997888ee608542809114fee16ca44584089efda86531516f5199776c,b90738dadc33bf5e113db1d2772bb0891f48f463e0c23d61fe9e3d06ef78efbf,0,0,0,0,0,0
1,1,2,R1F2,2000,1643,1643,4986cef7988e5ba26db4ef5cdeb3ed7015f17a48714f2e12cdad62453521445d,a5f903a35ba818b228a05741d5944095fbc49986f0f8f3a06a7a269f8a23205f,0,0,0,0,0,0
2,1,3,R1F3,2000,1753,1753,721d282273560cb91b557c5353e68ddc8ca95d022d7861aec9eff46451b7b865,eda46fb7ccad54bf6afae521e3a226e4cf3a2db2f9bbb11048fa6e5983382dec,0,0,0,0,0,0
3,1,4,R1F4,2000,1886,1886,272746642aa032722bb950f7270043588555f77882962c5c881b146f2cbca392,e8b196455660b8c52b8f016cda631739ba5f944c99bfbef208a40fc5376cbda4,0,0,0,0,0,0
4,1,5,R1F5,2000,1564,1564,dd6c9f7e9b4ccc28de8e6904afcd567b4c08a403b6fd5d468a51478cf9c9b6fb,2c108b62a5f1db5ef51a581f2a862aa04e61eadc44b37771cc836f39a2733f6b,0,0,0,0,0,0
5,2,1,R2F1,2000,1816,1816,7f6aa75d0219e6ec36a529b5fe710f06094969b8fdb9ceaafada396d3e695ae5,127229356ab9ed1d94363f2eb67d21f65772e7e445dec6b4de06f6e415fa00a4,0,0,0,0,0,0
6,2,2,R2F2,2000,2028,2028,ebe89cc11da621c53013dd1c082f24c4091de3ffa04fcdbbc20926fedc9eda62,222fb996aef4728c49a2c5a1c90110c713e39d24a583a1339e92589d8eaa2f5a,0,0,0,0,0,0
7,2,3,R2F3,2000,2009,2009,c665fc665c245f22b05905774279b3e272fccd47daf47ceaf0dec89fec4cd87e,0c03d78f5125dc1044b899d91c592f5aae1aa45ba193a7cd975932be4effab26,0,0,0,0,0,0
8,2,4,R2F4,2000,1490,1490,0b9e50b19361a46fbb9c7a58b078f8f54202f2c63ee20843fd6123ef39e0c2f2,37f44106606ab4630552c10578fa5b2ca03a5d0bc4ad08e92579fad759a2a09f,0,0,0,0,0,0
9,2,5,R2F5,2000,1387,1387,1f4937665f0399e3100b0b92d0803fc23f3cd60e33de66cca5d86f47fbc71174,4f598f175a893e00d92530c56dafc9dec8c7ba880f55ab8a4c4fbab24713a26d,0,0,0,0,0,0
10,3,1,R3F1,2000,1757,1757,bc032636051a0194ae74cd18f1cc880230f531966b6b2a904b0290187bb2788e,465c3b47834536f259bdb52e992d9fe37e64cfd860a9962f62d4b368970d1a25,0,0,0,0,0,0
11,3,2,R3F2,2000,1514,1514,fc46b4d598a64221fa2f4fdcfdd382e22f8db5d51b669cc1493b3ef2f5daabdb,365f8b079d4d8178214dbbef13951ff0cbe9517b847d0a93a6b9b3dd0e21bc42,0,0,0,0,0,0
12,3,3,R3F3,2000,1734,1734,b9f06fcfaeebdd146cf8d6886e46ee2e97878d12f38bf7b24e7a904f40ff10f2,590dd97e18f6c2105c3315fce173d7c5da4ba0f68226e6351860840d33a75088,0,0,0,0,0,0
13,3,4,R3F4,2000,1999,1999,65cf3a62a2153d7e3a17c6578038755e226bb14da39914308a3fef621fa2d946,b5abd3019093aa918b4df3970ed979cfad8b3b7da6a047418b4affe095b49079,0,0,0,0,0,0
14,3,5,R3F5,2000,1726,1726,fae93b6382df83f021c9612071d7e88fd0e59bf39c79acbe667c803a87b1bb93,b1b4a21eeaca01b40abdcc79ab54a01bcac9c5c44535312fa1d2feaca73063e2,0,0,0,0,0,0
15,4,1,R4F1,2000,1700,1700,b7e8b0080d931ebc2ae03e74586dfc6e7a98e0dbb9166c81ec16fe99ed4d35f0,c36367be444aef3f8a5d17b2e4a4968501db4c370e203e76649dee5e893bfe0d,0,0,0,0,0,0
16,4,2,R4F2,2000,1739,1739,281380ea42175561efc816055f5b2286883887fc4200e098008d88b7f4528b92,8853c8b3c392d71a853d7eca708ea5cae850ff5a5c2fa651597b8d82b2b3fc05,0,0,0,0,0,0
17,4,3,R4F3,2000,1702,1702,e642223107b5969655f3bf4d730324b2e36b014bd16066425d2d585fcfda730d,99408f4f18b5a410a1d4f8460b0be1e73f8c6aa063bf729e5bd2e547c0352326,0,0,0,0,0,0
18,4,4,R4F4,2000,1867,1867,06f6de43b8b36cf6f50a175162aeb6e4764b8497319ae69e093a6966caa5aaf3,23a95cd0ba6613e431851f37503ebaf6f7bd4560d08c19931c52d1cc04bad02d,0,0,0,0,0,0
19,4,5,R4F5,2000,1722,1722,d2bb47c931c71aa315f3bc62b4548aeda7804c761b45879660778b5b9a34438a,49504614983ddeffcbdc301780bfb8acfa267786c57c702e8a830cf580984d86,0,0,0,0,0,0
20,5,1,R5F1,2000,1766,1766,18fbd5eee61280f6d4fae2f0c50772fb1eb30c8aa20e3709d9017fc63df44c55,026be16f05280853a33655814dc61f1d54f2715ddb99f74b5a779bacdff40eb2,0,0,0,0,0,0
21,5,2,R5F2,2000,1834,1834,cd95be16f77a5003379b033cbf57fe36084129fb8b518820e71bac352f31daf2,37f99368842761d7960987dc58bcff29123bd1a9d28b099762b4536915e306e7,0,0,0,0,0,0
22,5,3,R5F3,2000,1664,1664,4ecaa8cb89dda8bcd3d2c3d759dd5df2ed7e026bae7cf78d25d295e151dddf98,bd03128eebc6fc28ea139054a5a5b40eb234443cbb158d32729d8c1ddf2806c8,0,0,0,0,0,0
23,5,4,R5F4,2000,1884,1884,51409c9f59674a63138b527a7d4753c0206df6db7f296cdfb2934f696e4e5529,9d32fa7417a73976100e3885238258014eca912a8cd57ab2f5fe5fe878a4fc01,0,0,0,0,0,0
24,5,5,R5F5,2000,1582,1582,2391105c200e4fdeb6c029045665dc1a38ddf42f5089c7b57e355c26999c3410,d8ad47423252e56f2b9f7c192ad803c710c710ebb8a9b8cbe2aef4214188df52,0,0,0,0,0,0

Exact fold assignment evidence contains 50,000 rows and is saved in the final JSON evidence.

     repeat  fold evaluation_id  link_test_doc_position  doc_id
0         1     1          R1F1                       0     285
1         1     1          R1F1                       3    1211
2         1     1          R1F1                       8    1918
3         1     1          R1F1                      10    2805
4         1     1          R1F1                      12    3459
..      ...   ...           ...                     ...     ...
195       1     1          R1F1                     932  208027
196       1     1          R1F1                     934  208908
197       1     1          R1F1                     940  210131
198       1     1          R1F1                     952  216855
199       1     1          R1F1                     958  217798

[200 rows x 5 columns]

Link-prediction method summaries based on repeat means

,method,fold_evaluations,independent_repeat_blocks,repeats,folds_per_repeat,roc_auc_mean,roc_auc_repeat_sd,roc_auc_fold_sd_descriptive,roc_auc_repeat_bootstrap_ci_low,roc_auc_repeat_bootstrap_ci_high,average_precision_mean,average_precision_repeat_sd,average_precision_fold_sd_descriptive,average_precision_repeat_bootstrap_ci_low,average_precision_repeat_bootstrap_ci_high,bootstrap_unit,bootstrap_resamples
0,Topic-K200,25,5,5,5,0.638747,0.002134,0.013711,0.637194,0.640374,0.616646,0.003310,0.013896,0.614276,0.619284,repeat mean,5000
1,Topic-K100,25,5,5,5,0.637640,0.002519,0.014568,0.635535,0.639452,0.622466,0.003730,0.013856,0.619475,0.625381,repeat mean,5000
2,Topic-K300,25,5,5,5,0.635944,0.002491,0.011908,0.633773,0.637721,0.619584,0.002886,0.012789,0.617505,0.621783,repeat mean,5000
3,DeepWalk,25,5,5,5,0.635835,0.003910,0.013907,0.633401,0.639260,0.625391,0.004570,0.014340,0.621865,0.629275,repeat mean,5000
4,Node2Vec,25,5,5,5,0.629731,0.004373,0.012590,0.626750,0.633218,0.616961,0.006414,0.013338,0.611764,0.621649,repeat mean,5000
5,Adamic-Adar,25,5,5,5,0.617266,0.001449,0.007322,0.616158,0.618449,0.628825,0.002207,0.008294,0.627445,0.630736,repeat mean,5000
6,Jaccard,25,5,5,5,0.602076,0.002041,0.009395,0.600555,0.603700,0.600870,0.003250,0.011284,0.598201,0.603280,repeat mean,5000
7,Preferential-Attachment,25,5,5,5,0.569291,0.000394,0.006086,0.569037,0.569630,0.595375,0.001763,0.007223,0.593864,0.596618,repeat mean,5000
8,Random,25,5,5,5,0.498698,0.002568,0.010662,0.496958,0.500747,0.499931,0.002526,0.008392,0.498403,0.502231,repeat mean,5000

Link-prediction Friedman tests

,metric,block_unit,blocks,methods,friedman_chi_square,raw_p,kendalls_w,alpha,significant_0_05,inference_scope
0,roc_auc,repeat mean across five document folds,5,"Topic-K100, Topic-K200, Topic-K300, Node2Vec, DeepWalk, Jaccard, Adamic-Adar, Preferential-Attachment, Random",35.840000,0.000019,0.896000,0.05,True,Exploratory repeat-level comparison; only five repeat blocks are available.
1,average_precision,repeat mean across five document folds,5,"Topic-K100, Topic-K200, Topic-K300, Node2Vec, DeepWalk, Jaccard, Adamic-Adar, Preferential-Attachment, Random",36.586667,0.000014,0.914667,0.05,True,Exploratory repeat-level comparison; only five repeat blocks are available.

All pairwise Wilcoxon tests with Holm correction

,metric,method_a,method_b,paired_repeats,mean_difference_a_minus_b,repeat_bootstrap_95_ci_low,repeat_bootstrap_95_ci_high,bootstrap_resamples,a_wins,ties,a_losses,wilcoxon_statistic,wilcoxon_raw_p,sign_test_raw_p,rank_biserial,alpha,inference_scope,wilcoxon_holm_p,sign_test_holm_p,significant_wilcoxon_holm_0_05,significant_sign_test_holm_0_05
0,roc_auc,Topic-K100,Topic-K200,5,-0.001108,-0.002301,0.000652,5000,1,0,4,4.0,0.4375,0.3750,-0.466667,0.05,"Exploratory; inference uses five repeat means, while fold-level rows remain descriptive.",1.0,1.0,False,False
1,roc_auc,Topic-K100,Topic-K300,5,0.001695,0.000403,0.003315,5000,4,0,1,1.0,0.1250,0.3750,0.866667,0.05,"Exploratory; inference uses five repeat means, while fold-level rows remain descriptive.",1.0,1.0,False,False
2,roc_auc,Topic-K100,Node2Vec,5,0.007909,0.002538,0.011226,5000,4,0,1,1.0,0.1250,0.3750,0.866667,0.05,"Exploratory; inference uses five repeat means, while fold-level rows remain descriptive.",1.0,1.0,False,False
3,roc_auc,Topic-K100,DeepWalk,5,0.001805,-0.001163,0.004430,5000,3,0,2,4.0,0.4375,1.0000,0.466667,0.05,"Exploratory; inference uses five repeat means, while fold-level rows remain descriptive.",1.0,1.0,False,False
4,roc_auc,Topic-K100,Jaccard,5,0.035564,0.032684,0.037571,5000,5,0,0,0.0,0.0625,0.0625,1.000000,0.05,"Exploratory; inference uses five repeat means, while fold-level rows remain descriptive.",1.0,1.0,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67,average_precision,Jaccard,Preferential-Attachment,5,0.005495,0.002161,0.008603,5000,5,0,0,0.0,0.0625,0.0625,1.000000,0.05,"Exploratory; inference uses five repeat means, while fold-level rows remain descriptive.",1.0,1.0,False,False
68,average_precision,Jaccard,Random,5,0.100939,0.095956,0.104876,5000,5,0,0,0.0,0.0625,0.0625,1.000000,0.05,"Exploratory; inference uses five repeat means, while fold-level rows remain descriptive.",1.0,1.0,False,False
69,average_precision,Adamic-Adar,Preferential-Attachment,5,0.033450,0.031768,0.034988,5000,5,0,0,0.0,0.0625,0.0625,1.000000,0.05,"Exploratory; inference uses five repeat means, while fold-level rows remain descriptive.",1.0,1.0,False,False
70,average_precision,Adamic-Adar,Random,5,0.128893,0.126519,0.131690,5000,5,0,0,0.0,0.0625,0.0625,1.000000,0.05,"Exploratory; inference uses five repeat means, while fold-level rows remain descriptive.",1.0,1.0,False,False
71,average_precision,Preferential-Attachment,Random,5,0.095443,0.093456,0.097068,5000,5,0,0,0.0,0.0625,0.0625,1.000000,0.05,"Exploratory; inference uses five repeat means, while fold-level rows remain descriptive.",1.0,1.0,False,False

Predeclared Topic-K200 comparisons

,metric,method_a,method_b,paired_repeats,mean_difference_a_minus_b,repeat_bootstrap_95_ci_low,repeat_bootstrap_95_ci_high,bootstrap_resamples,a_wins,ties,a_losses,wilcoxon_statistic,wilcoxon_raw_p,sign_test_raw_p,rank_biserial,alpha,inference_scope,wilcoxon_holm_p,sign_test_holm_p,significant_wilcoxon_holm_0_05,significant_sign_test_holm_0_05
0,roc_auc,Topic-K100,Topic-K200,5,-0.001108,-0.002301,0.000652,5000,1,0,4,4.0,0.4375,0.3750,-0.466667,0.05,"Exploratory; inference uses five repeat means, while fold-level rows remain descriptive.",1.0,1.0,False,False
8,roc_auc,Topic-K200,Topic-K300,5,0.002803,0.002251,0.003497,5000,5,0,0,0.0,0.0625,0.0625,1.000000,0.05,"Exploratory; inference uses five repeat means, while fold-level rows remain descriptive.",1.0,1.0,False,False
9,roc_auc,Topic-K200,Node2Vec,5,0.009017,0.004037,0.012953,5000,4,0,1,1.0,0.1250,0.3750,0.866667,0.05,"Exploratory; inference uses five repeat means, while fold-level rows remain descriptive.",1.0,1.0,False,False
10,roc_auc,Topic-K200,DeepWalk,5,0.002913,-0.001541,0.006016,5000,4,0,1,3.0,0.3125,0.3750,0.600000,0.05,"Exploratory; inference uses five repeat means, while fold-level rows remain descriptive.",1.0,1.0,False,False
11,roc_auc,Topic-K200,Jaccard,5,0.036671,0.034669,0.038396,5000,5,0,0,0.0,0.0625,0.0625,1.000000,0.05,"Exploratory; inference uses five repeat means, while fold-level rows remain descriptive.",1.0,1.0,False,False
12,roc_auc,Topic-K200,Adamic-Adar,5,0.021482,0.019623,0.023209,5000,5,0,0,0.0,0.0625,0.0625,1.000000,0.05,"Exploratory; inference uses five repeat means, while fold-level rows remain descriptive.",1.0,1.0,False,False
13,roc_auc,Topic-K200,Preferential-Attachment,5,0.069456,0.068008,0.070904,5000,5,0,0,0.0,0.0625,0.0625,1.000000,0.05,"Exploratory; inference uses five repeat means, while fold-level rows remain descriptive.",1.0,1.0,False,False
14,roc_auc,Topic-K200,Random,5,0.140049,0.137898,0.141940,5000,5,0,0,0.0,0.0625,0.0625,1.000000,0.05,"Exploratory; inference uses five repeat means, while fold-level rows remain descriptive.",1.0,1.0,False,False
36,average_precision,Topic-K100,Topic-K200,5,0.005820,0.004334,0.007817,5000,5,0,0,0.0,0.0625,0.0625,1.000000,0.05,"Exploratory; inference uses five repeat means, while fold-level rows remain descriptive.",1.0,1.0,False,False
44,average_precision,Topic-K200,Topic-K300,5,-0.002939,-0.003574,-0.002370,5000,0,0,5,0.0,0.0625,0.0625,-1.000000,0.05,"Exploratory; inference uses five repeat means, while fold-level rows remain descriptive.",1.0,1.0,False,False
45,average_precision,Topic-K200,Node2Vec,5,-0.000315,-0.007246,0.005724,5000,3,0,2,7.0,1.0000,1.0000,-0.066667,0.05,"Exploratory; inference uses five repeat means, while fold-level rows remain descriptive.",1.0,1.0,False,False
46,average_precision,Topic-K200,DeepWalk,5,-0.008746,-0.013946,-0.004285,5000,0,0,5,0.0,0.0625,0.0625,-1.000000,0.05,"Exploratory; inference uses five repeat means, while fold-level rows remain descriptive.",1.0,1.0,False,False
47,average_precision,Topic-K200,Jaccard,5,0.015776,0.012608,0.018943,5000,5,0,0,0.0,0.0625,0.0625,1.000000,0.05,"Exploratory; inference uses five repeat means, while fold-level rows remain descriptive.",1.0,1.0,False,False
48,average_precision,Topic-K200,Adamic-Adar,5,-0.012179,-0.013563,-0.010827,5000,0,0,5,0.0,0.0625,0.0625,-1.000000,0.05,"Exploratory; inference uses five repeat means, while fold-level rows remain descriptive.",1.0,1.0,False,False
49,average_precision,Topic-K200,Preferential-Attachment,5,0.021271,0.019740,0.023194,5000,5,0,0,0.0,0.0625,0.0625,1.000000,0.05,"Exploratory; inference uses five repeat means, while fold-level rows remain descriptive.",1.0,1.0,False,False
50,average_precision,Topic-K200,Random,5,0.116714,0.114365,0.120128,5000,5,0,0,0.0,0.0625,0.0625,1.000000,0.05,"Exploratory; inference uses five repeat means, while fold-level rows remain descriptive.",1.0,1.0,False,False

## 8. Claim-ready summary and integrity checks

[2026-07-24 17:20:26] Computing SHA-256 for the source dataset...

C:\Users\Amir\AppData\Local\Temp\ipykernel_2532\667818745.py:3339: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  "bertopic_all_runs_use_ctfidf": bool(bertopic_encoder_runs["c_tfidf_used"].fillna(False).all()),

Integrity checks — all must be True

                                                        check  passed
0                 full_dataset_scanned_raw_row_count_positive    True
1                          full_dataset_second_pass_completed    True
2             sampling_is_random_stratified_not_top_n_longest    True
3             sampling_covers_all_populated_raw_length_strata    True
4   sampling_preserves_stratum_proportions_within_0_5_percent    True
5                                   working_sample_size_50000    True
6                                         train_size_expected    True
7                              topic_validation_size_expected    True
8                                     link_test_size_expected    True
9                             all_analysis_role_overlaps_zero    True
10                                   core_four_models_present    True
11                                   core_topic_runs_complete    True
12                         parsbert_sensitivity_runs_complete    True
13                                  total_topic_runs_complete    True
14                                    all_core_metrics_finite    True
15                              bertopic_two_encoders_present    True
16                               bertopic_all_runs_use_ctfidf    True
17                        bertopic_all_coherence_values_valid    True
18                     ctm_uses_configured_training_documents    True
19                                 ctm_uses_configured_epochs    True
20                                 ctm_uses_official_fit_loop    True
21                          shared_vocabulary_size_within_cap    True
22                   all_core_models_record_shared_vocabulary    True
23                   ctm_vocabulary_matches_shared_vocabulary    True
24                               topic_friedman_tests_present    True
25                         topic_pairwise_tests_holm_complete    True
26                                   bootstrap_resamples_5000    True
27             statistical_grid_is_subset_of_descriptive_grid    True
28                    statistical_blocks_dynamic_and_complete    True
29                            model_revisions_are_commit_like    True
30                             stanza_resource_hashes_present    True
31               package_versions_match_reference_environment    True
32                        preprocessing_ablation_4x3_complete    True
33                      preprocessing_ablation_metrics_finite    True
34                 preprocessing_ablation_statistics_complete    True
35                             ner_train_documents_configured    True
36                         ner_link_test_documents_configured    True
37                       ner_train_error_rate_below_1_percent    True
38                        ner_test_error_rate_below_1_percent    True
39                     ner_no_fabricated_or_fallback_entities    True
40                             ner_only_six_predeclared_types    True
41              graph_constructed_from_training_entities_only    True
42                                   graph_node_cap_respected    True
43                            graph_has_1000_evaluation_nodes    True
44              graph_topic_sensitivity_k100_200_300_complete    True
45            link_prediction_expected_evaluations_per_method    True
46                      link_prediction_repeat_means_complete    True
47                             link_fold_assignments_complete    True
48                       link_evaluation_diagnostics_complete    True
49                                   link_pair_hashes_present    True
50                      link_prediction_all_9_methods_present    True
51                             link_prediction_metrics_finite    True
52                  link_prediction_no_positive_train_overlap    True
53                     link_prediction_no_forbidden_negatives    True
54                link_prediction_no_self_class_or_fold_reuse    True
55                                link_friedman_tests_present    True
56                          link_pairwise_holm_tests_complete    True
57                                json_file_created_and_valid    True
58                          markdown_report_created_and_valid    True
59            output_directory_contains_only_two_public_files    True

Primary publication table: common K=30

,model,model_family,benchmark_role,encoder,k,seeds,valid_topic_fraction_mean,reference_match_rate_mean,training_seconds_mean,training_seconds_sd,c_v_mean,c_v_sd,c_v_bootstrap_ci_low,c_v_bootstrap_ci_high,c_npmi_mean,c_npmi_sd,c_npmi_bootstrap_ci_low,c_npmi_bootstrap_ci_high,diversity_mean,diversity_sd,diversity_bootstrap_ci_low,diversity_bootstrap_ci_high,distinctness_mean,distinctness_sd,distinctness_bootstrap_ci_low,distinctness_bootstrap_ci_high,stability
0,BERTopic,BERTopic,core,multilingual-MiniLM,30,3,1.0,0.988889,17.105445,0.230980,0.546043,0.011756,0.538970,0.559614,0.082531,0.011424,0.071114,0.093962,0.812570,0.008473,0.804714,0.821549,0.989015,0.001121,0.987745,0.989868,0.815588
1,LDA,LDA,core,None,30,3,1.0,1.000000,86.158133,1.990793,0.521497,0.015000,0.504799,0.533830,0.062277,0.021771,0.038949,0.082056,0.716667,0.011547,0.710000,0.730000,0.971326,0.001837,0.969690,0.973314,0.378720
2,NMF,NMF,core,None,30,3,1.0,1.000000,18.697926,0.156333,0.497694,0.007968,0.490068,0.505964,0.162876,0.011360,0.152661,0.175111,0.545556,0.023413,0.523333,0.570000,0.947564,0.005277,0.941863,0.952277,0.785295
3,CTM,CTM,core,multilingual-MiniLM,30,3,1.0,1.000000,155.878748,4.527172,0.472204,0.009472,0.461361,0.478867,-0.072760,0.045493,-0.121539,-0.031487,0.691111,0.015396,0.673333,0.700000,0.978477,0.000668,0.977857,0.979185,0.221490

Metric-specific coherence maxima — interpret with the Pareto table

,model,model_family,benchmark_role,encoder,k,c_v_mean,c_v_sd,c_v_bootstrap_ci_low,c_v_bootstrap_ci_high,c_npmi_mean,c_npmi_sd,c_npmi_bootstrap_ci_low,c_npmi_bootstrap_ci_high,diversity_mean,diversity_sd,distinctness_mean,distinctness_sd,stability,valid_topic_fraction_mean,reference_match_rate_mean,training_seconds_mean
0,BERTopic,BERTopic,core,multilingual-MiniLM,10,0.637101,0.004921,0.631418,0.639943,0.250526,6.957303e-03,0.242492,0.254543,0.860000,0.000000,0.982206,0.000000,0.987879,1.0,1.000,13.118121
1,NMF,NMF,core,None,5,0.622230,0.000000,0.622230,0.622230,0.344959,6.798700e-17,0.344959,0.344959,0.880000,0.000000,0.967251,0.000000,1.000000,1.0,1.000,9.468156
2,BERTopic-ParsBERT,BERTopic,encoder_sensitivity,ParsBERT-mean-pooling,10,0.586569,0.004719,0.583571,0.592008,0.252213,8.799375e-03,0.242052,0.257295,0.786667,0.005774,0.965800,0.001100,0.799822,1.0,1.000,12.688086
3,LDA,LDA,core,None,30,0.521497,0.015000,0.504799,0.533830,0.062277,2.177140e-02,0.038949,0.082056,0.716667,0.011547,0.971326,0.001837,0.378720,1.0,1.000,86.158133
4,CTM,CTM,core,multilingual-MiniLM,20,0.493161,0.022098,0.469742,0.513644,-0.089281,4.427812e-03,-0.092597,-0.084253,0.771667,0.033292,0.980462,0.003000,0.224601,1.0,0.995,148.839394

Publication-ready link-prediction table

,method,fold_evaluations,independent_repeat_blocks,repeats,folds_per_repeat,roc_auc_mean,roc_auc_repeat_sd,roc_auc_fold_sd_descriptive,roc_auc_repeat_bootstrap_ci_low,roc_auc_repeat_bootstrap_ci_high,average_precision_mean,average_precision_repeat_sd,average_precision_fold_sd_descriptive,average_precision_repeat_bootstrap_ci_low,average_precision_repeat_bootstrap_ci_high,bootstrap_unit,bootstrap_resamples
0,Topic-K200,25,5,5,5,0.638747,0.002134,0.013711,0.637194,0.640374,0.616646,0.003310,0.013896,0.614276,0.619284,repeat mean,5000
1,Topic-K100,25,5,5,5,0.637640,0.002519,0.014568,0.635535,0.639452,0.622466,0.003730,0.013856,0.619475,0.625381,repeat mean,5000
2,Topic-K300,25,5,5,5,0.635944,0.002491,0.011908,0.633773,0.637721,0.619584,0.002886,0.012789,0.617505,0.621783,repeat mean,5000
3,DeepWalk,25,5,5,5,0.635835,0.003910,0.013907,0.633401,0.639260,0.625391,0.004570,0.014340,0.621865,0.629275,repeat mean,5000
4,Node2Vec,25,5,5,5,0.629731,0.004373,0.012590,0.626750,0.633218,0.616961,0.006414,0.013338,0.611764,0.621649,repeat mean,5000
5,Adamic-Adar,25,5,5,5,0.617266,0.001449,0.007322,0.616158,0.618449,0.628825,0.002207,0.008294,0.627445,0.630736,repeat mean,5000
6,Jaccard,25,5,5,5,0.602076,0.002041,0.009395,0.600555,0.603700,0.600870,0.003250,0.011284,0.598201,0.603280,repeat mean,5000
7,Preferential-Attachment,25,5,5,5,0.569291,0.000394,0.006086,0.569037,0.569630,0.595375,0.001763,0.007223,0.593864,0.596618,repeat mean,5000
8,Random,25,5,5,5,0.498698,0.002568,0.010662,0.496958,0.500747,0.499931,0.002526,0.008392,0.498403,0.502231,repeat mean,5000

Claim-ready statements

,area,statement_type,claim_ready_statement,statistically_validated,scope
0,dataset,observation,"The complete source file contained 2,525,369 rows. After language eligibility screening and text-hash deduplication,...",None,Descriptive source-corpus audit.
1,sampling,methodological fact,"A proportional raw-length-stratified random sample of 50,000 documents was drawn from the full eligible corpus; the ...",None,Reproducible sampling procedure conditional on seed 42.
2,topic modeling,observation,"At the predeclared common topic count K=30, the four model families were compared under the same held-out corpus and...",False,Primary matched-K descriptive comparison; model-specific optima are secondary sensitivity analyses.
3,topic modeling,observation,"At K=30, BERTopic had the highest mean C_v (0.5460); NPMI, diversity, distinctness, and stability are reported besid...",False,Primary common-K descriptive result with explicit multi-metric qualification.
4,topic modeling,observation,"When each core model was allowed to choose its own coherence-maximizing K, BERTopic achieved the highest mean C_v (0...",False,Descriptive metric-specific selection; no composite quality score is used.
5,topic modeling,exploratory inference,"Across the 27 matched K × seed configurations in the fixed statistical grid, NMF had the highest mean C_v (0.5312); ...",True,Exploratory paired inference across the fixed statistical K grid; model-specific maxima are descriptive only.
6,BERTopic encoder sensitivity,exploratory inference,"Under fixed BERTopic settings, mean-pooled ParsBERT minus multilingual MiniLM produced a mean C_v difference of 0.00...",True,"Conditional on mean pooling, truncation length, UMAP, KMeans, and c-TF-IDF parameters."
7,NER,observation,"Stanza extracted 47,493 accepted training mentions and 45,947 accepted link-test mentions from 10,000 training and 1...",None,Typed normalized surface forms; no entity linking or canonical disambiguation.
8,entity graph,observation,"The training-only graph retained 5,000 typed surface-form nodes and 57,696 document co-occurrence edges.",None,"Entity association graph, not a multi-relational knowledge graph."
9,link prediction,observation,The predeclared Topic-K200 method achieved mean ROC-AUC 0.6387 and mean average precision 0.6166; means and uncertai...,False,Descriptive repeated cross-validation result.
10,link prediction,exploratory inference,"Relative to the strongest non-topic baseline (DeepWalk), Topic-K200 had a mean ROC-AUC difference of 0.0029 (repeat-...",False,Exploratory repeat-level inference based on five repeat means; all evidence derives from Persian Wikipedia.

Explicit limitations and inference scope

                          limitation                                                                                                                statement
0           Hash-based deduplication  Corpus-scale deduplication uses pandas' stable 64-bit text hash for tractability. Collisions are extremely unlikely ...
1           Shared-source evaluation  Preprocessing, topics, named entities, graph edges, and held-out links originate from the same Wikipedia source, alt...
2                 Domain specificity  Results describe Persian Wikipedia and do not establish population-level generalization to social media, news, conve...
3                CTM training budget  CTM uses the official CombinedTM.fit loop for ten epochs and the shared 10,000-term vocabulary; conclusions remain c...
4                   ParsBERT pooling  ParsBERT is a masked-language-model checkpoint converted to document embeddings through mean pooling; it is not a Pe...
5   Encoder/parameter conditionality  BERTopic conclusions are conditional on the selected encoders, 256-token truncation, UMAP, KMeans, Persian whitespac...
6                No human validation  This pipeline contains no human topic-interpretability or edge-validity annotations and makes no inter-rater-reliabi...
7             Three-seed uncertainty  Topic-model means and seed-bootstrap intervals are based on only three predeclared random seeds; they characterize i...
8            Repeated-fold inference  Repeated cross-validation folds overlap; Wilcoxon tests and bootstrap intervals are exploratory rather than independ...
9                     NER truncation  NER processes at most the first 5,000 characters of each document; entities appearing later in long documents are no...
10                 Head-entity graph  The graph retains the 5,000 most frequent typed nodes, at most 30 retained entities per document, and the link evalu...
11          Near-duplicate documents  Exact text-hash duplicates are removed, but semantic or near-duplicate pages and revisions are not explicitly cluste...
12             Surface-form entities  Nodes are typed normalized surface forms. Homonyms are not disambiguated and aliases are not linked to canonical ent...

## 9. Final files

====================
FINAL FILES
====================
JSON evidence: C:\Users\Amir\Desktop\My Desk\Desktop 20260506\Articles\Second article\FInilized\version 8 (last run)\q1_final_run\q1_final_evidence.json
Markdown report: C:\Users\Amir\Desktop\My Desk\Desktop 20260506\Articles\Second article\FInilized\version 8 (last run)\q1_final_run\q1_final_report.md
JSON SHA-256: ccb6715e88fedf75cd939a84a6fcda4c937123b80bfc67eb4fe034da57de7810
Markdown SHA-256: 29eca145d8ef9318e8703b431d9719e83e4d87f83402f223bf31b2afbc36f30e
Dataset SHA-256: 63fa7270b573b0b0dd72a46a8441fc8cc09cd958e524f88792f607ea65109406
Runtime: 10.32 hours

All integrity checks passed. No figures, dummy entities, fabricated topics, or fabricated statistical results were generated.
Inference remains exploratory where stated and is not population-level generalization.